[Step4] 블랙잭 (베팅)
next-step/kotlin-blackjack pull request #100
Opened 2021-03-28 14:56 UTC by begaonnuri

구현이 늦어졌네요 😭 
많은 지적 부탁드리겠습니다..!

2021-03-29 16:49 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/BettingMoneys.kt
> +}
미션의 내용과는 별개지만 참고가 되실까봐 내용 첨부합니다.

파일의 끝에 newline을 포함해주시면 좋을 것 같아요
POSIX 표준에 맞지 않기도 하고 작업 시 newline을 붙이는데 다른 작업자가 붙이지 않는 경우 불필요한 file change가 생기기도 합니다.

저 같은 경우 IntelliJ에서 newline을 자동으로 추가하는 설정을 사용하고 있습니다.

![image](https://user-images.githubusercontent.com/34656258/81493539-030f0d80-92dc-11ea-8129-756ca65b99cc.png)

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/BettingMoneys.kt
> +}
추가로 ktlint에서 newline을 체크해줄텐데

ktlint 설정이 제대로 되었는지 체크해보시면 좋을 것 같아요.

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    private fun calculateProfit(_player: User, dealer: User): BettingMoney {
제가 잘못 알고 있을 수도 있는데..
`Backing Properties`를 사용하는 경우 이외에 `_`로 시작하는 명명 규칙은 따로 없었던 것 같아요.

```suggestion
    private fun calculateProfit(player: User, dealer: User): BettingMoney {
```

파라미터로 넘어간 값과 지역 변수 이름이 같으면 `shadowing` 때문에 warning이 발생하긴 하겠네요..
이 경우 어떻게 변수명을 지정하면 좋을까요? 🤔 

그냥 _로 파라미터를 넘겨줘도 warning이 뜨지 않으니 사용하는게 좋을까요?

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    }
`Player`의 `BettingMoney`를 구하는 private 메소드로 보이네요.

현재 `player`의 참조를 넘긴 뒤 `player` 참조를 받아 함수 호출을 이용해 결과를 반환하고 있어요.

오브젝트라는 책에 보면 `INFORMATION EXPERT(정보 전문가)` 패턴에 대한 내용이 포함되어 있습니다.
단순하게 정보를 가진 곳에 책임을 위치한다는 내용인데요, 그 관점에서 보면 `Player`에 이 책임이 있어도 괜찮을 것 같아요.

물론 실제 블랙잭에서 유저가 배팅 금액까지 정해버리는건 조금 이상하긴 하죠.
의도하신 내용이 `GameResult`에 책임을 위치시키는거라면 그대로 두어도 상관없습니다~

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/Score.kt
> +    fun compareTo(other: Score): ResultType = ResultType.of(this, other)
크게 의미는 없지만 `infix`를 사용해볼수도 있을 것 같아요~

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/player/Users.kt
> +    fun doDealer(action: (Dealer) -> Unit) = action(users[0] as Dealer)
`BlackjackController`의 run 메소드에서 dealer와 player를 나누는건 어떨까요?

0번째의 player 요소를 꺼내 Delaer로 사용하는 부분과 `as Player, as Dealer`와 같이 캐스팅이 일어나는 부분들을 보다보니

Users는 Player만 다루고 딜러를 따로 빼서 컨트롤하는건 어떨까 하는 생각이 드네요.

2021-03-29 16:49 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/BettingMoney.kt
> +    fun multiply(rate: Double) = BettingMoney(money * rate)
operator overloading을 사용해보는건 어떨까요?

```suggestion
    operator fun times(rate: Double) = BettingMoney(money * rate)
```

https://kotlinlang.org/docs/operator-overloading.html#arithmetic-operators

2021-03-29 17:02 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/BettingMoneys.kt
> +}
린트 말고도 인텔리제이 설정이 있었군요..! 감사합니다

2021-03-29 17:03 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/BettingMoneys.kt
> +}
린트 적용 후에 수정을 해서 이 클래스만 빠졌나보네요 🥲

2021-03-29 17:07 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    private fun calculateProfit(_player: User, dealer: User): BettingMoney {
파라미터로도 플레이어란것을 명시해줘야하고, 함수 스코프 안에서도 플레이어라고 표현하는 것이 적절하다고 생각해서 사용했습니다.
함수 스코프 안에서는 gamePlayer라고 지정하려다가 오히려 플레이어와 게임플레이어가 다른가?라는 혼란을 줄 수 있을것 같더라구요.
이 부분에 대한 컨벤션은 저도 잘 모르겠지만 사용해봤더니 썩 나쁘지는 않은것 같네요 😢

2021-03-29 17:09 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/Score.kt
> +    fun compareTo(other: Score): ResultType = ResultType.of(this, other)
오 배웠던 것을 한번 활용해보겠습니다
사용해도 적절한 부분 같네요!

2021-04-01 15:01 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    }
오 그렇게도 구현할 수 있겠군요!

> 물론 실제 블랙잭에서 유저가 배팅 금액까지 정해버리는건 조금 이상하긴 하죠.

저도 이렇게 생각했었고, 비교적 직관적이게 게임 결과 객체가 결과(현재는 수익=결과)를 구한다는 관점에서 이렇게 구현했습니다!
새로운 관점을 알려주셔서 감사합니다!

2021-04-01 15:06 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/Score.kt
> +    fun compareTo(other: Score): ResultType = ResultType.of(this, other)
infix를 활용했는데,
[전에 리뷰 주셨던 부분](https://github.com/next-step/kotlin-blackjack/pull/78#discussion_r596959005) (score를 어떻게 처리할지 생각해보라는) 을 다시 함수에서 프로퍼티로 변경했습니다.

infix가 주는 자연어처럼 읽힌다는 장점을 더 살리는 것 같다고 생각했습니다 :)

2021-04-01 15:12 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/player/Users.kt
> +    fun doDealer(action: (Dealer) -> Unit) = action(users[0] as Dealer)
2단계까지 그렇게 구현했었는데 구현을 하면서는,
1. 일괄적으로 동작하는 기능을 한번에 처리한다는 점
2. 프로퍼티가 하나가 된다는 점(List<Player>, Dealer가 아닌 List<User>)

이것들의 장점이 조금 더 와닿았습니다.
지금은 트레이드오프가 비슷한것 같은데 기능이 확장되었을 때 일괄적인 기능이 많아지는지, 캐스팅하는 포인트가 늘어나는지에 따라 구현 방향을 따라갈 것 같습니다 :)

2021-04-01 15:29 UTC, begaonnuri commented on src/main/kotlin/blackjack/domain/BettingMoney.kt
> +    fun multiply(rate: Double) = BettingMoney(money * rate)
배워놓고 안쓰고있었네요😅
덕분에 적용했습니다 감사합니다~

2021-04-02 13:07 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    private fun calculateProfit(_player: User, dealer: User): BettingMoney {
warning도 별도로 안 잡혀서 요렇게 사용해도 괜찮을 것 같네요 ㅎㅎ

2021-04-02 13:08 UTC, kyucumber approved these changes
블랙잭 마지막 미션까지 구현하시느라 고생 많으셨습니다~

다음 단계 진행을 위해 머지할게요.

2021-04-02 13:08 UTC, merged