[Step2] 블랙잭
next-step/kotlin-blackjack pull request #131
Opened 2021-11-13 16:55 UTC by Flamme1004K

안녕하세요! 리뷰어님!

블랙잭 미션 구현하여 리뷰 요청 남깁니다 😊

블랙잭이라는 게임을 한번도 안해봐서, 요번에 구현하는데 생각보다 오랜 시간이 걸렸네요.

블랙잭 게임에 대해서 도메인을 찾아보고, 블랙잭 게임을 직접하면서 구현을 해봤는데, 게임머니를 탕진했다는 것 빼고는 좋은 경험을 한 것 같습니다.😭😭😭

이러한 경험을 하게 해주셔서 감사합니다 👍👍

2021-11-13 17:00 UTC, Flamme1004K commented on src/main/kotlin/blackJack/dto/PlayersDto.kt
> +            val cards = player.status.cards.toList().joinToString {
리뷰어님 질문이 있습니다.

항상 클래스의 값을 꺼내올때는  get을 선언해서 가지고 왔는데, 

코틀린은 위와 같이`player.status.cards.toList` 이렇게 꺼내와도 괜찬으려나요?

아니면 해당 부분을 위해서 player에서 getCardsList라는 함수를 만들어서

getCardsList에서는 status.cards.toList()를 반환하도록 만들어야할까요?🤔🤔

2021-11-13 17:01 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/Players.kt
> +        }
요즘들어 map을 사용할 때는 it을 그대로 넣어주는 것 보다 player 같이 변경을 시켜줘서 넣어주려고 하는데,

이렇게 변경해서 넣어주는게 더 가독성을 좋게 만드려나요?🤔

2021-11-14 06:02 UTC, vsh123 requested changes
형준님 안녕하세요!
전체적으로 구현 잘해주셨네요 💯 

몇가지 코멘트와 질문주신 내용에 대한 답변을 남겼으니,
궁금하신 점은 언제든 DM주세요!

2021-11-14 06:02 UTC, vsh123 commented on src/main/kotlin/blackJack/controller/BlackJackController.kt
> +            _player = continuousReceiveCard(_player, playingCard)
카드를 새로 받으면, 새로운 Player객체가 생성되니까 위와 같이 로직이 짜진 것 같은데요!
copy를 활용하지 않은 방식으로 변환 후 해당 함수들을 다시한번 고민해보세요!

2021-11-14 16:28 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/Players.kt
> +        }
확실히 it 대신에 player라는 것을 선호했을 때는 코드 상으로 명확해서 좋았는데, 다시 생각을 해보니,

ide 차원에서 it이 player라는 것을 알려주고 있으니, 딱히 크게 명시할 이유가 없는 것 같습니다.😅

2021-11-14 16:34 UTC, Flamme1004K commented
안녕하세요~ 리뷰어님 

피드백 주신 부분 변경하여 리뷰 요청 드립니다 !

요번에도 잘 부탁드립니다 ㅎㅎ

2021-11-14 16:36 UTC, Flamme1004K commented
```
it keyword에 대해 읽어보시구, 왜 kotlin이 해당 키워드를 제공했을지 생각해보면 좋을 것 같아요!

개인적으로는 저도 자바를 많이 사용해서 그런지 player와 같이 명시적인 키워드를 선호하긴 하지만 이게 코틀린스러운 코딩인가?라는 것에 대해 의문을 갖곤 하는데요! 이에 대한 형준님의 의견도 궁금합니다 :)
```

 생각을 해봤는데, ide이 차원에서 "it은 player다" 라는것을 알켜주기 때문에, 크게 it이 무엇인지에 대해서 명시할 필요가 없을 것 같다는 결론을 냈습니다. 해당 의견에 대해서 어떻게 생각하시나요 리뷰어님 ??🤔🤔🤔

2021-11-14 16:54 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/Player.kt
>      }
functional Programming을 이용하여 구현을 하던 도중에, 상태에 대한 변경에 대해 Player라는 것에 대해 불변을 어떻게 지키는게 좋을까하여 상태를 업데이트 하는 곳 마다 copy된 Player를 리턴 받도록 만들었습니다.

하지만, 리뷰어님이 피드백 해주신 부분 중에 

1. data class로 선언하게 되면 이름이 같은 Player인 경우에 같다고 판단할 것같은데, data class로의 선언이 괜찮을지 생각해보면 좋을 것 같아요!
2. 카드를 새로 받으면, 새로운 Player객체가 생성되니까 위와 같이 로직이 짜진 것 같은데요!
copy를 활용하지 않은 방식으로 변환 후 해당 함수들을 다시한번 고민해보세요!

을 읽고 Player 이름이 중복되는 상황에 대해서 생각을 못했구나. 라고 생각하여, Player를 일반 클래스로 변경을 하였습니다.

이렇게 일반 클래스로 변경을 하니깐, 이제 copy()에 대한 부분도 변경이 필요하더군요.

현재는 PlayerStatus를 backing properties로 만들어서 상태에 대해 업데이트 되도록 코드를 변경을 했습니다.

여기서 질문입니다.

1. Backing properties를 사용하는 것이 불변을 지켜주기 위한 방법 중에 하나일까요?
2. copy()를 사용해야할 떄는 언제일까요?
 
현재 Player에 대해서는 일반 클래스로 만들긴 했는데, copy를 지속적으로 사용하는 클래스인 PlayerStatus가 있는데, 해당 클래스를 계속 data class로 사용을 해야할지, 아니면 class로 변경을 해줘야할지 감이 안옵니다😭

2021-11-14 17:08 UTC, Flamme1004K commented
리뷰어님, 오후에 질문에 대한 답변 너무 감사합니다.
```
정말 get을 해야하는가?
get하지 않고 메세지를 던져 결과를 받을 수는 없는 건인가?
```

--> 해당 내용에 대해 참고하여, 저의 코드를 봤는데, 많은 부분이 메시지를 던져 결과를 받을 수 있었습니다.😊

생각을 전환시켜주셔서 너무 감사합니다!🙇🏻

```
business Layer에서의 getter는 지양
domain -> dto와 같이 convert를 위한 getter는 어쩔 수 없다고 생각
```

-->  여기서 질문이 있는데요.🤔

dto에 값을 넣어주기 위한 getter는 어쩔 수 없다고 하신 이유는, dto와 도메인은 분리되어야하기 때문인가요?

2021-11-14 17:11 UTC, Flamme1004K commented on src/main/kotlin/blackJack/controller/BlackJackController.kt
>          return player
Player가 playerStatus !is BlackJack의 결과를 리턴해주는 함수를 구현을 해봤는데, Player에게 블랙잭인지에 대한 상태 유무를 메시지를 받음으로써 코드가 훨씬 깔끔해지는 것을 볼 수가 있었습니다.

가르침 감사합니다 리뷰어님!👍👍👍

2021-11-14 17:14 UTC, Flamme1004K commented on src/test/kotlin/blackJack/domain/PlayingCardTest.kt
> +}
draw()에 대한 테스트는 CardsTest 중에 `카드 뭉치(52장)에서 1장을 빼면 51장이다` 라는 것으로 충분하다고 생각을 했는데,

더 치밀하게 테스트 케이스를 만들었었어야 했네요.😅

테스트 케이스 작성에 대해 좀 더 치밀해져야 되겠습니다!😁

가르침 감사합니다!🙇🏻

2021-11-15 12:42 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/Player.kt
>      }
> Backing properties를 사용하는 것이 불변을 지켜주기 위한 방법 중에 하나일까요?

Backing propperties를 이용한 방법은 외부에서 variable한 필드의 수정을막기 위해 많이사용되는 방법중에 하나입니다.(불변을 보장한다라하면 내부에서도 해당 프로퍼티의 값을 바꾸면 안될 것 같은..)
사실 Player의 status는 private이기 때문에 위와 같이 하지 않았어도 되지만, 이러한 방법도 있다는 것을 알려드리고 싶었습니다!!
또 다른 방법으로는 getter만 노출하고 setter만을 제한하는 방법이 있는데요!
아래와 같은 방법으로 외부에서 status에 대한 set을 막을수도 있습니다 :) 

생각해보니 이번 케이스에서는 아래와 같은 방법이 조금 더 나을 수 있었을 것 같네요!

```kotlin
class Player(val playerName: String) {
    var status: PlayerStatus = PlayerStatus.of()
        private set
```


> copy()를 사용해야할 떄는 언제일까요?

`copy()` 는 kotlin에서 data class 선언 시 자동적으로 지원해주는 함수중에 하나인데요!!
그렇다면 data class의 목적은 무엇일까요??

[data class](https://kotlinlang.org/docs/data-classes.html)에 대한 공식 레퍼런스를 읽어보시고, 어떠한 경우에 data class를 사용하면 좋을지 생각해보신다면, 어느 시점에 copy를 사용해야하는지 알 수 있을 것 같아요!!!

2021-11-15 12:47 UTC, vsh123 commented
> dto에 값을 넣어주기 위한 getter는 어쩔 수 없다고 하신 이유는, dto와 도메인은 분리되어야하기 때문인가요?

도메인 객체를 dto로 변환하는 방법은 크게 두가지가 있을 것 같은데요

1. 도메인 객체에서 dto로 변환해서 리턴 (getter 필요 x)
2. 도메인 객체를 dto로 변환해주는 factory사용(getter 필요 o)

첫번째 방법을 사용하지 않는다면 결국은 getter를 사용할 수 밖에 없다는 걸 전달드리고 싶었어요!
하지만 첫번째 방법은 도메인 객체 안에 dto에 대한 의존이 생긴다고 봐야하기 때문에,
이러한 방법은 지양하고 있습니다 :) 

혹시 이에 대해 궁금하거나 다른 의견이 있으시다면 말씀 주셔요!!

2021-11-15 12:50 UTC, vsh123 commented
>  ide이 차원에서 "it은 player다" 라는것을 알켜주기 때문에, 크게 it이 무엇인지에 대해서 명시할 필요가 없을 것 같다는 결론을 냈습니다. 

`ide레벨에서 it은 player다`라는 것을 알려주기 때문이라는 말에 공감이 됩니다 :)
추가적으로 함께 업무를 진행하는 개발자와 소통하는 부분에 있어서도 it으로 사용하는 것이 커뮤니케이션적인 측면에서도 더 낫다고 생각합니다!! (이는 팀마다 다르겠지만, 공식 레퍼런스가 아무래도 대중적이겠죠..?)

2021-11-15 12:53 UTC, vsh123 approved these changes
안녕하세요!! 
피드백 반영 잘해주셨네요! 💯 

빠른 진행을 위해 이번스텝은 머지하도록 하겠습니다 :) 

다음스텝도 화이팅 하세요!!

2021-11-15 12:53 UTC, vsh123 commented on src/main/kotlin/blackJack/view/InputView.kt
> +        return when (readLine()!!) {
이렇게 강제 not null처리는 kotlin에서 지원하는 null safety함을 훼손하는 방법일 수 있을 것 같아요!
별도로 null체크를 진행해보면 어떨까요?

2021-11-15 12:53 UTC, merged