[STEP2] 블랙잭
next-step/kotlin-blackjack pull request #134
Opened 2021-11-14 11:26 UTC by etff

난이도가 올라서 미션 구현하면서 아쉬웠던 점이 많네요. 
리뷰 잘 부탁드립니다.

2021-11-15 13:19 UTC, ka0oll requested changes
요구사항 잘 구현해주셨네요 👍 

몇가지 코멘트 남겼습니다. 확인부탁드려요.

2021-11-15 13:19 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +            receivedCardPlayers = receivedCardPlayers.updatePlayerStatus(receiveCardPlayer, update)
player가 카드를 받는 행위를 일급 컬렉션인 players가 하는게 어떨까요? controller에서의 비지니스 로직을 줄일수 있을거 같아요.

2021-11-15 13:19 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +            receiveCardPlayer = updatedStatus
요기도 input으로부터 turnOn여부를 전달받아서 비지니스 로직을 처리하는게 Players 일급 컬렉션에 역할 같아요.

2021-11-15 13:19 UTC, ka0oll commented on src/main/kotlin/blackjack/domain/Cards.kt
> +package blackjack.domain
여러 도메인 클래스들을 서브 패키지화 하면 가독성이 더 좋을거같아요.

2021-11-15 13:19 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +        receivedCardPlayers = receivedCardPlayers.updatePlayerStatus(receiveCardPlayer, receiveCardPlayer.turnOff())
여기도 일급 컬렉션의 역할 같아요!

2021-11-15 14:25 UTC, etff commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    val cards = generateCards()
테스트를 먼저짜다 보니 굳이 필요없는 필드를 공개했네요.
나중에 이런것도 리팩터링 대상이군요!

2021-11-15 15:14 UTC, etff commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +            receivedCardPlayers = receivedCardPlayers.updatePlayerStatus(receiveCardPlayer, update)
도메인 객체인 players에게 중간중간 input을 어떻게 받을 수 있을까요? 👀

2021-11-15 15:28 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +            receivedCardPlayers = receivedCardPlayers.updatePlayerStatus(receiveCardPlayer, update)
input을 전달하기 어렵다면, 현재의 구현 상황상 receivedCardPlayers.receviedCard(receiveCardPlayer, card) 가 될수도 있을거같아요.
일급 컬렉션이 player가 card를 받는 책임을 가지는게 어떤가 싶었어요 🤔

2021-11-15 16:51 UTC, etff commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +            receiveCardPlayer = updatedStatus
수정했습니다

2021-11-15 16:52 UTC, etff commented
어떻게 해야할지 감을 못잡았는데, 코멘트에 맞춰 수정했습니다.

2021-11-16 13:43 UTC, ka0oll approved these changes
빠르게 피드백 반영 잘해주셨네요. 👍 
 
추가적인 코멘트 남겨요. 다음 스텝에서 함께 고민해주세요!
다음 스텝도 화이팅 입니다.

2021-11-16 13:43 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
>          }
처음시작시 카드 두개를 받는게 도메인 영역이 아닌가 싶어요.

2021-11-16 13:43 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +    }
players에서 player를 조회해서 카드를 전달하기 보단 players에게 isPlayerTurnOff()에 해당하는 람다(인터페이스를 전달한다면) 더 깔끔해질거같아요!. 고민해보세요.

2021-11-16 13:43 UTC, ka0oll commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +        }
처음 두장을 받고 시작하는건 도메인 로직이 아닐까 싶어요!

2021-11-16 13:44 UTC, merged

2021-11-16 14:16 UTC, etff commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +        }
플레이어 목록에서 게임의 초기 플레이어가 해야하는 영역으로 두면 좋을 것같네요!