Step3 블랙잭(딜러)
next-step/kotlin-blackjack pull request #139
Opened 2021-11-15 17:50 UTC by sangyongchoi

안녕하세요. 리뷰어님

질문사항입니다.
1. ```card.denomination도 일종의 getter인데요! 해당getter를 없애보면 어떨까요?``` 이런 코멘트를 주셔서 수정을 해보았는데 의도하신게 맞는지 궁금합니다.

2. 프로그래밍 요구사항중에 딜러와 플레이어의 중복로직을 없애라는 요구사항이 있었습니다.
최대한 잘 풀어보려고 노력했으나, 맞는 방향인지 헷갈립니다.
제가 구현한 방향이 아닌 더 나은 방법이 또 있을까요 ?

3. 프로그래밍 요구사항중에 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다는 요구사항이 있습니다. 제가 구현한 방식에서는 CardDenomination enum class 가 4개의 변수를 가집니다. enum class 라서 요구사항을 벗어나는것인지, 예외인것인지 헷갈립니다.

이번에도 리뷰 잘 부탁드리겠습니다.
감사합니다 :)

2021-11-16 05:46 UTC, vsh123 requested changes
안녕하세요!!
구현 잘해주셨네요! 👍 

질문주신 내용에 대한 답변과 몇가지 코멘트를 남겼으니 확인부탁드리겠습니다!! :)

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/card/CardDenomination.kt
> +    val getValue: (Int) -> Int = { _ -> value[BASIC_VALUE_INDEX] },
> 프로그래밍 요구사항중에 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다는 요구사항이 있습니다. 제가 구현한 방식에서는 CardDenomination enum class 가 4개의 변수를 가집니다. enum class 라서 요구사항을 벗어나는것인지, 예외인것인지 헷갈립니다.

해당 요구사항의 목적은 하나의 객체가 너무 많은 책임을 갖지 않게 하는 것에 있습니다!! 지금 `CardDenomination`이 4개의 변수를 갖고 있다는 건 해당 객체를 조금 더 작게 쪼갤 수 있지 않을까 하는 고민을 해볼만한 시기일 것 같아요!

객체의 책임을 분리해보면 어떨까요?

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/card/Card.kt
> +    fun getValue(sum: Int): Int = denomination.getValue(sum)
> card.denomination도 일종의 getter인데요! 해당getter를 없애보면 어떨까요? 이런 코멘트를 주셔서 수정을 해보았는데 의도하신게 맞는지 궁금합니다.

넵!! 제가 의도한 부분은 요게 맞아용!!
코드를 작성할 때 객체가 가지고 있는 property를 꺼내는 것보다 메세지를 전달하는 것을 습관화 하면 좋을 것 같아요!

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/card/CardDenomination.kt
> +        if (sum + 11 > 21) ACE.value[BASIC_VALUE_INDEX]
`value` property가 필요할까요?

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Participant.kt
> +abstract class Participant(
> 프로그래밍 요구사항중에 딜러와 플레이어의 중복로직을 없애라는 요구사항이 있었습니다.
최대한 잘 풀어보려고 노력했으나, 맞는 방향인지 헷갈립니다.
제가 구현한 방향이 아닌 더 나은 방법이 또 있을까요 ?

상속 방식은 중복을 제거할 수 있는 가장 좋은방법중에 하나인 것 같아요!! 잘 구현해주셨습니다! 👍 
하지만 이펙티브 자바에서는 상속보다는 컴포지션을 활용하라고 가이드주고 있는데요!
[상속보다 컴포지션](https://smjeon.dev/etc/composite-extends/)을 활용해서 구현해보면 어떨까요?
어떤 장단점이 있을까요??

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/presentation/BlackjackGame.kt
> +        (listOf(dealer) + players).forEach { player ->
Players객체를 이전에 해당 로직 이전에 생성한다면,  해당 로직을 Players안으로 넣을 수 있을 것 같은데, 어떻게 생각하시나요~?

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Players.kt
> +class Players(
* `Players`는 일급컬렉션을 의도하여 작성하신걸까요? 그렇다면 [일급 컬렉션](https://jojoldu.tistory.com/412)에 대해 읽어보시구, 해당 객체가 일급컬렉션이 맞는지 확인해보면 좋을 것 같아요~!
* `Dealer`는 Player가 아닌데, Players라는 네이밍이 올바를까요??

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        ?.let {
let 활용 👍

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/BlackjackApplication.kt
>          while (player.getCardSum() <= 21 && wantMoreCard) {
해당 부분도 `getCardSum()`을 하기보다는 Player가 카드를 더 받을 수 있는 상태인지를 판단하는 함수를 만들어보면 어떨까요?

2021-11-16 05:46 UTC, vsh123 commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +            println("딜러는 16이하라 한장의 카드를 더 받았습니다.")
해당 출력도 View에 넘기는 건 어떨까요?

2021-11-16 17:26 UTC, sangyongchoi commented on src/main/kotlin/blackjack/domain/card/CardDenomination.kt
> +        if (sum + 11 > 21) ACE.value[BASIC_VALUE_INDEX]
제거하였습니다.

**78273a44**

2021-11-16 17:26 UTC, sangyongchoi commented on src/main/kotlin/blackjack/domain/card/Card.kt
> +    fun getValue(sum: Int): Int = denomination.getValue(sum)
조언 감사합니다 :)

2021-11-16 17:27 UTC, sangyongchoi commented on src/main/kotlin/blackjack/domain/player/Participant.kt
> +abstract class Participant(
아래 두개의 커밋을 통해 진행하였습니다.
ver1 : 8d868e2e
ver2 : c5f43d10

**8d868e2e**
**c5f43d10**

2021-11-16 17:27 UTC, sangyongchoi commented on src/main/kotlin/blackjack/domain/card/CardDenomination.kt
> +    val getValue: (Int) -> Int = { _ -> value[BASIC_VALUE_INDEX] },
value 변수를 제거함으로써 괜찮아졌다고 생각합니다 !

2021-11-16 17:28 UTC, sangyongchoi commented on src/main/kotlin/blackjack/presentation/BlackjackGame.kt
> +        (listOf(dealer) + players).forEach { player ->
Players 를 생성할 때 2개를 생성하도록 변경하였습니다.

다만 이렇게 하다보니 생성할 때 CardDeck 을 넘겨야 하는 트레이드오프가 생겼습니다 ㅠㅠ
혹시 이를 해결할 수 있는 방안이 있을까요 ?

2021-11-16 17:30 UTC, sangyongchoi commented on src/main/kotlin/blackjack/domain/player/Players.kt
> +class Players(
첫째로 Players 는 일급컬렉션을 의도하지 않았으며, 편의상 플레이어들을 한군데서 관리하기 위해 만든 객체입니다.

둘째로 Dealer 도 일종의 Player의 한종류 라고 생각을 했기때문에 Players 라는 네이밍을 사용하였습니다.

코딩을 하다보니 플레이어보다는 참가자라는 네이밍이 어울릴것 같아,
Participants 로 변경하였습니다.

2021-11-16 17:31 UTC, sangyongchoi commented on src/main/kotlin/blackjack/BlackjackApplication.kt
>          while (player.getCardSum() <= 21 && wantMoreCard) {
수정하였습니다.

**c1466de1**

2021-11-16 17:31 UTC, sangyongchoi commented
상속 -> 컴포지션의 방식으로 변경하면서 많은 부분의 변경이 생겼습니다. (거의 새로 짯다싶을 정도입니다..)

피드백 부탁드리겠습니다! 
감사합니다 :)

2021-11-17 07:52 UTC, vsh123 approved these changes
안녕하세요!
피드백 반영잘해주셨네요 💯 

질문 주신부분과 몇가지 코멘트를 남겨놓았으니, 다음스텝에서 함께 반영 부탁드려요!
질문은 언제든지 DM부탁드리겠습니다~~

2021-11-17 07:52 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +) : CardFunction by dealer {
위임 사용 👍

2021-11-17 07:52 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +    val resultStatuses: List<ResultStatus>
해당 프로퍼티는 지울 수 있을 것 같아요!

2021-11-17 07:52 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +        return resultStatuses
`_resultStatuses`로 진행해도 괜찮을 것 같아요!

2021-11-17 07:52 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Participants.kt
> +        allPlayers.forEach { player ->
생성과 카드발급을 하나의 로직으로 묶으신 이유가 있을까요?

2021-11-17 07:52 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/player/Participants.kt
> +    init {
> Players 를 생성할 때 2개를 생성하도록 변경하였습니다.
다만 이렇게 하다보니 생성할 때 CardDeck 을 넘겨야 하는 트레이드오프가 생겼습니다 ㅠㅠ
혹시 이를 해결할 수 있는 방안이 있을까요 ?

이럴 경우 개인적으로 FactoryMethod 패턴을 이용해서 함수명을 의미있게 작성하고 있습니다 :) 
플레이어에게 카드발급을 위해 cardsDeck을 생성자로 넘기는 것보다는

```kotlin
Participants participantWithReceiveCard(val dealer: Dealer, val players: List<Player>, cardsDeck: CardsDeck)
```
(예시입니다.. 이쁘게 바꿔주세요!!) 와 같은 함수를 작성해서 생성을하게 될 것 같아요!

2021-11-17 07:52 UTC, merged