Step3 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #153
Opened 2021-11-21 10:00 UTC by LimHanGyeol

안녕하세요. 블랙잭 3단계 PR입니다.
이전 피드백 주신 내용 반영 했습니다.

selaed class나 확장 함수 등 좀 더 코틀린스럽게 사용해보고 싶지만,
아직 잘 되진 않는거 같아요.. !😥

잘 부탁드립니다 !

2021-11-22 13:09 UTC, ka0oll requested changes
구현 잘해주셨습니다. 👍 

몇가지 코멘트 남깁니다. 고민후에 다시 요청주세요 🙇

2021-11-22 13:09 UTC, ka0oll commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
> +        val playedBlackjack = play(preparedGamers)
딜러 + 게이머들이 두장의 카드를 받는건 도메인 로직 같다는 생각이 들어요.

2021-11-22 13:09 UTC, ka0oll commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
>                  }
이부분이 도메인 로직으로 컨버팅을 시도해보는게 어떨까요.
playable 함수를 도메인에 전달하는 것도 방법일거같아요.!

2021-11-22 13:09 UTC, ka0oll commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
> +            }
이부분도 도메인과 in,out이 혼재 되어있는데요. 도메인 부분을 분리하도록 시도해보시면 좋을거같습니다.

2021-11-22 13:09 UTC, ka0oll commented on src/main/kotlin/blackjack/domain/result/PlayerResult.kt
> +    }
dealer에게 승패 여부를 판단하도록 메세지를 전달하는건 어떨가요. 딜러(객체)가 자신의 카드 정보를 이용해서 승패 여부를 판단하는 책임을 가지는걸 고민해보시면 좋을거같습니다.

2021-11-24 15:08 UTC, LimHanGyeol commented on src/main/kotlin/blackjack/domain/gamer/Gamers.kt
> +class Gamers private constructor(
반영 했습니다!

2021-11-24 15:09 UTC, LimHanGyeol commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
> +        val playedBlackjack = play(preparedGamers)
해당 기능을 Domain Layer 에서 수행하도록 변경 했습니다.

2021-11-24 15:10 UTC, LimHanGyeol commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
>                  }
저는 여기서 분리가 어려울 것이라고 생각했는데,, 좀 더 생각해보니 분리가 되네요 .. !
피드백 반영 하고, 테스트 코드 추가했습니다!🙏🏻

2021-11-24 15:11 UTC, LimHanGyeol commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
> +            }
이 부분 역시 위와같이 분리가 어려울 것이라고 생각했는데,, 피드백 반영 하고, 테스트 코드 추가했습니다!
🙏🏻

2021-11-24 15:16 UTC, LimHanGyeol commented
교육과정 절반이 지나가고, 연말이라 업무가 바쁘다보니 이번 미션에서 조금씩 집중력이 떨어지고 있었습니다.
그래서 좀 얕게 생각하고 개발한 부분이 보이는것 같기도 하고,,
더 깊게 생각해도 잘 되지가 않아 좀 아쉬운감이 있기도 합니다.

그만큼 이정도면 된것 같은데,, 라고 생각했던 부분의 빈틈을 잡아주셔서 더 생각하며 접근해볼 수 있는 계기가 됐던 것 같습니다. 감사합니다 ㅎㅎ

2021-11-25 15:40 UTC, ka0oll approved these changes
리뷰 잘 반영해주셨네요. 👍 
몇가지 코멘트 남겼습니다. 다음번 미션에서 함께 고민해주세요 😄

2021-11-25 15:40 UTC, ka0oll commented on src/main/kotlin/blackjack/domain/gamer/Gamers.kt
>  class Gamers private constructor(
data class가 더 어울릴거같아요.

2021-11-25 15:40 UTC, ka0oll commented on src/main/kotlin/blackjack/domain/gamer/Gamers.kt
>          }
```suggestion
        fun from(dealer, List<Player>): Gamers {
            return Gamers(gamers)
        }
```
팩토리 자체에서도 제약을 줄수 있을거같아요.

2021-11-25 15:40 UTC, ka0oll commented on src/main/kotlin/blackjack/domain/state/result/Lose.kt
> +}
상태와 결과는 다른 개념인거 같아요.

2021-11-25 15:40 UTC, ka0oll commented on src/main/kotlin/blackjack/domain/result/PlayerResult.kt
> +                DealerResultType.WIN -> player.lose()
```suggestion
               dealer.judgeGameResult(player)).oppsite 
```
이런방식 어떨까요.

2021-11-25 15:40 UTC, ka0oll commented on src/main/kotlin/blackjack/presentation/BlackjackController.kt
>          return completedBlackjackPlayers
컨트롤러에서  in/out과 연결되어 있다보니 도메인 로직이 있는거같아요.
callback방식을 적용해보시는건 어떠실까요?

2021-11-25 15:40 UTC, merged