4단계 - 블랙잭(베팅)
next-step/kotlin-blackjack pull request #160
Opened 2021-11-25 10:12 UTC by leesohyun13

안녕하세요~ 블랙잭(배팅) 진행해보았습니다. 수익률 계산하는 부분이 복잡하여 시간이 좀 걸렸습니다. 리뷰 잘 부탁드립니다!

2021-11-26 14:03 UTC, malibinYun requested changes
미션 고생 많으셨습니다!
수정해보면 좋을 점들 피드백 남겼습니다.
수정하시구 다시 리뷰 요청 부탁드릴게요!😊

2021-11-27 04:03 UTC, leesohyun13 commented
안녕하세요! 리뷰 감사드립니다.  리뷰 주신 것 기반으로 수정해보았습니다 ㅎㅎ

2021-11-28 12:18 UTC, malibinYun approved these changes
블랙잭 미션 완주 정말 고생 많으셨습니다 🙂
피드백 반영하시느라 고생 많으셨어요! 미션은 여기서 마무리하겠습니다.
다음 미션도 화이팅입니다!! 😊

2021-11-28 12:18 UTC, malibinYun commented on src/main/kotlin/blackject/model/Player.kt
> +    open fun isDealer(): Boolean = false
이 메서드는 도메인에서 쓰이지 않아서 삭제해도 좋을 것 같아요.

2021-11-28 12:18 UTC, malibinYun commented on src/main/kotlin/blackject/model/Player.kt
> +    }
오버라이드 하지 않을 메서드들은 open으로 꼭 열어둘 필요가 없습니다.
오히려 상속받은 자식클래스가 부모클래스의 로직에 영향을 미칠 수 있는 요소로 작용하기 때문이에요. open으로 열어두기보다, 상속 받는 자식 클래스에서 빈 부분을 채울 수 있게 abstract 또는 interface 구현을 하는 것이 더 좋은 방법입니다 🙂

2021-11-28 12:19 UTC, merged