Step4 - 블랙잭(베팅)
next-step/kotlin-blackjack pull request #161
Opened 2021-11-25 15:16 UTC by Flamme1004K

안녕하세요 리뷰어님😁

지난번에 Step3 에서 리팩토링을 하고 피드백을 다 받은 뒤에 Step4를 진행을 했는데, 확실히 수월했습니다.👍👍👍

요번 기회로 리팩토링을 신경써야하는지에 대해서 회고하는 기회가 되었습니다 ☺️

항상 가르침에 감사합니다 리뷰어님 🙇🏻

요번 미션도 잘부탁드립니다 😁

2021-11-25 15:19 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/card/Denomination.kt
>                  11
ACE에 대한 조건 +11을 붙여주니 호출하는 메소드의 코드가 깔끔해지는 것을 확인할 수 있었습니다.

자그마한 변화가 큰 변화를 줄지 상상도 못했습니다 😌

2021-11-25 15:21 UTC, Flamme1004K commented on README.md
> +- [] 처음 두 장의 카드 합이 21일 경우 블랙잭이 되면 베팅 금액의 1.5 배를 딜러에게 받는다. 딜러와 플레이어가 모두 동시에 블랙잭인 경우 플레이어는 베팅한 금액을 돌려받는다.
`딜러와 플레이어가 모두 동시에 블랙잭인 경우 플레이어는 배팅한 금액을 돌려받는다.`

해당 부분에 대해서는 나중에 플레이어와 딜러에 대해서 수익이 0원이라는 것인가요??

2021-11-25 15:23 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/result/WinDrawLose.kt
> +    }
훌륭하신 리뷰어님. 질문드릴 게 있습니다!

when절 안의 else문을 없애야할까요?? 아니면 그냥 그대로 놔둬도 괜찮을까요? 🤔

추가로 else 문을 없애는 좋은 방법이 있을까요?? 🤔

2021-11-26 10:35 UTC, vsh123 commented on README.md
> +- [] 처음 두 장의 카드 합이 21일 경우 블랙잭이 되면 베팅 금액의 1.5 배를 딜러에게 받는다. 딜러와 플레이어가 모두 동시에 블랙잭인 경우 플레이어는 베팅한 금액을 돌려받는다.
넵 맞습니다!!

2021-11-26 11:26 UTC, vsh123 requested changes
안녕하세요!
확실히 Step3때 많은 개선이 진행되어서 Step4에는 크게 피드백 드릴 부분이 없네요!

질문주신 내용에 대한 코멘트를 남겼으니 확인 부탁드리겠습니다~!

2021-11-26 11:26 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/card/Cards.kt
> +    private fun isAce(sum: Int) = sum > 21 && cards.map { it.denomination }.contains(Denomination.ACE)
21을 상수화해서 관리하면 어떨까요?(사용하는 곳이 많아보여요!)

2021-11-26 11:26 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/card/Denomination.kt
>                  11
ACE에 있는 11이라는 값도 상수화를 하면 더 좋을 것 같아요!

2021-11-26 11:26 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/player/BettingMoney.kt
> +class BettingMoney(private var _money: Int = ZERO) {
`_money`프로퍼티가 생성자로 사용되는 곳이 없어보이는데요! 생성자 프로퍼티에 있어야 할 이유가 있을까요?

2021-11-26 11:26 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/result/BettingResult.kt
> +            if (player.isBlackJackPlayer() && !dealer.isBlackJackPlayer()) {
해당 조건도 WIN조건에 함께 넣으면 어떨까요?

2021-11-26 11:26 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/result/WinDrawLose.kt
> +    }
결국 조건절은 필요하기 때문에 when을 없애기는 쉽지 않아보여요!
다만 이렇게 했을 경우, 판단로직에 순서가 생겨버리기 때문에 순서가 바뀌면 결과가 달라질 수도 있는데요!

예를들어 WIN과 DRAW에 대한 순서를 바꾸는 경우에 `player = 22, dealer =22`가 WIN에서 DRAW로 되는거죠! 
따라서 모든 case에 대하 조건을 쭉 나열해서 보여주는게 더 좋을 것 같아요!

추가적으로
- LOSE도 else가 아닌 하나의 case로 관리되면 좋을 것 같아요!
- `!player.isBustPlayer() && player.getScore() > dealer.getScore()`와 같은 내용은 별도 함수로 빼서 한눈에 내용을 확인할 수 있으면 좋을 것 같아요!

2021-11-26 11:26 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/result/WinDrawLose.kt
> +    }
아래는 이렇게도 짤 수 있을 것 같아 참고용으로 안내드립니다!!(오버엔지니어링일 수도 있어요!)

```kotlin
package blackJack.domain.result

import blackJack.domain.player.Dealer
import blackJack.domain.player.Player

enum class WinDrawLose {
    WIN, DRAW, LOSE;

    companion object {
        private val conditions: List<Condition> = listOf(PlayerWinCondition, PlayerDrawCondition, PlayerLoseCondition)

        fun from(player: Player, dealer: Dealer): WinDrawLose =
            conditions.single { it.isMatch(player, dealer) }.winDrawLose
    }
}

sealed interface Condition {
    val winDrawLose: WinDrawLose
    fun isMatch(player: Player, dealer: Dealer): Boolean
}

object PlayerWinCondition : Condition {
    override val winDrawLose: WinDrawLose = WinDrawLose.WIN

    override fun isMatch(player: Player, dealer: Dealer): Boolean {
        return isOnlyPlayerBlackjack(player, dealer) || dealer.isBustPlayer() || isPlayerGreaterThanDealer(player, dealer)
    }

    private fun isOnlyPlayerBlackjack(player: Player, dealer: Dealer):Boolean =
        player.isBlackJackPlayer() && !dealer.isBlackJackPlayer()

    private fun isPlayerGreaterThanDealer(player: Player, dealer: Dealer): Boolean =
        !player.isBustPlayer() && player.getScore() > dealer.getScore()
}

object PlayerDrawCondition : Condition {
    override val winDrawLose: WinDrawLose = WinDrawLose.DRAW

    override fun isMatch(player: Player, dealer: Dealer): Boolean {
        return allBust(player, dealer) || isEqualScore(player, dealer)
    }

    private fun allBust(player: Player, dealer: Dealer): Boolean = player.isBustPlayer() && dealer.isBustPlayer()

    private fun isEqualScore(player: Player, dealer: Dealer): Boolean = player.getScore() == dealer.getScore()
}

object PlayerLoseCondition : Condition {
    override val winDrawLose: WinDrawLose = WinDrawLose.LOSE

    override fun isMatch(player: Player, dealer: Dealer): Boolean {
        return isOnlyDealerBlackjack(player, dealer) || player.isBustPlayer() || isDealerGreaterThanPlayer(player, dealer)
    }

    private fun isOnlyDealerBlackjack(player: Player, dealer: Dealer):Boolean =
        player.isBlackJackPlayer() && !dealer.isBlackJackPlayer()

    private fun isDealerGreaterThanPlayer(player: Player, dealer: Dealer): Boolean =
        dealer.isBustPlayer() && dealer.getScore() > player.getScore()
}

```

2021-11-27 13:28 UTC, Flamme1004K commented
안녕하세요. 리뷰어님 😁

피드백 받은 부분 리팩토링하여 리뷰 요청 드립니다 ☺️

요번에도 잘 부탁드립니다 🙇🏻

항상 가르침에 대하여 감사합니다 👍👍👍👍

2021-11-27 13:30 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/player/BettingMoney.kt
> +    private var _money: Int = ZERO
피드백을 받고 BettingMoney에 대하여 생성자 프로퍼티에 대하여 선언해주는 곳이 없는 것을 확인하였고,

_money를 필드로 옮겼습니다.😅

2021-11-27 13:31 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/card/Denomination.kt
>      },
ACE 11이라는 값을 상수화에 대한 피드백을 주셨는데,

1과 11 그리고 21에 대하여 상수화가 필요할 것 같아서 위와 같이 수정을 했습니다.

2021-11-27 13:33 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/result/BettingResult.kt
> +                }
BlackJack 플레이어에 대한 조건문을 Win으로 옮겼습니다.

그런데, 여기서 Win 절 안에 if else 문이 추가가 되었는데, 이 부분에 대하여 함수화를 시켜줘야 할까요?

저는 이 부분이 더 명확히 읽혀져서 현재 함수화를 시켜주지 않은 상태입니다.

리뷰어님은 어떻게 생각하시나요? 🤔

2021-11-27 13:36 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/result/WinDrawLose.kt
> +                else -> DRAW
리뷰어님의 피드백을 받고 WIN / DRAW 외에 대하여 LOSE를 하는 것에 대하여 다시 생각을 해보니, 

게임에 대한 결과가 오류가 나면, 항상 플레이어는 돈을 뺏기는구나라는 생각을 하게 되었습니다.

매우 큰일나는 상황이죠 😭

그래서 바로 LOSE에 대하여 명확히 해주고 그 나머지는 모두 DRAW 로직을 타도록 했습니다. ☺️

2021-11-28 11:03 UTC, vsh123 requested changes
안녕하세요!!
피드백 반영 잘해주셨네요!! 💯 

몇가지 추가 코멘트를 남겼으니 확인부탁드리겠습니다!

2021-11-28 11:03 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/card/Denomination.kt
>  enum class Denomination(val value: String, val orderBy: Int) : CardScore {
[high-order-function](https://kotlinlang.org/docs/lambdas.html#invoking-a-function-type-instance)을 이용해 CardScore 인터페이스 없이 동작하도록 바꿔보는건 어떨까요?

2021-11-29 15:52 UTC, Flamme1004K commented
안녕하세요. 리뷰어님 ☺️

피드백 주신 부분 수정하여 리뷰 요청 드립니다 😊

항상 쓰고 싶었던 고차 함수에 대하여 리뷰어님 덕분에 이러한 상황에서도 쓸 수 있구나 라는 것을 느꼇던 피드백이 되었네요 😁

그리고, 비교에 대한 것에 대해 괄호로 묶는 것 그리고 배수에 대하여 함수로 만든다면 본래의 로직을 좀 더 줄일 수 있다는 것을 깨달을 수 있었습니다.

가르침 감사합니다 리뷰어님 🙇🏻🙇🏻

2021-12-03 13:49 UTC, Flamme1004K commented
안녕하세요. 리뷰어님 😁

합계 부분과 결과에 부분을 다시 리팩토링하여 리뷰 요청 드립니다.

잘 부탁드립니다 ! 🙇🏻

2021-12-03 13:50 UTC, Flamme1004K commented on src/main/kotlin/blackJack/domain/card/Cards.kt
> +    }
합계 부분에 대해서 잘 생각을 해보니, 일단 ACE에 대해서 1로 다 더한 뒤에 후에 ACE가 있다면 보너스 점수를 주는 방식도 괜찬을 것 같아서 위와 같이 변경을 했습니다.☺️

2021-12-04 12:43 UTC, vsh123 approved these changes
안녕하세요!!
마지막까지 구현 잘해주셨네요!! :) 💯 

너무 깔끔한 코드가 만들어진 것 같아요!!
블랙잭 미션 구현하느라 정말고생하셨습니다.

마지막 미션도 화이팅하세요!!

2021-12-04 12:43 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/card/Cards.kt
> +    private fun isAce() = cards.map { it.denomination }.contains(Denomination.ACE)
[any](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/any.html)를 활용하면 아래와 같이 만들 수 있겠네여!
```suggestion
    private fun isAce() = cards.any { it.denomination === Denomination.ACE }
```

2021-12-04 12:43 UTC, vsh123 commented on src/main/kotlin/blackJack/domain/card/Cards.kt
> +    private fun sumBonus(total: Int): Int =
(그럴일은 없겠지만....) 만약 MAX_NUMBER가 30이라고 가정하면 현재 구조에서는 정상적으로 동작하지 않을 것같아요!!
예를 들어 ACE,ACE,8인 경우 30이 나와야하지만, 현재 코드는 20이 나올 것 같아요~!!!

이를 해결하기 위해 ACE의 개수만큼 sumBonus함수를 호출하도록 하는 방향으로 변경하는게 더 낫지 않을까 하는 의견입니다!

2021-12-04 12:43 UTC, merged