🚀 3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #162
Opened 2021-11-27 19:25 UTC by nachwon

블랙잭은 규칙을 잘 몰라서 그런지 갈수록 어려운것 같네요;;ㅎㅎ

2021-11-28 07:49 UTC, vagabond95 requested changes
블랙잭 도메인이 처음 접하시면 많이 헷갈리고 어려우실 것 같아요 😢 
그래도 걱정하신 것에 비해 큰 구조 변경 없이 잘 작성해주신 것 같습니다 ㅎㅎ

구현내용에 대하여 간단한 코멘트 몇개 남겼는데요, 확인 부탁드리요!

2021-11-28 07:49 UTC, vagabond95 commented on src/main/kotlin/blackjack/domain/Player.kt
> +    open infix fun wins(player: Player): Boolean {
오 이러한 infix 메소드 좋은 것 같습니다 👍 👍

2021-11-28 07:49 UTC, vagabond95 commented on src/test/kotlin/blackjack/domain/PlayerTest.kt
> +
테스트 코드 잘 짜주셨어요!

다만, 블랙잭은 기본적으로 플레이어와 딜러 간의 대결이기 때문에
player 사이의 비교는 의미가 없을 것 같아요!

예를들어 Player 와 Player 끼리 비교하게 되면 둘다 bust 를 하는 케이스가 생길 수 있는데 사실 player 간의 bust 는 의미가 없습니다!
반면 딜러 / 플레이어 간에는 논리상 둘 중 '하나만'  먼저 버스트가 될 수 있습니다.

2021-11-28 07:49 UTC, vagabond95 commented on src/main/kotlin/blackjack/views/OutputView.kt
> +        blackJack.apply {
dealerWinCount, dealerLoseCount 는 view 외의 영역에서 계산하는 것이 어떨까요?
view 가 상세과정을 알 필요가 없을 것 같아요!

2021-11-28 07:49 UTC, vagabond95 commented on src/test/kotlin/blackjack/domain/PlayerGroupTest.kt
> +        val playerGroup = PlayerGroup(
테스트 코드가 있긴 하지만,
기본적으로 외부에서는 코드 내부를 보지 않는 한 딜러가 자동으로 추가되는지 알기 어려울 것 같은데요!

딜러를 생성자에 또 추가하면 예외를 던지거나, 딜러가 추가되는 것을 나타내는 팩토리 메소드를 제공해보는 것은 어떨까요?

2021-12-04 14:25 UTC, nachwon commented on src/test/kotlin/blackjack/domain/PlayerGroupTest.kt
> +        val playerGroup = PlayerGroup(
d27fe66 딜러가 포함된 경우 에러를 던지도록 수정했습니다!

2021-12-04 14:25 UTC, nachwon commented on src/test/kotlin/blackjack/domain/PlayerTest.kt
> +
03114e9 player vs player 테스트를 player vs dealer 테스트로 수정했습니다

2021-12-04 14:26 UTC, nachwon commented on src/main/kotlin/blackjack/views/OutputView.kt
> +        blackJack.apply {
1522630 로직을 옮겼습니다

2021-12-05 14:15 UTC, vagabond95 approved these changes
피드백 의도에 맞게 잘 수정해주셨네요!

3단계는 머지하도록 하겠습니다 ㅎㅎ

2021-12-05 14:15 UTC, vagabond95 approved these changes
피드백 의도에 맞게 잘 수정해주셨네요!

3단계는 머지하도록 하겠습니다 ㅎㅎ

2021-12-05 14:15 UTC, merged