2단계 - 블랙잭 rlarlvy153
next-step/kotlin-blackjack pull request #224
Opened 2022-06-06 13:11 UTC by rlarlvy153

2022-06-07 15:17 UTC, pci2676 requested changes
블랙잭미션 구현하느라 고생하셨습니다.
개선해볼만한 부분에 리뷰를 남겼으니 참고해주세요!
추가로 kotlin lint를 확인하고 수정해주세요!

2022-06-07 15:17 UTC, pci2676 commented on src/main/kotlin/blackjack/Card.kt
> +        return "${cardNumber.cardName}${cardShape.shapeName}"
보통 `toString()`은 `view`에 직접적으로 사용되지 않고 디버그용으로 많이 사용되는데요.
`view`에 어떻게 노출할지는 `view`의 책임으로 생각하고 변경해보는건 어떨까요?

2022-06-07 15:17 UTC, pci2676 commented on src/main/kotlin/blackjack/Dealer.kt
> +    }
`dealer`(딜러)의 공개 인터페이스는 `popOneCard`로 보이는데요.
그렇다면 딜러의 역할은 카드를 뽑아서 주는것이라고 생각해볼수도 있을것 같아요!
그렇다면 카드 뭉치를 딜러가 굳이 석어줄 필요는 없지않을까요? 카드 뭉치를 딜러가 생성될때 주입받도록 변경하면 `shuffled`로 인해
테스트하기 힘든 영역도 테스트가 가능해질수 있을것 같아요!

2022-06-07 15:17 UTC, pci2676 commented on src/main/kotlin/blackjack/InputView.kt
> +package blackjack
view 와 domain 간 패키지를 분리해보시는건 어떨까요?

2022-06-07 15:17 UTC, pci2676 commented on src/test/kotlin/blackjack/DealerTest.kt
> +    fun `딜러가 중복없는 카드를 내놓는지 테스트`() {
popOneCard를 테스트하는 것이라면 딜러가 가지고 있는 카드중 하나를 꺼내주는것으로 보는게 좋다고 생각합니다.
딜러가 들고 있는 카드 뭉치가 중복이 없는것을 보장하고 싶다면 
카드뭉치를 생성하는 객체가 있는것이 좋을것 같아보이고, 해당 객체를 테스트해주는 것이 좋을것 같습니다!

중복이 없는것을 확인하기 위해 테스트에서 반복문을 수행하는것 같아보이는데 
테스트를 파악하기 힘들게 만드는 요소로 작용할수 있기때문에 반복문은 지양해주는것이 좋습니다!

2022-06-07 15:17 UTC, pci2676 commented on src/test/kotlin/blackjack/ResultCalculatorTest.kt
> +class ResultCalculatorTest {
카드의 합계를 계산하는 케이스가 ACE의 계산방식에 따라 더 존재할것 같습니다.
해당 케이스들도 모두 추가 해주는것이 좋을것 같습니다~!

2022-06-08 08:22 UTC, rlarlvy153 commented on src/main/kotlin/blackjack/Card.kt
> +        return "${cardNumber.cardName}${cardShape.shapeName}"
view에서 도메인 객체를 접근하는걸 지양하고 싶은데, 어떻게 생각하시나요

2022-06-08 08:28 UTC, rlarlvy153 commented on src/test/kotlin/blackjack/ResultCalculatorTest.kt
> +class ResultCalculatorTest {
내부에서 고려 되었습니다.

2022-06-08 14:30 UTC, pci2676 commented on src/main/kotlin/blackjack/Card.kt
> +        return "${cardNumber.cardName}${cardShape.shapeName}"
그렇다면 view에서만 사용할 정보를 담은 view용 객체를 만들어서 사용해보는건 어떨까요?

2022-06-08 15:02 UTC, pci2676 requested changes
안녕하세요~
추가로 리뷰를 남겨두었으니 확인 부탁드리겠습니다~!
이전에 피드백해주신 부분에 코멘트를 달아두었으니 그 부분도 확인 부탁드리겠습니다!

2022-06-08 15:02 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +        offerInitialCards(players)
메세드에 넘긴 파라미터가 해당 메서드 내부에서 값이 변경된다는 것은 추적하기 힘든 코드가 되는 것 같습니다.
파라미터로 넘긴 값과 같은 같은 타입을 리턴하도록 하고 변경된 객체를 반환하도록 변경하는것이 좋을것 같습니다.
이 리뷰는 다른 부분에도 동일하게 적용해주시면 좋을것 같습니다.

2022-06-08 16:18 UTC, rlarlvy153 commented on src/main/kotlin/blackjack/Card.kt
> +        return "${cardNumber.cardName}${cardShape.shapeName}"
그런데 이미 접근하긴했네요? ㅎㅎ..;

2022-06-09 13:27 UTC, pci2676 requested changes
지난번 리뷰중 테스트 코드를 더 작성해 달라고 요청드린 부분이 개선되지 않은것 같습니다.
그리고 리뷰를 추가로 남겨두었으니 확인해주세요.

2022-06-09 14:57 UTC, rlarlvy153 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        if (idx == cards.size) {
lastIndex란게 있는지 몰랐네요~ 감사합니다.

2022-06-11 04:23 UTC, pci2676 approved these changes
2단계 구현하느라 고생하셨습니다!
리뷰를 남겨두었지만 해당 부분은 다음 단계 진행하시면서 적용해주시면 좋을것 같습니다!
이번 단계는 머지하도록 하겠습니다!

2022-06-11 04:23 UTC, pci2676 commented on src/test/kotlin/blackjack/CardsTest.kt
> +    fun `카드의 합계를 모든 경우의수가 결과가 맞는지 테스트`() {
여러개의 케이스를 하나의 테스트에서 확인하고 싶으시다면 `@ParameterizedTest`를 이용하시는것이 좋습니다~!
지금 같이 하나의 테스트에 계속해서 테스트 케이스가 추가된다면 테스트를 파악하기 힘들어질것 같습니다!

2022-06-11 04:23 UTC, pci2676 commented on src/test/kotlin/blackjack/CardDeckTest.kt
> +    fun `카드덱이 만들때마다 랜덤한 순서를 반환하는지 테스트`() {
이 테스트는 만들지 않으셔도 될것 같습니다~!
랜덤한 요소에 의존하는 테스트는 확신할 수 없습니다!

2022-06-11 04:23 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +            UserAnswer.NO -> false
`UserAnswer`의 프로퍼티로 `boolean`을 추가해주는 것이 좋지 않을까요??

2022-06-11 04:23 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +            card.cardNumber.multiNumbers?.forEach {
Card에게 직접 메세지를 던지는 건 어떨까요?

```suggestion
        if (card.isMultiple) {
            card.multiNumbers?.forEach {
```

2022-06-11 04:23 UTC, pci2676 commented on src/test/kotlin/blackjack/PlayerTest.kt
> +        val expected = 14
가장 큰값을 불러오는 메서드이기 때문에 `possibleResults`가 두개 이상인 경우에 대해 테스트를 해야 더 의미가 있을것 같습니다~!

2022-06-11 04:23 UTC, merged

2022-06-11 12:53 UTC, rlarlvy153 commented on src/test/kotlin/blackjack/PlayerTest.kt
> +        val expected = 14
ACE가 포함되어있어서 두개이상인 것 같습니다