3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #231
Opened 2022-06-08 02:54 UTC by shindongyoun

리뷰 요청드립니다~
기존에 Step2 에서 부족했던 부분도 수정 했습니다~ 😁😁

2022-06-09 13:00 UTC, laco-dev requested changes
3단계 미션 고생하셨습니다. 🙏🏻 

지난번 드린 의견과 같이 
"3단계에서는 딜러와 플레이어가 공통으로 가지는 로직을 어떻게 만들 수 있을까?" 라는 방향성을 제시 해드렸습니다.

관련해서 참가자와 딜러라는 개념을 어떻게 구조화 할지 고민 해보세요.
또한 어떠한 메시지를 두고 누가 책임을 가지고 누구에게 협력할지를 결정하는 것이 객체지향 설계의 중요한 포인트 입니다.

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +    }
참가자와 딜러 모두 동일한 개념을 가집니다.
참가자인지 딜러인지 상관 없이 아래의 메시지를 요청하려면 어떻게 할 수 있을까요?
```
1. 참가자는 이름을 가진다
2. 딜러는 이름을 가진다
3. 참가자와 딜러는 카드를 더 뽑을지 여부를 알려줄 책임이 있다.
4. 카드를 뽑는다
```

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        private const val SCORE_TO_REQUEST_A_CARD_FOR_DEALER = 16
이 값은 어플리케이션이 결정할 책임일까요?

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    val dealer = players.first { it.name == DEALER }
이름이 `"딜러"`인 다른 참가자가 있으면 어떨까요?

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = _status.toList()
1. `List<GameResult>`는 Status와 무슨 관계를 가질까요? 의미가 잘 와닿지 않는 변수명 같아요.
2. GameResult의 결과들을 가지고 있을 필요가 있을까요?
딜러의 상태(점수)와 참가자의 상턔(점수)를 비교해서 결과를 반환할 책임만 가지고 있지 않을까요?

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    private val _status: MutableList<GameResult> = mutableListOf()
backing property를 사용하는 경우  `_XXX` 를 먼저 작성합니다.
```kotlin
private val _xxx = Mutable()
val xxx: Immutable = _xxx.toMutable()
```

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Result.kt
> +class Result(private val blackJackGame: BlackJackGame) {
Result의 책임은 무엇일까요?
플레이어와 딜러를 받아 승리, 패배의 개수를 결정하는 걸까요?

현재 구조에서는 Result가 다시 참가자와 딜러의 상태를 변경하도록 만들어 져 있습니다.

Result가 만들어질 때 마다 참가자의 상태가 어디서든 변경될 수 있게 됩니다. 😱 

Result를 만드는 로직은 어디에 위치해야 할지 고민 해보세요.

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Result.kt
> +        return blackJackGame.players
승리인지, 패배인지, 무승부인지는 참가자에게 메시지를 통해 결정하도록 하면 어떨까요?

2022-06-09 13:00 UTC, laco-dev commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        GameResult.values().forEach { enum ->
`enum` 이라는 형을 그대로 사용하는 것은 지양 해주세요.
Enum이 아닌 다른 타입으로 구현이 된다면 이 코드도 변경이 되야 합니다

2022-06-09 15:33 UTC, shindongyoun commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +    }
요구사항에는 없었지만 딜러도 이름을 가질 수 있다는 전제하에 이름을 받도록 수정하고 미입력 시 default = "딜러" 로 설정하도록 수정하겠습니다.

2022-06-09 15:36 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    val dealer = players.first { it.name == DEALER }
참가자를 표현하는 Participant 클래스에 isDealer 프러퍼티를 추가하여 구분하도록 수정하였습니다.

2022-06-09 15:41 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    private val _status: MutableList<GameResult> = mutableListOf()
오 모르고 있던 부분이었는데 꿀팁 감사합니다 👍

2022-06-09 15:45 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Result.kt
> +class Result(private val blackJackGame: BlackJackGame) {
조금 고민을 해봤는데 Result 클래스를 분리하는것보다는 게임을 관리하는 blackJack에서 결과를 계산하는게 맞을것 같다는 생각이 드네요~

2022-06-09 15:54 UTC, shindongyoun commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        GameResult.values().forEach { enum ->
넵 수정했습니다~

2022-06-09 15:57 UTC, shindongyoun commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        private const val SCORE_TO_REQUEST_A_CARD_FOR_DEALER = 16
카드의 영역에서 스코어를 비교하여 isHit 을 내려주도록 수정하였습니다.

2022-06-09 16:05 UTC, shindongyoun commented
3단계를 진행하면서 이렇게 하면 될까 라는 생각이 많이 들기도 했었는데, 리뷰를 받고 나니까 부족했던 부분이나 깊게 고민하지 못했던 부분이 많이 보이네요 ㅎㅎ 꼼꼼한 리뷰 감사합니다. 😁😁
이번에 리뷰 주신 내용을 반영 하면서도 새로 알게되거나 이해를 잘 못한 부분도 있었던것 같습니다! 최대한 이해하려고 노력해서 수정했는데 다시 한번 리뷰 부탁드리겠습니다~~ 🥹🥹

2022-06-11 00:54 UTC, laco-dev requested changes
객체지향을 연습하는 과정에서
클래스 분리라는 것이 가장 어색하면서도 어려운 경험입니다.

쉽게 프로퍼티들로 모든것을 판단하고 사용하는 곳에서 로직을 포함하는 귀차니즘에서 벗어나서
객체들에게 역할을 쥐어주도록 노력 해보는 것이 중요합니다.

나눌 수 있을것 같은데? 생각이 들면 우선 나누고 봅니다!
그렇다고 슈퍼 베이스 클래스가 되는 남용은 피해야 겟죠.... 😓 

역할 분리에서 시작해보는 연습을 위해 다시 한번 개선 요청을 드립니다.

4단계에서는 딜러와 참가자 뿐만 아니라 카드의 상태들도 분리가 되는 목표를 가지기 때문에 3단계에서 충분히 연습 해 보는것이 중요합니다.

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    val isDealer: Boolean = false
`isDealer` 라는 필드를 통해 구분을 하는 것도 가능하지만
조금 더 복잡해지는 경우 `Participant`의 코드는 아래와 같은 형태가 될 수도 있습니다.
```kotlin
class Participant { 
   fun foo() {
      if (dealer) { ... } else { ... }
   }

  fun bar() {
     if (dealer) { ... } else { ... }
  }
}
```

객체지향에서는 역할을 객체에게 부여합니다.
그리고 if, else를 가장 쉽게 없애는 방법은 클래스를 분리하는 것입니다.

참가자와 딜러는 아래의 행동과 상태를 가집니다.
```
1. 이름을 가진다.
2. 카드를 가진다.
3. 카드를 뽑는다.
4. 다른 사람과 점수를 비교할 수 있다.
5. 카드를 더 뽑을 수 있는지 결정한다. (딜러와 참가자가 다름)
```

동일한 개념을 하나의 객체로 정의하고,
참가자와 딜러가 각각 이를 구현하는 형태로 만들어 보면 어떨까요?

참고로 3단계의 미션은 아래 요구사항을 따릅니다.

```
- 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
- 딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.
```

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    fun addGameResult(isWin: List<GameResult>) = this._gameResults.addAll(isWin)
> 이 부분의 의도는 게임을 상상했을 때 참가자의 정보에 게임의 결과가 기록된다는 생각으로 participant에 게임 결과를 가지고 있다고 생각했는데 이 구조는 이상한걸까요?

객체는 재사용성을 항상 고려해서 작성하되 변하지 않도록 만드는 것이 중요합니다.
게임의 결과는 참가자 자율적으로 결정해서 만들어진 결과일까요?
아니면 다른 누군가에게 결정받은 결과일까요?

한 명의 참가자가 여러명의 딜러와 결과를 비교한다.
반대로 말하면 한 명의 딜러는 여러명의 참가자들과 비교한다.

이 문제는 결과에 대한 상태와 역할 분리를 어렵게 생각이 될 수도 있어요.
참가자가 해야할 책임은 무엇일까에 집중 해 보면 좋습니다.

참가자가 다른 참가자와 승부한다 라는 행동으로 만들어 보면 어떨까요?
객체지향에서는 이 개념을 메시지라고 부릅니다.
```
메시지 : 승부한다.
책임 : 참가자
협력관계: 다른 참가자
```

```kotiln
class Participant {
   fun match(otherScore: Int): GameResult {
      // 내가 버스트 상태이면 무조건 패배
      // 상대가 버스트 상태이면 무조건 승리
      // 내 점수가 상대 점수보다 낮으면 패배
      // 그 외 다른 조건이 있을 거에요.
   }
}
```

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    }
.

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        var isHit = blackJackGame.dealerCards.isDealerHit()
딜러카드에 직접 접근하는 것 보다 블랙잭 게임에서 필요한 결과를 받아올 수 있을 것 같아요

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        } while (isHit)
챌린지 일 수 있는데 딜러를 잘 구조화 한다면 위 두 개의 함수 역할을 하나로 만들 수도 있습니다.

참가자와 딜러를 고민 해 보면서 혹은 블랙잭 미션이 끝나기 전까지 한번 생각 해 보시고, 도전 해볼만 하다면 해보세요! 

카드를 추가로 뽑는 조건
```
참가자
- 21점보다 미만 || 카드를 뽑겟다고 선언
딜러
- 16점보다 미만이면 무조건
```

```
블랙잭게임.게임을 시작하자, 결과를 줘
블랙잭게임
   참가자들.뽑아, 뽑은 결과를 줘
       나.뽑을 수 있나? && ???.더 뽑을래?(이게 가장 어려움)
       나.뽑는다
   딜러.뽑아, 뽑은 결과를 줘
       카드상태.뽑을 수 있나?
       나.뽑는다
```

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    private val dealerScore = dealerCards.score()
이 프로퍼티들이 정말로 public 가시성을 가져야 할까요?

2022-06-11 00:54 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    }
"딜러"가 카드를 더 뽑을 수 있는지는 "카드들"에게 물어보는게 맞을까요?

2022-06-11 16:04 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    val isDealer: Boolean = false
참가자와 딜러를 분리 하였습니다

2022-06-11 16:48 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    fun addGameResult(isWin: List<GameResult>) = this._gameResults.addAll(isWin)
의견주신 방향으로 설계 해보겠습니다~

2022-06-11 17:33 UTC, shindongyoun commented
안녕하세요~ 먼저 리뷰 감사합니다~~
리뷰 주신 내용 기반으로 수정을 진행해 보았습니다~ 이번 리뷰 내용은 역할분리가 핵심으로 역할을 분리하고, 클래스를 생성하고 변경하는 작업을 진행하다 보니 커밋의 단위를 분리하기가 조금 어려웠던것 같아요. 기존꺼 변경하면서 컨플릭 생기는 부분 수정하고, 수정하면서 기존에 사용하던걸 지우고, 새로 만들고 반복하다가 보니 커밋 하나에 다 뭉쳐서 올리게 되었네요ㅠㅠ
이번에도 리뷰 잘 부탁드리겠습니다!

2022-06-12 01:13 UTC, laco-dev requested changes
구조 개선에 대해 잘 따라와 주셔서 감사합니다.
아직 플레이어와 게임 결과에 대해 조금 개선 해 보면 좋을 의견이 있어서 남겼습니다.

블랙잭 게임 자체에 대한 이해가 정말 힘들다고 생각합니다... 😭 
다음 요청에는 병합하도록 하겠습니다. 💪🏻

2022-06-12 01:13 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Dealer.kt
> +    }
.

2022-06-12 01:13 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
>      val cardDeck: Deck
이 프로퍼티들은 외부에서 더이상 참조하지 않아요.
private 접근자로 수정할 수 있을 것 같습니다.

테스트 코드를 위해 가시성이 변경되는건 좋지 않습니다.
적절한 다른 방법을 생각해야 합니다

2022-06-12 01:13 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    open val playerCards: Cards = Cards(),
이름과 플레이어 카드가 open으로 만들어지지 않아도 될 것 같습니다.

2022-06-12 01:13 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    }
참가자는 isDealer() 함수가 무조건 false이지 않을까요?
Participant라는 객체가 Dealer라는 클래스를 알 필요가 없다고 생각해요.
```kotlin
// Participant
open fun isDealer(): Boolean = false

// Dealer
override fun isDealer(): Boolean = { ... }
```

2022-06-12 01:13 UTC, laco-dev commented on src/main/kotlin/blackjack/view/InputView.kt
> +        } else dealer
https://github.com/next-step/kotlin-blackjack/pull/218#discussion_r889644497

동일한 의견입니다.

2022-06-12 01:13 UTC, laco-dev commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        val result = StringBuilder()
코틀린의 `buildString { ... }`을 활용할 수 있어요

2022-06-12 01:13 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/GameResultTest.kt
> +class GameResultTest {
.

의견에 따라 게임 결과를 확인하는 테스트가 더 있어야 할 것 같습니다.

2022-06-12 01:21 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    open val playerCards: Cards = Cards(),
혹은 참가자를 open class가 아닌 abstract로 만들고
Player, Dealer라는 클래스 두 개로 나누는 방법도 좋습니다

2022-06-12 08:15 UTC, shindongyoun commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +            InputView.needMoreCard(participant)
아 그렇군요.. 수정해두겠습니다!

2022-06-12 08:23 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
>      val cardDeck: Deck
수정 하였습니다~

2022-06-12 08:27 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    }
수정하였습니다.

2022-06-12 08:29 UTC, shindongyoun commented on src/main/kotlin/blackjack/view/InputView.kt
> +        } else dealer
빠르게 고쳐야하는 습관인데.. 몸이 먼저 반응해서 그런것 같네요~ 주의 하겠습니다

2022-06-12 08:31 UTC, shindongyoun commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        val result = StringBuilder()
꿀팁 감사합니다~

2022-06-12 08:43 UTC, shindongyoun commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        blackJackGame.match()
의견주신 내용을 확인 후 수정하였습니다.

2022-06-12 08:56 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +        }
수정하였습니다~

2022-06-12 08:58 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +            gameResult.setDealerIsWin()
게임 룰을 잘못 이해하고있었네요. 수정하겠습니다~

2022-06-12 09:16 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    open val playerCards: Cards = Cards(),
이 부분은 open 으로 지정하지 않으면 불가능하다고 해서 우선 open으로 두었습니다.

2022-06-12 09:18 UTC, shindongyoun commented
이번 리뷰도 감사합니다~ 제가 블랙잭의 도메인 지식을 충분히 알지 못하고 키보드에 손을 먼저 올린것 같다는 생각이 드네요...
그래도 리뷰어님 덕분에 방향을 잘 잡아가고 있다는 생각이 드네요~ 
이번 리뷰도 잘 부탁드리겠습니다!

2022-06-13 01:52 UTC, laco-dev approved these changes
지금까지 피드백 반영 해주시느라 고생 많으셨습니다. 🙏🏻 
4단계 미션을 진행하면서 구조적으로 같이 고민 해 볼만한 내용을 같이 남겼습니다.

3단계에서는 딜러와 참가자에 대한 로직에 집중 했다면,
다음 미션은 카드들의 상태들에 대해 각각 다른 로직들을 처리하는 방법을 고민합니다.
if, else 코드를 최대한 없애려면 어떻게 해야 할까? 를 생각 해보세요

2022-06-13 01:52 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +            else -> gameResult.decideWinner(participant)
Match 로직도 모두 GameResult로 옮길 수 있을 것 같네요!

2022-06-13 01:52 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +) {
다음 미션을 진행하면서 게임 결과에 보다 많은 정보가 필요하게 되는데요.
마찬가지로 플레이어에게 해당 상태를 추가하면 더욱 재사용이 어려운 형태가 될 것 같아요.
제가 생각한 GameResult는 아래 역할을 가지지 않을까 합니다.

```kotlin
class GameResultMatcher(...) {

   fun match(): GameResult(어떤 참가자가, 어떤 승부 여부를 가지고 있는지)
}
```

게임 결과에는 정말 결과에 대한 정보만 판단하고, 딜러나 참가자의 상태는 변경하지 않아야 한다고 생각합니다

이 내용은 의견이 저랑 다를 수 있어서,
4단계 미션을 진행하면서 한번 고민 해보세요.

2022-06-13 01:52 UTC, laco-dev commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        if (participant is Dealer) {
isDealer() 를 활용할 수 있겠네요!

2022-06-13 01:53 UTC, merged