2단계 - 블랙잭
next-step/kotlin-blackjack pull request #245
Opened 2022-06-11 13:12 UTC by aeomhs

2022-06-13 10:24 UTC, vsh123 requested changes
안녕하세요!!
블랙잭 미션 구현 잘해주셨네요!! 👍 
특히 테스트를 세세하게 작성해주셔서 읽기 좋았습니다~~

몇가지 고민할점을 남겼으니 확인부탁드려요~!!

2022-06-13 10:24 UTC, vsh123 commented on src/test/kotlin/camp/nextstep/blackjack/card/CardTest.kt
> +        val (suit, cardNumber) = spadeAce
Destructuring declarations﻿ 사용 👍

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/Card.kt
> +        }
String을 key로 가져가도 괜찮겠지만, suit와 number를 가지는 별도의 key class를 만들어보면 어떨까요?

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/Card.kt
> +        private fun CardSuit.with(number: CardNumber) = Card(this, number)
확장함수 👍 
다만, 해당 함수의 위치가 이곳에 위치해도 괜찮은지는 고민해보면 좋을 것 같아요!

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/Card.kt
> +            return requireNotNull(CARDS[key(suit, number)]) { "잘못된 카드 모양과 숫자입니다." }
에러에 대한 테스트가 없는 것 같아요! 테스트를 추가해보면 어떨까요~?

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/Card.kt
> +        fun ofCombinations(): Set<Card> {
`ofCombinations`은 어떤 의미에서 네이밍을 하신건지 알 수 있을까요~?

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/CardDeck.kt
> +class CardDeck private constructor(private val _cards: MutableList<Card>) {
private 생성자 활용 👍

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/CardDeck.kt
> +    val cards get() = _cards.toList()
[문서와 같이](https://kotlinlang.org/docs/properties.html#getters-and-setters) getter는 라인을 나눠서 작성해보면 어떨까요?

```suggestion
    val cards
        get() = _cards.toList()

```

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/CardDeck.kt
> +        }
new와 of는 어떤 차이가 있나요??

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +        val playerNames = requireNotNull(readLine()).split(',').map { it.trim() }
`readln()`을 사용해보면 어떨까요?

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +            check(playerName.isNotBlank()) { "올바른 플레이어 이름을 입력해주세요. ($playerName)" }
해당 validation은 Player에 위치하는게 어떨까요?

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +            players.add(Player(playerName))
view(ui)에서 도메인 객체에 대한 생성의 책임까지 맡는게 괜찮을까요?

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/Application.kt
> +    }
한명씩 participate할 이유가 있을까요?

2022-06-13 10:24 UTC, vsh123 commented on src/test/kotlin/camp/nextstep/blackjack/game/BlackJackGameTest.kt
> +        assertThat(players.size).isEqualTo(2)
hasSize를 활용해보는건 어떨까요?!

2022-06-13 10:24 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +    }
BlackJackGame의 생성시점을 참가자를 입력받은 순간으로 변경해보면 어떨까요?

이로인해
- lateinit()제거
- isInitialized 프로퍼티 제거
등을 노려볼 수 있을 것 같아요!

2022-06-14 13:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/card/Card.kt
> +            return requireNotNull(CARDS[key(suit, number)]) { "잘못된 카드 모양과 숫자입니다." }
이 경우 모든 입력값(CardSuit, CardNumber) 조합에 대해서 오류가 발생할 수 없는 부분인데요,
어떻게 테스트할 수 있을지 고민입니다 🤔
에러 메시지가 없는 것이 더 나을까요?

2022-06-14 13:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/card/CardDeck.kt
> +    val cards get() = _cards.toList()
공유해주신 문서 아래에 
```
val area get() = this.width * this.height
```

타입 추론이 가능한 경우 한 라인에 작성하는 케이스도 있는 것 같은데요,
따로 정해진 컨벤션이 있는걸까요?

2022-06-14 13:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/card/CardDeck.kt
> +        }
new 는 타입에 대한 기본(Default) 상태의 인스턴스를 생성하고,
of 는 내부 상태에 대하여 사용자(Caller)가 직접 매개변수로 전달하는 케이스로 나누었습니다!

2022-06-14 13:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +        val playerNames = requireNotNull(readLine()).split(',').map { it.trim() }
오!! 이런게 있었군요 👍

2022-06-14 13:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/Application.kt
> +    }
실제 게임이라면, 사용자 참여는 한 번에 이루어지기보다 비동기적으로 이루어지는 것이 맞을 것 같았고,
여러 명이 동시에 참여하는 participate(players...) 메서드는 따로 두지 않았는데요,
너무 먼 미래를 생각한 것 같네요 🥲
아래에서 말씀주신 Game 을 생성할때에 참가자 Player 리스트를 받도록 수정해보았습니다!

2022-06-14 13:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +            players.add(Player(playerName))
현재 구조에서는 BlackJackGame 밖에서 생성되어 주입되어야 할 것 같은데요,
자연스럽게 PlayerReader 에서 Player 를 만들어주게 되었습니다.
아니면,, 정적 팩터리 메서드를 사용하는 것을 말씀해주신걸까요?

2022-06-15 14:19 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +            players.add(Player(playerName))
하나의 도메인은 여러 ui에 대응할 수 있어야한다고 생각합니다!
또한 ui와 도메인은 **특정 객체**가 아닌 정해진 프로퍼티들만 있으면 정상적으로 동작해야한다고 생각하구요!
이렇게 때문에  DTO라는 개념이 나온게 아닌가 싶어요~~!

그리고 ui와 도메인은 서로다른 영역이라고 생각합니다 (간단히 클라이언트와 서버라고 나눠볼게요!)
그렇게 됐을 경우 클라이언트에서 Player를 생성하고 card를 받는 receive를 할 수 있게끔 권한을 열어주는게 맞나 생각해보면 좋을 것 같아요!!

>정적 팩터리 메서드를 사용하는 것을 말씀해주신걸까요? 

위와 같은 문제를 해결하기 위해 정적 팩터리 메서드는 하나의 방법일 것 같구요! controller에서 생성을 해주는 등 방법을 고민해보면 좋을 것 같아요 :)

2022-06-15 14:22 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/card/CardDeck.kt
> +    val cards get() = _cards.toList()
코틀린의 컨벤션은 공식문서가 제일 정확하다고 생각해요!! :) 
타입추론이 가능할 경우 하나의 라인에 작성이 가능하다는 부분을 저도 이번에 처음알았네요..!! (감사합니다 ❤️)

저의 경우 전체 코드의 일관성을 유지시키기 위해 타입추론이 가능하더라도 타입을 명시하고, 라인을 나눠서 작성을하는데요!
현식님 지금처럼 작성하고 싶다고 하시면 그대로 작성해주셔도 무방할 것 같아요!

2022-06-15 15:00 UTC, vsh123 requested changes
안녕하세요!
피드백 반영잘해주셨네요!! 💯 

몇가지 추가 포인트와 함께 질문주신 내용에 대한 코멘트를 달았으니 확인부탁드리겠습니다~~!!

2022-06-18 07:57 UTC, aeomhs reviewed
소중한 피드백 감사합니다 🙇‍♂️
몇 가지 질문이 있어서 남겨두었습니다! 🙋‍♂️

2022-06-18 07:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +            players.add(Player(playerName))
DTO 를 생각하신거군요!
저는 서비스 애플리케이션이 외부로 불필요한 정보를 숨기고, 더 효과적으로 정보를 노출하기위한 용도로 DTO 를 사용하는 것이라고 이해하고 있었는데요,
(오래된 글이긴하지만,, https://martinfowler.com/eaaCatalog/dataTransferObject.html 요런 느낌으로 이해하고 있었습니다)
DTO 를 만들어 사용할까 하다가 하나의 `name` 프로퍼티만 포함하는 Player 를 다시 Wrapping 하는 DTO 가 필요할까 싶어 추가하진 않았었습니다! 🤔
(이전에도 모든 도메인 객체에 대한 DTO 를 만드는 것에대해 고민해보다가 [링크](https://www.baeldung.com/java-dto-pattern#common-mistakes)에 나와있는 것과 비슷한 이유로 하지 않았기도 합니다)

저도 ui 와 도메인은 다른 영역이라고 생각합니다!
UI 는 애플리케이션이 비즈니스 로직을 수행하기 위한 입력값(Input)을 받거나 결과를 출력(Output)하는 역할을 맡고
도메인은 입력값을 바탕으로 비즈니스 로직을 수행하는 영역이라고 생각합니다

하지만 결국 하나의 애플리케이션으로 실행되어 서비스를 제공하게되는데요,
그 내부를 클라이언트(ui)와 서버(domain) 모델로 나누는 것을 잘 이해하지 못했습니다! 🙋‍♂️
그리고 권한을 열어준다는 것이 정확히 어떤 의미인지 잘 이해하지 못한 것 같습니다,,

음.. 같은 이야기일지 모르겠지만 저는 의존 관계, 의존 방향이 핵심이라고 생각했는데요
ui → domain 에 대한 의존 방향을 유지하는 것이 중요하다고 생각했습니다!
컨트롤러를 포함한 ui 에서 domain 에 접근하는 것은 자연스러운거라고 생각했는데요, 
이에 대한 반의 의견이 궁금합니다!

또한 domain 안에서 여러 객체의 의존 방향도 중요하다고 생각합니다.
```mermaid
  graph TD;
      game-->card;
      game-->player;
      player-->card;
```

이러한 형태로 의존성을 가지고 있는데요,
Game 을 시작하면서 플레이어를 생성하는 것이 아니라
이미 존재하는 플레이어가 참여하는 형태로 생각했습니다.
그래서 player 에 대한 생성을 game 이 직접 하는 것이 아니라, 외부에서 주입하고 있습니다.
인스턴스는 PlayerReader에서 이름을 받자마자 생성하곤 있지만,, 실제 Player 정체성은 그 외부에서 주입되는 것이라고 생각합니다. 
이후 실제 플레이어 서비스를 추가하여 player id 를 부여하면 조금 더 명확해질 것 같습니다 🤔

2022-06-18 07:57 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/GameWriter.kt
> +    fun write(game: BlackJackGame) {
GameWriter 라는 이름이 굉장히 추상적이고.. 범위가 커 보여서 GameInitializedInfoWriter 으로 이름을 수정했고,
이에 맞게 참여자 목록만 받아오도록 수정했습니다!

2022-06-19 15:46 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +            serve(turn.player, _cardDeck.draw())
저는 private함수는 해당 객체의 역할(action)이라고 보지는 않아요!! 
또한 개인적으로 `주어.행위()`로 이어지는 것이 조금 더 가독성이 좋다고 느껴집니다!

만약 외부에서  `BlackjackGame.serve(player, draw())`와 같이 호출했다면, 괜찮겠지만 지금 상황에서는 굳이(?) 라는 생각이 들어서 질문드렸어요!

해당 부분은 개인의 차가 존재할 수 밖에 없다고 생각하기 때문에 현식님의 생각을 듣고 싶었습니다!! :)

2022-06-19 15:52 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/Score.kt
> +    val isNotBust: Boolean = !isBust
[요 글](https://stackoverflow.com/a/46376746)을 참고해보시면 좋을 것 같아요!
해당 부분에 대해서는 저도 조금 더 확실하게 이해하고 다시한번 DM드리도록 하겠습니다!! :)

2022-06-19 16:06 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/PlayersReader.kt
> +            players.add(Player(playerName))
오호오호 좋은 글과 의견, 그림 감사합니다!! 👍 

우선 요것두 참고할만한 [링크](https://stackoverflow.com/a/821300)를 전달드리도록 하겠습니다!

> 음.. 같은 이야기일지 모르겠지만 저는 의존 관계, 의존 방향이 핵심이라고 생각했는데요
ui → domain 에 대한 의존 방향을 유지하는 것이 중요하다고 생각했습니다!
컨트롤러를 포함한 ui 에서 domain 에 접근하는 것은 자연스러운거라고 생각했는데요,
이에 대한 반의 의견이 궁금합니다!

네에 저두 이부분은 동의합니다!! 그리구 해당 방법을 유지하면서 우리가 많이 사용하고 있는 게 [레이어드 아키텍쳐](https://medium.com/riiid-teamblog-kr/gradle%EA%B3%BC-%ED%95%A8%EA%BB%98%ED%95%98%EB%8A%94-backend-layered-architecture-97117b344ba8)라구 생각해요~!!

위 글에서 핵심적으로 봐야하는 부분은 **ui(프레젠테이션 레이어)와 도메인(어플리케이션 레이어)에대한 분리**인데요!
지금 현재 코드에서는 의존에 대한 방향성은 올바르지만, 어플리케이션 레이어에서 수행해줘야하는 작업( Player라는 도메인 모델을 생성)이 프레젠테이션 레이어에 존재하고 있다고 생각합니다!


요 부분은 다음 스텝에서 함께 고민해보시구, 추가 의견을 주시면 좋을 것 같아요!  궁금한점이나 이해가 안가는 부분은 언제든 DM을 주시면 더더 빠르게 답변드리겠습니당~

2022-06-19 16:07 UTC, vsh123 approved these changes
현식님 안녕하세요!
피드백 반영 너무 잘해주셨네요! 💯 

남겨주신 질문에 대한 답변을 작성하는데, 저 또한 많은 공부를 할 수 있어서 너무 좋았습니다~~~~~~
다음 스텝을 위해 이번 스텝은 머지하도록 할게요!

혹시 진행중에 궁금한점이 있다면 언제든 DM주세요! :)

2022-06-19 16:07 UTC, merged