4단계 - 블랙잭(베팅)
next-step/kotlin-blackjack pull request #255
Opened 2022-06-13 09:38 UTC by shindongyoun

벌써 이번 미션의 마지막 PR 이네요~ 이번 미션을 진행하면서 코틀린에 대해서 더 많이 배우고 기존에 모르고 그냥 사용하던것이 잘못되었다는걸 알 수 있었던 계기가 된것 같습니다. 
4단계의 경우 배팅에 대한 이해가 어려워 딜러는 0원의 배팅으로 시작하는 방향으로 시작했습니다. 
마지막 4단계 리뷰 요청드립니다~ 마지막까지 잘 부탁드립니다!!🥹🥹🥹

2022-06-14 14:19 UTC, laco-dev requested changes
4단계 미션 고생하셨습니다.
오늘 강의 잘 들어보셨나요?

강의에서 말하는 객체지향의 목표에 맞게 협력, 책임, 추상화 등등 모든 것을 정리 해보는 블랙잭 미션 4단계 입니다.

다소 난이도가 높은 과제를 피드백으로 드려 보았습니다.
많이 어렵게 느껴지실 수 도 있지만 이 경험을 통해 보다 객체지향 프로그래밍에 대해 성장하는 기회가 될 것이라고 믿고 있습니다.

급하게 구현에 집중하실 필요는 없습니다.
천천히 고민하고 도전 해보세요. 🙏🏻

2022-06-14 14:19 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    }
새로운 요구사항을 받으면서 GameResult가 더욱 복잡해 졌습니다.
위의 모든 로직은 각각의 "카드 상태"가 구현하도록 만들고,

참가자에게 메시지를 보내 필요한 결과를 알 수 있도록 하는 방향으로 만들어 져야 합니다.

```kotlin
// Outer
participant.earnAmount(배팅 금액, 비교할 상태)

// Participant
state.earnAmount(배팅 금액, 비교할 상태)

// State
fun earnAmount(배팅 금액, 비교할 상태): 수익
   1. 버스트 상태이면 배팅 금액을 모두 잃음
   > 단, 카드를 추가로 뽑아 21을 초과할 경우 베팅 금액을 모두 잃게 된다.
   3. 스테이 상태이면 비교할 상태에 따라 이기거나 지거나 무승부 일 수 있음
   > 딜러가 21을 초과하면 그 시점까지 남아 있던 플레이어들은 가지고 있는 패에 상관 없이 승리해 베팅 금액을 받는다.
   4. 블랙잭 상태이면 비교할 상태에 따라 1.5배거나 1배일 수 있음
   > 딜러와 플레이어가 모두 동시에 블랙잭인 경우 플레이어는 베팅한 금액을 돌려받는다.
```

2022-06-14 14:52 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +
이 내용이 최고의 정답은 절대 아닙니다.
정리하면 "플레이어가 가지는 책임을 다른 객체와 협력을 하자" 입니다.

다른 구현 방법도 충분히 고려 해보셔도 됩니다!

2022-06-14 15:04 UTC, shindongyoun commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        return if (participant.playerCards.isBust()) {
넵~ 제가 이해를 잘못한거 같네요~ 수정 해두겠습니다!

2022-06-14 16:01 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        return this.playerCards.score() < SCORE_TO_REQUEST_A_CARD_FOR_DEALER
카드도 추상화 클래스로 수정하였습니다.

2022-06-14 16:01 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +
수정하였는데 이 방향이 맞을까요..? 확인 부탁드릴게요~~

2022-06-14 17:46 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    }
참가자의 상태에 따른 결과 조회 로 변경하였습니다~

2022-06-16 14:12 UTC, laco-dev requested changes
어려운 도전을 드렸는데 많이 고민 해 주신 흔적이 보입니다.

아직은 함수와 클래스가 책임이 집중되면서 조금 코드 복잡도가 많은 상태인데요.
관련해서 몇가지 피드백을 남겨 보았습니다.

2022-06-16 14:12 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +            playerStatus == BlackJackStatus.BLACK_JACK && dealerStatus == BlackJackStatus.BLACK_JACK -> {
PlayerStatus에게 배당금 계산을 요청 해보면 어떨까요?

```kotlin
playerStatus.getEarningAmount(amount: Int, otherStatus: BlackjackStatus): Float { ... }
```

딜러는 수익금을 직접 계산하기 보다는, 모든 플레이어들의 수익금을 뒤집으면 될 것 같아요!

2022-06-16 14:12 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +            }
score() 함수가 조건에 따라 최대 4번이 호출될 수 있는데요.
한번만 계산하도록 개선 해볼까요?

2022-06-16 14:12 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    abstract fun getEarnAmount(participants: List<Participant>, dealer: Dealer): Int
수익금은 여러 참가자들과 딜러와 상관없이, 자기 자신의 카드 상태와 배팅액, 그리고 상대의 상태 카드상태로 결정되지 않을까요?

2022-06-16 14:12 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/PlayerCards.kt
> +    }
카드에 16과 21이라는 딜러의 의존성이 들어가면서 다소 조금 더 복잡하게 느껴지셨을 것 같습니다.

카드에게서 딜러의 의존성을 없애고 Dealer 혹은 Player가 카드를 더 뽑을 수 있는지로 분리 해봐도 좋습니다.

```kotlin

abstract class Participant  {
   abstract fun canDraw(): Boolean = // 딜러와 참가자가 다른 조건을 가짐

   fun isHit() = cards.isHit() // 순수하게 카드뭉치가 Hit인지만 확인. (딜러인지 관심 없어짐)
}

```

2022-06-17 05:22 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    abstract val battingAmount: Int
Player만 가지도록 수정했습니다~

2022-06-17 06:42 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    abstract fun getEarnAmount(participants: List<Participant>, dealer: Dealer): Int
2명의 플레이어와 1명의 딜러가 있을 때 비교해야하는게 딜러 vs 플레이어1, 딜러 vs 플레이어2 로 비교해서 딜러는 총 합산의 금액을 가져가는 구조가 아닐까요..? 케이스를 봤을 때 딜러가 돈을 잃지 않고 플레이어가 돈을 가져가는 경우도 있고, 플레이어가 1.5배 , 딜러가 0.5배 가져가는 케이스가 있어서 위에 주신 의견과 비슷하게 뒤집는 구조는 조금 어렵다고 생각을 했습니다...

2022-06-17 06:45 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/PlayerCards.kt
> +    }
이 부분 관련해서는 딜러와, 플레이어의 검증하는 값이 달라서 조금 헷갈리는게 있었는데 
isHit 에 대한 가장 풀기 어려운 문제는 플레이어의 경우 InputView 의 의존하여 플레이어에게 카드를 뽑을것인가에 대한 응답이 필요하다는 부분이었습니다. 
카드의 isHit 은 단순 카드의 상태이지만 플레이어가 카드를 뽑지 않길 원하면 Stay가 되기 때문에 이 부분을 풀어나가기가 어렵더라구요.. 혹시 제가 잘못 생각하는 부분이나 이해의 포인트가 잘못된 부분이 있다면 다시 한번 수정 해보겠습니다~

2022-06-17 06:48 UTC, shindongyoun commented
안녕하세요~ 리뷰어님. 바쁘신 와중에 리뷰 감사합니다. 
이번에 리뷰 주신 내용도 수정을 하였지만 두 가지의 수정사항을 반영하지 못했습니다. 
우선 반영하지 못한 이유는 수정이 필요한 부분에 대해 풀어나가는 로직의 이해가 부족한 것일 수 있고, 도메인의 지식이 부족한 이유일 수 있을것 같습니다. 

관련해서는 수정 요청주신 부분에 코멘트를 남겨두었습니다. 확인 부탁드릴게요.. 😁😁

2022-06-17 13:01 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    abstract fun getEarnAmount(participants: List<Participant>, dealer: Dealer): Int
답을 잘 말씀 해 주신것 같아요?
딜러는 플레이어가 받은 만큼 마이너스로 손해를 보는 구조라 
플레이어들이 벌은 금액 = 딜러가 잃은 금액이 됩니다.
반대로 플레이어가 잃은 금액 = 딜러가 벌은 금액이 됩니다.

아래는 참고만 해주세요~
```kotlin
Player1, Player2, Dealer
val player1 = Player1.getEarnAmount(status: BlackjackStatus, score: Score): EarnAmount {
    return 나의 상태와 파라미터로 받은 상태, 점수를 비교해 수익금을 계산한다.
}
val player2 = Player2.getEarnAmount(...) 

딜러의 수익 = -(player1 수익 + player2의 수익)
```

2022-06-17 13:07 UTC, laco-dev requested changes
피드백 확인했습니다. 🙏🏻 

질문주신 내용에 대한 답변을 같이 남겼습니다!
BlackjackGameResult의 책임만 조금 더 풀어서 개선해보면 될 것 같습니다.

마지막까지 화이팅입니다. 💪🏻

2022-06-17 17:06 UTC, shindongyoun commented on src/main/kotlin/blackjack/domain/PlayerCards.kt
> +    }
협력관계의 권한을 위임한다는 view의 역할을 대신할 수 있다는 의미라 생각하고 수정 해보았습니다~

2022-06-18 02:35 UTC, laco-dev requested changes
구조가 변경되면서 다시 UI에 의존성이 생겨버렸어요!
이 부분만 추가로 수정하면 될 것 같습니다! 🙏🏻

2022-06-18 02:35 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Player.kt
> +    private val canDrawable: Drawable = PlayerDrawable(this)
Player가 가지는 drawable이 UI에 의존되지 않도록 만들어주세요!

2022-06-18 14:41 UTC, shindongyoun commented
리뷰어님~ 의견주신 내용 기반으로 고민을 해보고 다시 수정해보았습니다~ 
다시 한번 리뷰 부탁드릴게요! 즐거운 주말 보내세요~~

2022-06-19 02:55 UTC, laco-dev approved these changes
좋습니다. 👍🏻 

지금까지 잘 따라와 주셔서 감사합니다.
스스로 구현해본 결과와 다른 사람들 코드도 한번씩 봐 보면서 고민해보시면 도움 많이 되실 것 같습니다.

마지막 남은 지뢰찾기 미션도 화이팅입니다. 🙏🏻 
그동안 고생하셨습니다.

2022-06-19 02:55 UTC, merged