Step2: 블랙잭
next-step/kotlin-blackjack pull request #275
Opened 2022-06-19 10:51 UTC by hbm0411

일정이 늦어져 죄송합니다 ㅠㅠ

2022-06-19 10:52 UTC, hbm0411 commented on src/test/kotlin/blackjack/domain/CardDeckTest.kt
> +@TestInstance(TestInstance.Lifecycle.PER_METHOD)
object를 method 마다 재생성할 수 있는 방법이 있을까요?

2022-06-19 18:20 UTC, hbm0411 commented on src/test/kotlin/blackjack/domain/CardDeckTest.kt
> +@TestInstance(TestInstance.Lifecycle.PER_METHOD)
DM 코멘트로 주신 의견에 따라 class로 변경하였습니다.

2022-06-19 18:20 UTC, hbm0411 commented on src/main/kotlin/blackjack/domain/PlayGame.kt
> +    fun hitOrStand(player: Player) {
이 함수가 그냥 Application에 있다가 여기로 옮겨오게 되었는데 맞는것인지 헷갈립니다.
또한 여기 있다면 테스트할때 System.in 부분을 건드려야 할 것같은데 테스트가 잘 안되고 있습니다.
도움 부탁드립니다(__)

2022-06-21 12:50 UTC, pci2676 requested changes
안녕하세요~
질문하신 부분에 대한 답변을 남겨두었습니다.
리뷰 확인해주세요~!

2022-06-28 09:39 UTC, hbm0411 commented on src/main/kotlin/blackjack/view/InputView.kt
> +        } while (!ContinueGame.values().any { it.input == result })
none을 처음 사용해보게 되었어요!
훨씬 보기 좋네요. 감사합니다(__)

2022-06-28 09:40 UTC, hbm0411 commented on src/main/kotlin/blackjack/view/InputView.kt
> +        require(result.size in 2..24) { "게임 인원은 2명 ~ 24명만 가능합니다." }
음.. exception 메시지 내용에 "게임 인원은 2명 ~ 24명만 가능합니다." 가 출력되게 해두었는데,
어떤 방식을 말씀하시는걸까요?

2022-06-28 09:45 UTC, hbm0411 commented on src/main/kotlin/blackjack/domain/PlayGame.kt
> +        }
else 대신 runcatching을 사용했는데, 이게 좋은 방법인지 잘 모르곘네요;;
코멘트 부탁드립니다(__)

2022-06-29 00:54 UTC, pci2676 commented on src/main/kotlin/blackjack/view/InputView.kt
> +        require(result.size in 2..24) { "게임 인원은 2명 ~ 24명만 가능합니다." }
아하 메세지에 `result.size`가 같이 추가되면 좋겠다는 의견이었습니다~!

2022-06-29 00:57 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/PlayGame.kt
> +        }
엇.. 어느 부분은 개선하신건지 파악이 안되는것 같은데 코드 반영이 된걸까요?

2022-06-29 09:42 UTC, hbm0411 commented on src/main/kotlin/blackjack/domain/Player.kt
> +                .sumOf { it.number.value }
card class에
```
data class Card(
    val symbol: Symbol,
    val number: CardNumber
) {
    fun getNumberValue() = number.value
}
```

이런 함수를 넣고, 
```
 .sumOf { it.getNumberValue() }
```
이런식으로 호출하는것을 말씀하시는 걸까요?

2022-06-29 16:51 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/Player.kt
> +        if (_cards.any { it.number.anotherValue != null }) {
`ACE`를 산정하여 만든 조건문이니 `card.isAce`라는 메세지를 던질수 있다면 의미가 더 명확하지 않을까 싶습니다~!

2022-06-29 16:53 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/Player.kt
> +                .sumOf { it.number.value }
네 맞습니다~!
다만 상태를 알려주는 것이니 코틀린스럽게 작성한다면 val을 이용하여 표현할 수 있을것 같습니다~
```
data class Card(
    val symbol: Symbol,
    val number: CardNumber,
) {
    val numberValue: Int = number.value
}
```

2022-06-29 16:57 UTC, pci2676 commented on src/main/kotlin/blackjack/domain/PlayGame.kt
> +        }
코드반영된 부분 확인했습니다~!
제가 처음 의도한 코드는 아래와 같긴했습니다~
별건 아니고 else 블럭이 없어도 동일하게 동작할것 같아서 말씀드린거였습니다~
지금같이 하셔도 문제가 되지는 않지만 catch 하는 작업은 비용이 꽤 큰편이라서 catch해서 특정한 동작을 수행하는것이 아니라면 추천하지는 않습니다~
지금의 경우에는 onFailure에서 전달받은 Throwable을 사용하지 않기때문에 아래와 같이만 하셔도 충분할것 같다는 것이 제 의견입니다~

```
        if (cardDeck.isLeft()) {
            player.receiveCard(cardDeck.getOne())
        }
        throw IllegalStateException("카드가 존재하지 않습니다.")
```

2022-06-30 10:59 UTC, pci2676 approved these changes
2단계 구현하느라 고생하셨습니다.
추가로 리뷰를 남겨두었는데요. 다음단계를 진행하시면서 같이 반영해보시면 좋을것 같습니다.
이만 머지하도록 하겠습니다!
수고하셨습니다.

2022-06-30 11:00 UTC, merged