3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #291
Opened 2022-06-26 13:26 UTC by aeomhs

안녕하세요 🙇‍♂️

평일에는 과제를 진행하기에 조금 어려움이 생겨서 제출이 많이 늦어지고 있습니다 😭
주말에 열심히 구현해보았는데,, 생각보다 시간이 더 걸렸네요 ㅠㅠ
변경사항이 너무 많은 것 같기도해서, 혹시 궁금하신 내용은 편하게 말씀 부탁드립니다!

그리고 이번 과제 구현하면서 스스로도 아쉬운 부분이 많이 있었던 것 같은데요,,
계속 고쳐보다가는 과제 제출이 더 늦어질 것 같아서 우선 기능 구현하여 제출합니다!!! 
소중한 피드백 미리 감사드립니다 🙏

---
몇 가지 큰 수정 사항만 적어둡니다..

**카드 패(Hand) 추가**
- 이전에는 Player 가 직접 카드 리스트를 들고 있었는데요, 딜러의 등장으로 카드 리스트 역할을 할 객체가 필요했습니다. 이에 플레이어와 딜러는 모두 자신의 카드 패를 통해 카드셋(리스트)을 가진다는 것을 통해 Hand 를 추가했습니다.

**딜러와 참가자는 모두 Player** 
- 이전에는 Player 가 참가자를 의미했다면, 이후에는 딜러(Dealer) 와 참가자(Gambler) 가 Player 를 구현하는 형태입니다.
- 플레이어(Player)는 자신의 패(Hand) 를 가지고 게임에 참여하는 객체로, Dealer, Gambler 모두 게임에 참여하는 형태입니다.
- 다만,, 아직은 기능 구현되지 않았지만 "배팅하는 사람" 의 역할로 Gambler 라는 네이밍을 해보았습니다.

**뽑힌 카드 DrawnCard**
- 딜러에의해 카드 덱으로부터 뽑힌 카드를 DrawnCard 로 래핑했습니다.
- 딜러의 경우 특정 케이스에 대하여 카드를 덮어두기위해 이와 관련된 상태를 관리합니다.

**턴 수정**
- BlackJackGame 의 Turn 에 대해서 몇 가지 수정 사항이 있습니다. 
- 딜러의 Play 를 위해 dealersPlay 가 추가되었습니다.
- 딜러는 사용자의 입력없이 정해진 규칙(DealerActionProducer)에 의해 Hit or Stay 를 결정합니다.

**게임 승패 구현**
- 게임의 승패를 가리기 위해 Score, GameResult 가 수정/추가 되었습니다.

2022-06-27 13:39 UTC, vsh123 requested changes
안녕하세요!
3단계 구현 잘해주셨네요!! 👍 

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다~!!
천천히 진행해주셔도 좋습니다!! 마지막까지 화이팅하세요!

2022-06-27 13:39 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/cli/GameInitializedInfoWriter.kt
> +    fun write(participants: List<Gambler>) {
writer들을 여러개의 파일로 분리할 필요가 있을까요??

2022-06-27 13:39 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +class BlackJackGame private constructor(private var _cardDeck: CardDeck, private val _participants: List<Gambler>) {
_participants는 불변 list인데 backing Properties로 선언할 필요가 있을까요?

2022-06-27 13:39 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/player/Dealer.kt
> +        for (player in target) {
target을 players라고 네이밍하는것도 좋아보이는데 어떻게 생각하시나요?

2022-06-27 13:39 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/player/Dealer.kt
> +        if (hand.cards.isEmpty()) {
cards를 get하기보다는 물어보는게 어떨까요?

2022-06-27 13:39 UTC, vsh123 commented on src/test/kotlin/camp/nextstep/blackjack/player/DealerTest.kt
> +    @DisplayName("딜러의 첫번째 카드가 10 혹은 에이스가 아니면 두 번째 카드는 비공개한다.")
블랙잭에 요런 규칙이 존재하는가요~?? (궁금)

2022-06-27 13:39 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/player/Gambler.kt
> +    override fun receive(card: Card) {
[class layout](https://kotlinlang.org/docs/coding-conventions.html#class-layout)에 맞게 위치를 조정해보면 어떨까요?

2022-06-27 13:39 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +    fun play(turn: Turn<out Player>, actionProducer: (Player) -> Action, actionCallback: (Action) -> Unit = {}) {
actionProducer와 actionCallback, while이 해당 함수로 들어오게 되면서 해당 함수는 테스트하기 어려운 구조가 된 것 같은데요!

현식님이 위와 같은 구조로 변경하신 이유가 궁금합니다!

2022-06-29 10:49 UTC, aeomhs reviewed
깜박하고 submit 을 안했네요 !!!
확인 감사합니다 🙇‍♂️

2022-06-30 10:01 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +    fun play(turn: Turn, actionProducer: (Player) -> Action, actionCallback: (Action) -> Unit) {
> BlackJackGame::play 는 Player 의 Turn 을 수행합니다. 이때 Player 가 어떤 Action 을 할 것인지 ActionProducer 를 통해 정하게됩니다.
Turn 은 한 번의 HIT / STAY 를 결정하는 것이 아닌, Player 의 순서를 의미하는데요
HIT / STAY 한 번 결정할때마다(Action을 수행할때마다) 카드 패를 보여주기위해서 actionCallback 을 추가했습니다..
(이전에는 제가 엉뚱하게 cli writer 를 호출하고 있더라구요 😢)
흠.,. 지금 보니 Turn 을 play 할 것이 아니라 action 을 take, run, execute,, play,,? 하는 함수가 있으면 더 좋았을까 싶네요! 

개인적으로 현재 해당 함수는 사용자의 의사를 묻고, 결과를 출력해주는 Controller의 역할이 domain에 주입된 것 같은 느낌이에요!

while문을 controller에서 제어하시지 않은 이유는 무엇인가요~?

2022-07-03 11:54 UTC, aeomhs reviewed
질문 주신 내용에 대한 답변과 몇 가지 질문 남겨두었습니다!

제가 잘못 이해하고 있는 부분이나 이견이 있으시면 편하게 말씀 부탁드립니다!! 🙏🙏🙏
감사합니다 🙇‍♂️

2022-07-03 11:54 UTC, aeomhs commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +    fun play(turn: Turn, actionProducer: (Player) -> Action, actionCallback: (Action) -> Unit) {
ActionProducer 의 역할은,, 사용자턴(Turn)에 적용할 Action 을 계속 만들어주는 것인데요,
ActionProducer 가 사용자의 의사를 묻는 것이라고 생각하진 않았습니다 ,, 🤔

다만,, Gambler 의 ActionProducer 내부에서 block 이 걸리면서 IO 를 통해 사용자의 입력을 기다리게 되어서 마치 사용자의 의사를 묻는 것 같지만 
DealerActionProducer 만 보아도 BlackJack 게임 내부의 정해진 규칙대로 Action 을 생성하게됩니다. 

`Turn 이 종료될때까지 Action 을 수행한다` 라는 것을 도메인 규칙이라고 생각하고, play 안에 두었습니다!

잠깐 Controller 에서 Turn 의 진행을 하게된다는 생각을 해보았는데요
```kotlin
while(turn.isDone) {
  val action = BlackJackWriter.readGamblerAction()
  game.apply(turn, action) // 혹은 turn.play(action) 직접 호출,,?
  BlackJackWriter.write(gambler.hand)
}
```
이렇게 될 것 같습니다!

Controller 에서 Turn 의 종료 여부를 체크하는 것이 더 좋을까요?


+계속 생각해보니,,
Turn 을 별도 클래스로 만들고 외부에 공개하는 것이 좋을 것 같다는 생각도 드네요 ,, 🤔🤔🤔

2022-07-03 11:54 UTC, aeomhs commented on src/test/kotlin/camp/nextstep/blackjack/game/BlackJackGameTest.kt
> +    fun playAlwaysHit() {
음,, 마지막에 급하게 추가한 테스트같네요 😕 

처음에 기능 요구사항에 대한 테스트 케이스를 먼저 만들면서 TDD 를 진행했는데요
이후에 커버리지를 확인해보니 테스트되지 않는 라인이 발생했던 것 같습니다.,
그 중 하나였던 것 같은데요, 그래서 급하게 추가했던 것 같습니다.
어떤 부분을 놓친걸까요... 😭

또.. 계속 고민이었던 부분은 테스트하기 위해 어디까지 수정하는 것이 좋을지? 입니다.
기능 요구사항을 토대로 테스트 케이스를 만들다보니 BlackJackGame 의 play 메서드에 대한 테스트가 부족했고, 
이후에 어떤 테스트가 좋을지 고민해보았습니다.
"Tim에게 카드가 ACE, 10 나오고 STAY 를 하면 BLACKJACK 이다."
"Tim에게 카드가 6,7이 나오고 HIT 을 했는데 8이 나오면 BUST 이다." 
이와 같은 케이스가 적절해보였는데요,
이렇게 하기 위해서는 Game 의 CardDeck 을 주입해줄 수 있어야하고,, 또 초기화시 CardDeck 을 셔플하지 않아야합니다.
이 경우 테스트를 위해서 수정하는 것이 좋을까요?

그리고 "Tim에게 카드가 ACE, 10 나오고 STAY 를 하면 BLACKJACK 이다." 
이 케이스는 ,, play 의 테스트가 맞을까요? 아니면 통합 테스트라고 하는 것이 더 좋을까요?

2022-07-06 09:15 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/ui/PlayerHand.kt
> +    override fun toString(): String {
오호 제가 꼬아서 드린 코멘트를 정확하게 이해해주셨네요!! 💯 

> Writer 에서 DTO 의 상태를 어떻게 보여줄 것인지 

정확히 해당 의도가 맞습니다! DTO가 특정 ui를 위한 처리를 해주는건 지양하는게 좋을 것 같아서요~!!

2022-07-06 09:28 UTC, vsh123 commented on src/main/kotlin/camp/nextstep/blackjack/game/BlackJackGame.kt
> +    fun play(turn: Turn, actionProducer: (Player) -> Action, actionCallback: (Action) -> Unit) {
더 좋은건 없을 것 같아요! (제가 드린 것도 하나의 의견일 뿐입니다)
위에 코멘트 드린 테스트하기 좋은 구조와 함께 고민하셔서 현식님만의 결론을 내보시면 어떨까요?!

2022-07-06 09:29 UTC, vsh123 approved these changes
현식님 안녕하세요!
우선 리뷰가 많이 늦어져서 죄송합니다ㅠㅠ

궁금하신 질문에 대해 제 생각을 적어봤어요~! 참고부탁드릴게요! :)
마지막까지 화이팅하시길 바라겠습니다!

2022-07-06 09:29 UTC, merged