3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #303
Opened 2022-07-03 10:06 UTC by Hyeon9mak

안녕하세요 규남님, 딜러 기능 추가했습니다!
이번 리뷰도 잘 부탁드립니다 🙇‍♂️

2022-07-04 14:58 UTC, kyucumber requested changes
안녕하세요 리뷰가 조금 늦었네요 😭 

기존 구조에서 크게 바뀐 부분은 없는 것 같아요. 간단한 몇가지 코멘트 남겨두었으니 확인 부탁드립니다~

2022-07-04 14:58 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/participant/state/Stay.kt
> +        }
GameResult를 구하는 부분의 역할이 Blackjack, Bust, Stay 등에서 각각 override 되고 있고 일부는 Score에서 구현되고 있는 것 같아요. Score에서 모든 역할을 수행할수도 있지 않을까요? 

compareGameResult에서 Bust 등의 모든 로직을 처리하고 아래와 같이 구현하는건 어떨까요?

```suggestion
        return this.score().compareGameResult(other = otherScore)
```

2022-07-04 14:58 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/participant/state/Cards.kt
> +) {
외부에 List 인터페이스의 메소드들이 노출되긴 하겠지만 불변이라 아래와 같이 delegation 사용을 고려해볼 수 있을 것 같네요.

```suggestion
class Cards(values: List<Card> = listOf()) : List<Card> by values {
```

노출되는 타입도 일관성 있게 Cards로 가져갈 수 있을 것 같아요.

```kotlin
fun cards(): Cards
```

2022-07-05 03:21 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/domain/participant/state/Stay.kt
> +        }
이 부분에서 규남님과 같은 고민을 했었습니다!! 👍 👍 

Blackjack, Bust, Stay 등 상태에게 판단 역할을 넘긴 이유가 결국은 Blackjack 승리조건 때문이었는데요,
Score는 21점이 Blackjack에 해당되는 점수라는건 알지만, 21점이 무조건 Blackjack은 아니라는 상황 때문에 그랬습니다.

- Stay 21과 Blackjack 21 끼리의 승패를 비교하려면 카드의 장수를 알아야 함
- Stay와 Bust, Stay와 Blackjack 끼리의 승패를 비교하려면 점수 뿐만 아니라 상태값 까지 알아야함

결국 Score 쪽에서 상태와 카드 장수를 알아야하는 문제가 있어서 상태 쪽에 판단 로직을 넣고, Score는 점수만 비교하도록 했습니다.

2022-07-05 03:46 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/domain/participant/state/Cards.kt
> +) {
'`List<Card>`를 delegation 한다는게 어떤 의미지? 캡슐화가 깨지지 않을까?' 고민 했는데,
제 코드를 다시 뜯어보고서야 규남님의 깊은 뜻을 이해할 수 있었습니다.. 🙇‍♂️ 
어차피 `values: List<Card>`를 getter 처럼 끌어다 사용해서 캡슐화고 뭐고 없으니,
delegation 해서 `List<Card>` 대신 `Cards`로 들고 다니면 어떠냐는 말씀이셨던거 같아요!
굉장히 멋진 코드인거 같아서 당장 반영했습니다 👍 

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/37354145/177244911-e510b577-d867-4ca5-a13d-ceeb008d1f10.png">

다만 `List<Card>`를 최종적으로 하는 곳들이 모두 출력을 위해 List 컬렉션을 내보내고 있어서
최후에는 values를 꺼내어 사용하는게 아쉽네요... 😭

2022-07-07 13:22 UTC, merged