🚀 1단계 - 코틀린 DSL
next-step/kotlin-blackjack pull request #313
Opened 2022-11-29 14:22 UTC by dreamboy1339

코틀린 DSL 학습 코드 PR 요청 드립니다!

2022-11-29 15:37 UTC, laco-dev requested changes
안녕하세요.
블랙잭 미션동안 잘 부탁드립니다.

본격적으로 미션 진행하기 앞서 DSL 연습을 잘 해주셨네요.
다만 Builder 개념과 타입에 대해 한가지 확인하고 넘어가면 좋을 내용이 있어서 의견 남겨드렸습니다.

2022-11-29 15:37 UTC, laco-dev commented on src/test/kotlin/study/DslTest.kt
> +data class Skill(val softSkills: List<String>, val hardSkills: List<String>)
Skill은 하나의 기술을 나타내는 개념으로 볼 수 있지 않을까요?
스킬이 softSkills, hardSkills를 가진다는 것으로 잘 예측이 되지 않을 것 같습니다.

또한, soft, hard 외에 다른 스킬 종류가 생기면 프로퍼티가 계속해서 늘어나는 문제로 이어지는데요.

아래 순서에 따라 Skill 구조를 개선 해보면 어떨까요?

1. Skills 라는 객체로 분리 해본다.
2. Skills는 Skill 타입의 데이터들을 가진다.
3. Skill을 sealed class로 개선 해본다. (Soft, Hard 타입이 있다)

2022-11-29 15:37 UTC, laco-dev commented on src/test/kotlin/study/DslTest.kt
> +data class Person(val name: String, val company: String, val skills: Skill, val languages: List<Language>)
프로퍼티의 이름과 타입이 맞지 않는 것 같아요
```
skills: Skill
```

2022-11-29 15:37 UTC, laco-dev commented on src/test/kotlin/study/DslTest.kt
> +    private lateinit var language: List<Language>
모든 값을 lateinit으로 만들어서 초기화가 되지 않을 경우 오류가 발생할 수 있는데요!

사실 Builder 패턴에서는 반드시 필요한 값은 생성자로 만드는게 원칙적이기는 합니다.
즉 필수로 4가지를 받아야한다면 아래와 같은 패턴이 만들어지고는 합니다.
```kotlin
Builder(name, company, skill, language).build() // Optional이 없음
```

프로퍼티의 기본값을 활용하거나 nullable을 이용해서 optional 형태를 만들어 보면 어떨까요?
List 형태는 emptyList를 활용할 수 있습니다.

2022-12-03 08:14 UTC, dreamboy1339 commented on src/test/kotlin/study/DslTest.kt
> +data class Skill(val softSkills: List<String>, val hardSkills: List<String>)
스킬에 대해서 구조 개선 진행합니다!

2022-12-03 08:22 UTC, dreamboy1339 commented on src/test/kotlin/study/DslTest.kt
> +data class Person(val name: String, val company: String, val skills: Skill, val languages: List<Language>)
수정합니다!

2022-12-03 08:30 UTC, dreamboy1339 commented on src/test/kotlin/study/DslTest.kt
> +    private lateinit var language: List<Language>
프로퍼티에 기본 값을 할당합니다!

2022-12-03 13:10 UTC, laco-dev approved these changes
피드백 잘 반영 해주셨네요!

블랙잭 미션이 게임에 대한 이해도가 상당히 높게 요구되는 만큼, 
게임을 충분히 이해하고 구현을 시작하시면 조금 더 수월할 것 같습니다! 🙏🏻

2022-12-03 13:10 UTC, merged