🚀 2단계 - 블랙잭
next-step/kotlin-blackjack pull request #339
Opened 2022-12-06 13:58 UTC by chayoung-choi

### 기능 구현 목록
- [X] 카드
    - [X] Ace, 2 ~ 10, King, Queen, Jack의 숫자값 중 하나를 가진다.
    - [x] 하트, 다이아, 스페이드, 클로버 4 종류의 모양 중 하나를 가진다.
- [X] 카드 리스트
    - [X] 카드들을 가질 수 있고, 카드 수를 가져온다.
    - [X] 카드를 추가할 수 있다.
    - [X] 카드 합계를 반환한다.
- [X] 덱
    - [X] 전체 카드 총 52장을 가진다.
- [X] 딜러
    - [X] 최초 52장의 덱을 가진다.
    - [X] 딜러는 보유한 카드를 셔플할 수 있다.
    - [X] 참가자에게 카드를 한장씩 분배할 수 있다.
- [X] 참가자
    - [X] 이름을 가진다.
    - [X] 딜러가 분배한 카드를 가질 수 있다.
    - [X] 가지고 있는 카드 점수를 카운팅한다.
    - [X] 카드를 추가로 받을 수 있다.
- [X] 점수
    - [X] 카드의 점수를 카운팅한다.
    - [X] 카드의 합이 21이 넘으면 ACE 카드는 11로, 넘지않으면 1로 계산된다.
- [X] 게임
    - [X] 딜러와 참가자들을 가진다.
    - [X] 게임 시작시 2장의 카드를 랜덤하게 참가자들에게 분배한다.
    - [X] 카드를 추가로 받을지를 요구한다.
    - [X] 추가로 받을 때마다 참가자의 카드 정보를 출력한다.
- [X] 입력
    - [X] 플레이어 이름을 쉼표로 구분하여 입력받는다.(최대 8명)
    - [X] 추가로 카드를 받을지의 여부를 입력받는다.
- [X] 출력
    - [X] 참가자가 보유한 카드들을 출력한다.
    - [X] 게임 시작시 2장을 분배하고 결과값을 출력한다.
    - [X] 게임 결과를 출력한다.

2022-12-08 14:08 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요!! 😊
미션을 진행 하시다 보니 3단계 미션에 대한 내용도 동시에 진행하신 걸로 보이네요.
미션은 꼭 순서대로 진행해보시길 부탁드려요!
3단계의 내용은 잠시 복사해 두고, 2단계 미션 내용만 먼저 진행해보시길 바라요 :)

코드를 짧게 작성하려고 노력 하신 것이 잘 느껴져서 읽기가 아주 좋았어요 👍
요구사항도 열심히 정리해주신 것이 인상 깊었습니다 :)

여러 생각해보면 좋을 점들에 코멘트 남겨두었으니 확인 부탁드릴게요!
피드백 반영하시고 다시 리뷰 요청 부탁드립니다 💪

2022-12-08 14:08 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Score.kt
> +        var score = 0
점수를 계산하는 것을 다른 객체에서 수행하기 보다, Cards 객체 스스로가 자신의 점수를 계산할 수 있게 만들어보는 것은 어떨까요?

2022-12-08 14:08 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Score.kt
> +                CardNumber.KING -> SPECIAL_CARD_SCORE
카드의 점수는 CardNumber Enum이 직접 갖게 해보는 것은 어떨까요?

2022-12-08 14:08 UTC, malibinYun commented on src/test/kotlin/blackjack/domain/CardTest.kt
> +    }
이 테스트는 Card의 테스트보다는,
각각 CardNumber와 CardShape의 테스트이기에 불필요해 보입니다 :)

2022-12-08 14:08 UTC, malibinYun commented on src/test/kotlin/blackjack/domain/PlayerTest.kt
> +    }
이름을 가지는 것 자체에 대한 테스트는 의미가 없어보여요.
이름에 대한 조건인, EmptyString이 인풋으로 들어왔을 때에 대한 테스트를 해보는 것은 어떨까요?

2022-12-08 14:08 UTC, malibinYun commented on src/test/kotlin/blackjack/domain/PlayersTest.kt
> +    }
이 부분도 참가자 자체를 가지는 것에 대해선 의미가 없어 보이니, 정원을 초과한 경우에 대해 테스트해보면 좋겠네요 :)

2022-12-09 01:33 UTC, chayoung-choi commented on src/main/kotlin/blackjack/domain/Constants.kt
> +}
해당 상수들은 각기 다른 2개의 클래스에서 사용되고 있습니다. 
사용하는 객체에 할당하게되면 다른 쪽에서 그 도메인의 상수를 가져오게되는데 상관이 없는걸까요??

2022-12-09 01:39 UTC, chayoung-choi commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    }
이미 list 프로퍼티가 불변값으로 선언이 된게 아닌건가요? 지난 강의때 들었던 내용으로 list를 불변으로 선언하고 내부에서 가변으로 값을 변경처리했다고 생각됐습니다.
그리고 add 행위에 Cards 객체를 반환해줘야 하는 이유는 무엇때문에 그런지 궁금합니다! 🧐

2022-12-09 05:32 UTC, chayoung-choi commented on src/main/kotlin/blackjack/domain/Game.kt
> +        ConsoleOutput().printLine()
players 안에 view.input 값을 받는 로직 없이 하려니
controller 단에서 받는거 외에 마땅한 방법을 찾기 못했습니다.

2022-12-10 05:48 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    }
생성자의 파라미터로 받는 list를 내부에서 복사해서 사용하셔서, 확실히 외부 mutableList인스턴스에대한 변경 문제는 없습니다 :)

다만, 불변 객체의 의미는, 객체 내부에서 변경되는 값이 전혀 없음을 의미해요.
즉, 내부에서 _list 같이 Mutable한 값이 한 개도 없어야 합니다.

그러면 값이 추가되어야할 때, 값을 추가한 형태의 Cards 객체를 전혀 만들 수 없을 것이라 생각이 드실 수 있어요 :)
그렇기 떄문에, add 메서드의 결과물로 값을 추가한 형태의 Cards 객체를 넘겨주면 해결이 됩니다.

```kotlin
fun add(card: Card) : Cards{
    return Cards(this.list + card)
}
```
위 형태 처럼 아예 새로운 불변 객체를 생성해낼 수 있어요 🙂

2022-12-10 05:52 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Constants.kt
> +}
해당 상수가 꼭 필요하다면 가지고 오는 게 맞겠지요.
그 이전에, 메시지를 던져 값을 가져올 수 있게 바꾼다면, 해당 상수가 다른 곳에서 사용되어야할 떄가 많아요 :)
해당 상수가 정말로 필요한 곳에서만 사용해보는 것을 생각하다보면, 필요 없는 의존성을 줄일 수 있을거에요 :)

2022-12-10 05:53 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Game.kt
> +        ConsoleOutput().printLine()
그렇다면 view에 대한 함수를 람다를 통해 파라미터로 전달해볼 수 있겠네요!

2022-12-12 13:19 UTC, malibinYun approved these changes
2단계 미션 고생 많으셨어요!!!
요구사항 반영하시느라 특징 고생 많으셨습니다 :)
피드백도 반영하시고, 단계 별로 미션 수행하시는 데 노력을 정말 많이 하신 걸로 보여요!
생각해보면 좋을 점들에 코멘트 남겨두었어요~
피드백은 다음 미션에 반영해주시면 됩니다 🙂
다음 미션을 위해 머지할게요 :)
미션 완주까지 응원할게요!!

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Card.kt
> +    override fun toString(): String = number.value + shape.label
카드를 캐싱 해주셨고, 해당 카드르를 찾는 메서드를 만들어주셨으니, 생성자는 private으로 감춰도 좋겠네요 🙂

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Card.kt
> +    }
어떤 인풋이 들어와서 에러가 났는지도 메시지에 표시해주면 좋겠네요 :)

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/CardNumber.kt
> +    TWO("2", 2),
ACE카드의 기본 점수는 1이고, 높은 점수가 나타나는 것은 특수 케이스라고 생각해요 :)
11점으로 계산될 때는 로직으로 나타내보는 것은 어떨까요?

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    fun addAll(cards: Cards): Cards = Cards(this.list + cards.list)
plus operator를 override 해서 활용해보는 것은 어떨까요?

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Deck.kt
> +
초기 카드를 생성자로 받을 수 있다면, 랜덤에 대한 테스트에 더 용이해지겠네요 :)

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Player.kt
> +    fun hit(card: Card): Player = this.copy(name = this.name, cards = this.cards.add(card))
Player도 불변 객체로 만들어 주셨네요! 👍👍

2022-12-12 13:19 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/CardNumber.kt
> +        }
이 메서드도 기능을 잘 하고 있는지에 대한 테스트도 있으면 좋겠네요 :)

2022-12-12 13:19 UTC, merged

2022-12-12 14:16 UTC, chayoung-choi commented on src/main/kotlin/blackjack/domain/Card.kt
> +    override fun toString(): String = number.value + shape.label
private으로 감싸니 Cards에서 countingCard()시 점수와 ACE 카드 비교가 불가하게 됩니다.
이에 따른 필요 메소드를 만들어야할 것 같은데, 이 경우는 어떤게 더 이득이 되는지 궁금합니다 🤔

2022-12-13 14:34 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Card.kt
> +    override fun toString(): String = number.value + shape.label
음!! 어떤 부분을 private으로 감싸셨는지 잘 모르겠네요! 아마 생성자가 아닌 다른 곳을 private으로 선언하신 것 같아요.

저는 이미 모두 생성하고, 생성된 Card를 찾는 메서드인 `of` 메서드가 있기 때문에,
외부에서 Card 생성자를 활용해서 새 Card instance를 만들어내는 것을 방지해보자는 의미였어요!

코틀린의 주 생성자를 private으로 선언하는 방법은 아래와 같아요 :)
```kotlin
class card private constructor(val number: CardNumber, val shape: CardShape) {
//...
}
```