Step2: 블랙잭
next-step/kotlin-blackjack pull request #350
Opened 2022-12-11 12:52 UTC by JunHoPark93

안녕하세요. 2단계 미션 제출합니다.
개선할부분 지적부탁드립니다!

2022-12-13 07:52 UTC, wisemuji requested changes
안녕하세요 준호님!

블랙잭 구현을 잘 해주셨습니다 💯  블랙잭 도메인을 이해하고 잘 구현해주셨네요. 코틀린 문법에 이미 익숙하신 것으로 보입니다.
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다. 변경사항이 많아서 코멘트가 좀 많습니다 😅  블랙잭 미션은 처음 구조 설계하는 것이 제일 오래 걸리기에 남은 단계는 금방 마치실 것이라고 생각합니다 🙂 

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2022-12-13 07:52 UTC, wisemuji commented on README.md
> +# kotlin-blackjack
기능 목록 정리 👍 

지금은 커밋을 파일 단위로 해주셨는데요, 정리하신 기능 목록이 commit의 단위로 나올 수 있도록 해보시면 더욱 좋습니다. 지금 단계에서 바꾸기 어렵다면 다음 미션 진행하실때부터 참고해주세요. 

> git의 commit 단위는 앞 단계에서 README.md 파일에 정리한 기능 목록 단위로 추가한다.

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/controller/Main.kt
> +}
이 로직이 controller에 있는게 적절할까요? 개발자마다 의견이 다를 수 있는 영역인 것 같은데 저는 이 부분은 컨트롤러가 도메인 로직의 역할을 수행하고 있는 것 같다고 생각됩니다. 컨트롤러는 도메인 로직을 수행하기 위해 메세지만 보내는 식으로 바꿔보면 어떨까요? 준호님의 의견이 궁금해요!

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Card.kt
> +    }
이 부분은 뷰에 해당하는 로직인 것으로 보입니다. 도메인이 뷰에 직접적으로 의존하지 않도록 바꿔보면 어떨까요?

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Card.kt
> +        const val BLACKJACK_ACE_CORRECTION = 10
이 세 값이 모두 '카드'의 관심사일까요?

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Deck.kt
> +    private var _cards = cards.shuffled().toMutableList()
MutableList 타입의 경우 이미 가변 타입이므로 var로 선언하지 않아도 됩니다. 참고로 List 타입을 var로 선언하여 값을 새로 할당하는 것보다 MutableList 내부 요소를 조작하는 것이 더 적은 비용이 듭니다 🙂

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Deck.kt
> +    }
유효성 검사 👍

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Deck.kt
> +        }
카드 인스턴스 생성에 대한 고민 👍  강의에서 재성님이 소개해주신 아이디어를 잘 적용해주셨네요!

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +    private var _cards: List<Card> = mutableListOf()
MutableList 타입의 경우 이미 가변 타입이므로 var로 선언하지 않아도 됩니다. 참고로 List 타입을 var로 선언하여 값을 새로 할당하는 것보다 MutableList 내부 요소를 조작하는 것이 더 적은 비용이 듭니다 🙂

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +    }
블랙잭 도메인에 대한 이해 👍

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +    }
toList() 방어적 복사 👍 

참고로 저는 이런 종류의 함수는 [backing 프로퍼티](https://kotlinlang.org/docs/properties.html#backing-properties)로 만들어 가변 타입은 감추고 불변 타입은 외부에 노출하도록 하는 것을 선호합니다. 읽기/쓰기 연산이나 유효성 검사 등의 로직이 포함되어 있는 경우에는 함수로, 단순 클래스 내부 값을 노출하는 경우에는 프로퍼티의 getter로 만드려고 해요.
```suggestion
        val cards: List<Card> get() = _cards.toList()
```

2022-12-13 07:52 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +        val scoreBeforeAceCorrection = _cards.sumOf { it.cardNumber.number }
cards의 리스트 요소의 cardNumber를 직접 꺼내어(get) 사용하기보다 메세지를 던져보면 어떨까요? (이럴 때 일급 컬렉션을 사용하는 것도 괜찮은 방법일 것 같아요~!) 이하 동일합니다.

2022-12-13 07:52 UTC, wisemuji commented on src/test/kotlin/com/nextstep/blackjack/domain/CardNumberTest.kt
> +            ).forAll { numberByCard ->
Kotest를 활용하여 테스트를 잘 작성해주셨어요 👍  forAll을 활용하여 복수의 값 확인 👍

2022-12-13 07:52 UTC, wisemuji commented on src/test/kotlin/com/nextstep/blackjack/domain/CardTest.kt
> +            val card2 = Card(Symbol.DIAMOND, CardNumber.ACE)
이런 종류의 테스트의 경우 저는 data class 자체에 대한 테스트라는 생각이 들어 선호하지는 않습니다. Card가 data class라는걸 명시적으로 확인하는데에 의미가 있을 수는 있겠군요. 이 의견은 참고만 해주세요!

2022-12-13 07:52 UTC, wisemuji commented on src/test/kotlin/com/nextstep/blackjack/domain/DeckTest.kt
> +            }
만약 덱이 52장에서 더 줄어들거나 늘어난다면 이런 테스트도 모두 수정되어야 하기에 Deck의 인스턴스 생성에서 개수를 지정하여 생성하면 변경에 유연한 로직이 될 것 같아요.

2022-12-13 07:52 UTC, wisemuji commented on src/test/kotlin/com/nextstep/blackjack/domain/PlayerTest.kt
> +                player.isBust() == false
shouldBe로 검증하는걸 의도하신 것 같아요!

2022-12-13 07:52 UTC, wisemuji commented on src/test/kotlin/com/nextstep/blackjack/domain/PlayerTest.kt
> +class PlayerTest : FunSpec({
Ace 점수 계산에 대한 테스트도 추가해주세요!

만약 PlayerTest가 너무 커질 것 같다는 생각이 든다면
1. Player가 실제로 하고 있는 일이 많다는 뜻을 암시하며
2. 클래스 분리가 필요한 시점일 수 있습니다 🙂

2022-12-15 11:31 UTC, JunHoPark93 commented on src/main/kotlin/com/nextstep/blackjack/controller/Main.kt
> +}
저도 동의합니다!
근데 view의 input, output이 엮여있어서 이게 도메인쪽으로 옮기기가 좀 애매한부분이 있는거같아요. 일단 최대한 분리를 시도해봤는데 bust while문 내의 동작들까지 분리할 수 있는 방법이 있을까요?

2022-12-15 11:56 UTC, JunHoPark93 commented on src/main/kotlin/com/nextstep/blackjack/domain/Card.kt
> +    }
수정해보았습니다

2022-12-15 11:59 UTC, JunHoPark93 commented on src/main/kotlin/com/nextstep/blackjack/domain/Card.kt
> +        const val BLACKJACK_ACE_CORRECTION = 10
블랙잭 패키지내 Card여서 관련있다고 봤는데 분리해봤습니다

2022-12-15 11:59 UTC, JunHoPark93 commented on src/main/kotlin/com/nextstep/blackjack/domain/Deck.kt
> +    private var _cards = cards.shuffled().toMutableList()
그렇네요! 불변타입으로 수정했습니다

2022-12-15 12:08 UTC, JunHoPark93 commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +    }
오 이거 제대로 한건지 한번 확인부탁드릴게요

2022-12-15 12:15 UTC, JunHoPark93 commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +        val scoreBeforeAceCorrection = _cards.sumOf { it.cardNumber.number }
수정해보았습니다

2022-12-15 12:16 UTC, JunHoPark93 commented on src/test/kotlin/com/nextstep/blackjack/domain/CardTest.kt
> +            val card2 = Card(Symbol.DIAMOND, CardNumber.ACE)
그렇네요. 이거 자바 습관이 남아서 그런거같아요. 동일성 체크에 대한 강박인거같습니다.
껍데기만 있는 클래스같아서 이 테스트는 그냥 지울게요~

2022-12-15 12:18 UTC, JunHoPark93 commented on src/test/kotlin/com/nextstep/blackjack/domain/DeckTest.kt
> +            }
const선언으로 개선해보았습니다

2022-12-15 12:18 UTC, JunHoPark93 commented on src/test/kotlin/com/nextstep/blackjack/domain/PlayerTest.kt
> +                player.isBust() == false
감사합니다!

2022-12-15 12:20 UTC, JunHoPark93 commented on src/test/kotlin/com/nextstep/blackjack/domain/PlayerTest.kt
> +class PlayerTest : FunSpec({
ace계산을 담당하는 private 메서드는 '카드 draw를 하고 점수 계산'에서 ace가 1혹은 10으로 계산하는 케이스가 테스트 되고있긴합니다! 점수 계산을 player가 직접 담당하는것을 의도했지만 추후 단계에서 역할이 많아지게 되면 분리해보겠습니다!

2022-12-16 15:43 UTC, wisemuji approved these changes
안녕하세요 준호님! Step2 리뷰 반영을 잘 해주셨습니다 💯 

코멘트를 많이 남겼었는데 꼼꼼하게 전부 반영해주셨네요 👏 
조금 고민해보시면 좋을 내용을 코멘트로 달았으니 다음 단계 미션 진행해주시면서 같이 반영해주시면 됩니다!

남은 블랙잭 미션은 구현하는 데에 상대적으로 시간이 덜 소요되실 거예요. 
꼭 완주하시길 바라면서 다음 미션도 화이팅입니다 🙏

2022-12-16 15:43 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/controller/Main.kt
> -    }
일급 컬렉션으로 도메인 로직을 잘 분리해주셨습니다 👍 말씀하신 것처럼 bust while문 내의 동작들까지 분리하기에는 view의 로직이 얽혀있어서 어려움이 있을 것 같네요.

2022-12-16 15:43 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/controller/Main.kt
> +    val players = Players(playersInput.map { Player(it) })
이러한 구문을 함수 reference로 넘길 수 있습니다. 
```suggestion
val players = Players(playersInput.map(::Player))
```

lambda로 작성하는 것과 어떤 차이가 있는지 참고할 수 있는 글을 소개해드릴게요 🙂 
https://proandroiddev.com/kotlin-lambda-vs-method-reference-fdbd175f6845

2022-12-16 15:43 UTC, wisemuji commented on src/main/kotlin/com/nextstep/blackjack/domain/Player.kt
> +        }
backing property 활용 👍

2022-12-16 15:43 UTC, wisemuji commented on src/test/kotlin/com/nextstep/blackjack/domain/PlayersTest.kt
> +            exception.message shouldBe "초기화 할 수 없는 상태입니다"
새로 추가된 기능도 꼼꼼한 테스트 👍  컨트롤러에 있던 로직을 도메인 로직으로 옮겼기 때문에 초기화 구문도 테스트할 수 있게 되었어요. 예외발생 케이스 말고 정상적으로 초기화되는지도 검증하면 어떨까요?

2022-12-16 15:45 UTC, merged