Step2: 블랙잭
next-step/kotlin-blackjack pull request #357
Opened 2022-12-15 13:00 UTC by wrallee

안녕하세요 2단계 미션 제출합니다.
리뷰 부탁드립니다!

2022-12-18 02:01 UTC, ohgillwhan requested changes
안녕하세요. 우찬님
화면단과 도메인단의 분리가 조금 더 이뤄졌으면 좋을것 같네요~
리뷰 확인 부탁드려요.

2022-12-24 04:52 UTC, wrallee commented
길환님 안녕하세요.
피드백 주신 내용 반영했습니다. 리뷰 부탁드립니다🙇

---

> 화면 부분과 로직 부분이 분리되어서 `Application`에 빠지면 더 좋을것 같습니다~ `fun initPlayers(countOfPlayer: Int)`등의 메서드를 만들어서 입력과 분리하는거죠~

➡️ 요 내용은 `BlackjackGame`이라는 Service Layer를 만들었다가 View 로직이 담긴 함수를 파라미터로 받는게 View에 의존하게 되는것같아서 지우고 `Application`으로 다시 이동했습니다. 제가 의도파악을 정확히 한건지 잘 모르겠네요. 리뷰 부탁드립니다! 

> `Player`에 `finalScoreOf`를 두고, `FinalScoreCalculator`는 `Cards`만 받게 하면 어떨까요?
> `player.finalScoreOf()`를 호출하면 `player`의 `cards`를 `FinalScoreCalculator`로 넘기는거죠.
>
> 더 나은 방법은 일급컬렉션을 써보는것일거 같네요. 그러면 Calculator가 없어져도 될거 같아요.

➡️ 이 부분도 반영해봤는데 의도하신 내용대로 구현했는지 리뷰부탁드립니다!
(제가 제대로 했다면)`Cards`에 복잡한(?) 계산 알고리즘이 들어가는게 맞나?
알고리즘은 교체될 수 있지 않을까? Calculator로 빼는게 좋지 않을까? 라는 생각도 들었습니다.

➡️ 추가로 궁금한점은 제가 OutputView 쪽에서 players 들을 조작할수 있는데요(ex. `players.first().addCard(...)`).
이런걸 어떻게 막아야 할까 고민하다 잘 안되는것 같아서 조언해주실수있나요?
(피드백 강의자료에 있는 다형성을 쓰면 뭔가 될것같기도? 한데 너무 많은 변경이 일어날것같아 적용은 안했습니다)

2022-12-25 04:31 UTC, ohgillwhan requested changes
우찬님 코드 💯 
리뷰 확인 부탁드려요!

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        println()
공백을 줘서 조금 더 깔끔하게 처리하는건 어떨까요?

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +class BlackjackApplication {
`Application`도 테스트가 가능할까요? `View`등을 `Interface`하면 될거같아요~

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +    fun getCard(): Card {
`get`의 네이밍은 사이드 이펙이 없어보여요. 하지만 카드를 삭제하고 있네요! 더 좋은 이름 없을까요?

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +            players.forEach { it.addCard(cardDeck.getCard()) }
카드를 꺼내올 때 `INIT_CARD_COUNT` 만큼 한번에 가져오는건 어떨까요?

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/view/InputView.kt
> +    }
`View`에서 `Value Object`도 아닌 `Entity`를 생성하는건 조금 아쉬운것 같아요.

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +        initPlayers(players, cardDeck)
`players`의 이름만 받고, `initPlayers`에서 정말 `Player`를 생성하는건 어떨까요? 그러면 `Player`생성과 동시에 카드를 줄 수 있을거 같아요.

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/model/CardDeck.kt
> +        }
깔끔하네요~

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/model/Cards.kt
> +}
`Cards` 바깥으로 뺀 이유가 있을까요?

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/model/Player.kt
> +        get() = _cards
`List<Card>`를 사용함으로 써 일급컬렉션의 이유가 없어진거 같아요!

2022-12-25 04:31 UTC, ohgillwhan commented on src/main/kotlin/blackjack/model/Cards.kt
> +        calculate(cards, index + INDEX_INCREMENT, accumulator + Denomination.ACE.specialScore!!)
`specialScore`가 `nullable`이여서 `!!`가 나온것 같네요. `!!`를 사용하면 조금 불안정해보여요! 구조를 조금 수정하면 없앨 수 있을거 같습니다!

2022-12-25 04:33 UTC, ohgillwhan commented
아마 리뷰남긴것에 대부분의 답변이 되었을것 같습니다! `Cards`에 복잡한 알고리즘이 들어가도 괜찮고, 블랙잭 게임이 바뀌지 않는 이상 알고리즘이 크게 교체되지는 않아도 될것 같습니다. 메서드의 이름과 맞는 역할만 잘 수행한다면요!

3번은 어느정도 고민이 필요한데, 처음 카드를 나눠주는 부분에서 초기화를 조금 잘 해보면 괜찮지 않을까 싶습니다!

2022-12-26 01:30 UTC, wrallee commented on src/main/kotlin/blackjack/model/Cards.kt
> +}
> Cards에 복잡한(?) 계산 알고리즘이 들어가는게 맞나?

이 생각 때문에 빼놨었습니다😅
아래 답변주신내용 확인했습니다 이동할게요!

2022-12-26 04:35 UTC, wrallee commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +class BlackjackApplication {
피드백 주신 내용이 혹시 어떤 의미일까요?
1. `InputView`의 `Interface`를 만들고, 특정 값을 리턴하는 구현체를 만들어서 인풋을 고정시키고
2. `Application` 내 `Players`, `CardDeck`에 대한 검증을 하는 방식일까요?

그리고 `Appllication`에서도 `initPlayers(...)` 외에 어떤 부분을 테스트해야할 지 감이 잘 안잡히네요😭
혹시 좀 더 구체적인 설명 가능할까요?😶

2022-12-26 04:36 UTC, wrallee commented
피드백 반영했습니다!
다만 아래 내용은 정확히 이해를 못해서 적용못했는데 좀 더 자세한 설명 가능할까요?

> Application도 테스트가 가능할까요? View등을 Interface하면 될거같아요~

2022-12-28 04:34 UTC, ohgillwhan approved these changes
코드 전체적으로 깔끔하네요!
DM으로 주고받은 내용은 다음 step3 에서 적용 고민 부탁드려요!

2022-12-28 04:34 UTC, ohgillwhan commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +    }
`Players`라는 일급 컬렉션이 나와도 괜찮아 보여요

2022-12-28 04:34 UTC, ohgillwhan commented on src/main/kotlin/blackjack/model/Player.kt
> +    var cards = initCards
```suggestion
    var cards: Cards = Cards()
)
```

2022-12-28 04:34 UTC, ohgillwhan commented on src/main/kotlin/blackjack/view/InputView.kt
> +    val readPlayerPickAnswer: (Player) -> String = {
이 부분에서` boolean` 을 내려줘도 괜찮긴 하겠네요~

2022-12-28 04:34 UTC, merged