feat: Step3: 블랙잭(딜러)
next-step/kotlin-blackjack pull request #385
Opened 2022-12-28 14:25 UTC by rolroralra

- [x] 딜러는 처음에 받은 2장의 합계가 16이하이면 반드시 1장의 카드를 추가로 받아야 하고, 17점 이상이면 추가로 받을 수 없다.
- [x] 딜러가 21을 초과하면 그 시점까지 남아 있던 플레이어들은 가지고 있는 패에 상관 없이 승리한다.
- [x] 게임을 완료한 후 각 플레이어별로 승패를 출력한다.

2022-12-31 05:23 UTC, ohgillwhan requested changes
리뷰 늦어져서 죄송합니다!
리뷰 확인 부탁드려요~

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/card/vendor/CardVendor.kt
> +    fun drawPlayerFirstTwoCards(): Cards
만약 2장이 아닌, 3장으로 바뀐다면 조금 어렵겠네요! 이럴 땐 `drawPlayerFirstCards(count: Int = 2)` 등으로 지정하는건 어떨까요?

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/Blackjack.kt
>          }
검증로직이 `player`의 `hit`에 있어도 괜찮을것 같네요!

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +        )
팩터리 메서드인 `of`를 통해서 만들어야 할까요? `Player` 객체에게 결과를 내라고 해도 괜찮을것 같아요.

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +class Dealer(
메서드의 순서를 정리해볼까요?
A -> B -> C 순서대로 메서드를 호출한다면
코드의 배치도 똑같이 이뤄지면 좋을것 같아요~

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +    private fun hit(): Unit = hit(drawCard())
재사용하지 않는데, 해당 메서드가 필요할까요?

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +        player.takeResult(playerResult)
`Player` 객체에게 하나의 메서드로 응집할 수 있을것 같아요

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/card/vendor/CardVendor.kt
> +    fun drawPlayerFirstTwoCards(): Cards
`drawCards()` 라는 네이밍으로도 충분할것 같네요!

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/result/PlayerResult.kt
> +enum class PlayerResult {
`opposite`에서 사용되는 `DealerResult` 가 나와야 하지 않을까요?!

2022-12-31 05:23 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/result/PlayerResult.kt
> +            return if (playerCards.isBust())
`when` 은 어떨까요?

2022-12-31 06:48 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +        player.takeResult(playerResult)
저는 이걸 딜러 객체에게 모두 응집하였습니다. 

player에게 무언가 결과를 정산하는 공개메서드를 넣어버린다면, 

player가 주도해서 누구의 카드를 기준으로 결과를 정산할지 모든게 꼬여버릴수 있기 때문에,

오로지 결과 정산의 행동과 책임은 `Dealer`에게 집중시키는것이 맞다고 판단하였습니다.

2022-12-31 10:16 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +        )
저의 생각은 `Cards` 객체 2개를 서로 비교해서, 결과를 내는거에 대한 책임과 역할을 `PlayerResult`혹은 `Dealer` 쪽에 맞쳐줘야 된다고 생각합니다.

`Player`객체는 오로지 결과를 수신하는 쪽만 가능해야된다고 생각합니다. 

따라서 `Player`객체에서 결과를 계산하고 하는건 설계를 어떻게 하냐에 따라 다르게 생각할수 있다고 생각합니다.

2022-12-31 10:24 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +        )
결과를 산출하는 로직을 오로지 PlayerResult 쪽에만 담아 두기 위함입니다.

2022-12-31 10:24 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/card/vendor/CardVendor.kt
> +    fun drawPlayerFirstTwoCards(): Cards
넵 리뷰 감사합니다.

반영하겠습니다.

2022-12-31 10:24 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/Blackjack.kt
>          }
리뷰 감사합니다.

반영하겠습니다.

2022-12-31 10:24 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +class Dealer(
리뷰 감사합니다.

반영하겠습니다.

2022-12-31 10:25 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +    private fun hit(): Unit = hit(drawCard())
리뷰 감사합니다. 반영하겠습니다.

2022-12-31 10:25 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/result/PlayerResult.kt
> +enum class PlayerResult {
딜러 또한 추상적으로 플레이어라고 본다는 설계였지만,

리뷰 감사합니다.

말씀대로 구분 지어 주는게 좋을거 같네요.

2022-12-31 10:25 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/result/PlayerResult.kt
> +            return if (playerCards.isBust())
리뷰 감사합니다.
반영하겠습니다.

2023-01-02 05:57 UTC, ohgillwhan approved these changes
안녕하세요!
몇가지 리뷰 남겼는데, 확인 부탁드립니다! 다음 step에서 적용 부탁드려요

2023-01-02 05:57 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/Blackjack.kt
> +    fun notFinishedPlayers(): Players = players.notFinishedPlayers()
`get`이 붙어야 정확하게 표현될것 같네요.

2023-01-02 05:57 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/Blackjack.kt
>              false -> acceptStayFrom(player)
```suggestion
            true -> player.hit(dealer.drawCard())
            false -> player.stay()
```

2023-01-02 05:57 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/Blackjack.kt
>              false -> acceptStayFrom(player)
`player`에게 `hitOrStay` 메서드를 만들어도 되겠네요~

2023-01-02 05:57 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/CardHolder.kt
> +    fun isFinished() = state.isFinished
리턴 반환타입 명시 부탁드립니다!

2023-01-02 05:57 UTC, ohgillwhan commented on src/main/kotlin/blackjack/domain/player/Players.kt
> +    fun notFinishedPlayers(): Players = players.filter { it.isNotFinished() }.toPlayers()
`get` 이 붙어야 할것 같네요!

2023-01-02 05:57 UTC, merged

2023-01-02 06:04 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/Blackjack.kt
> +    fun notFinishedPlayers(): Players = players.notFinishedPlayers()
리뷰 감사합니다.

반영하겠습니다.

2023-01-02 06:04 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/CardHolder.kt
> +    fun isFinished() = state.isFinished
리뷰 감사합니다.

반영하겠습니다.

2023-01-02 06:04 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/player/Players.kt
> +    fun notFinishedPlayers(): Players = players.filter { it.isNotFinished() }.toPlayers()
리뷰 감사합니다.

반영하겠습니다.

2023-01-02 06:07 UTC, rolroralra commented on src/main/kotlin/blackjack/domain/Blackjack.kt
>              false -> acceptStayFrom(player)
이부분은 결국 실제로 `hit`할 경우에는

`Blackjack`객체 내부에 있는 `dealer`에게 카드를 한장 뽑은 다음에, 그 카드를 전달해줘야 하기 때문에,

`player`객체가 모든 행동을 취할수 없을것으로 판단됩니다.

만약 되게끔 하려면 결국 `player::hitOrStay`메서드에 `isHit`과 `dealer`객체를 넘겨줘야 하므로,

전반적인 `blackjack`객체에서 어떤 `player`가 hit 할지 stay할지 처리해주는 메서드로써 현재로도 충분하지 않을까  생각됩니다.