3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #404
Opened 2023-01-15 13:18 UTC by 0923kdh

2023-01-15 13:20 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/Judgment.kt
> +                else -> throw IllegalStateException("게임 결과를 판별하는 중 에러가 발생했습니다.")
해당 코드는 코드의 순서에 따라 버그를 발생시킬 수 있는 잠재적인 위험 요소가 있어요. 코드조건에 우선순위가 있다는걸 코드를 작성하는 사람이 아니면 처음에 파악하기가 어려울 것 같은데, 이런 부분은 어떻게 해결할 수 있을까요 ?

2023-01-18 15:00 UTC, namjackson requested changes
안녕하세요 다희님! 
승패에 대한 테스트 케이스 작성 👍 👍 
몇가지 고민할법한 코멘트 드렸으니, 확인해주세요! 
변경사항 적용 후, 리뷰요청해주세요!

2023-01-18 15:00 UTC, namjackson commented on src/main/kotlin/blackjack/domain/Judgment.kt
> +                else -> throw IllegalStateException("게임 결과를 판별하는 중 에러가 발생했습니다.")
else -> JudgmentResult.DRAW  (블랙잭에는 무승부도 존재합니다! )

도메인 상 코드의 순서가 중요한건 어쩔수 없는거 같아요! 

다만, 복잡해진 함수의 복잡도는 줄일수 있을 거 같아요.
 **( 요구사항 : 함수(또는 메서드)의 길이가 15라인을 넘어가지 않도록 구현한다.)**

승패의 결정하는 역할은 Player에게 위임해주면 어떨까요?
dealer의 score를 받아서 PlayerResult를 리턴하도록 Player 객체 전달하는 방법도 좋을거같아요!

2023-01-18 15:00 UTC, namjackson commented on src/main/kotlin/blackjack/domain/Judgment.kt
> +                else -> throw IllegalStateException("게임 결과를 판별하는 중 에러가 발생했습니다.")
모든 조건문마다, getScore()가 실행되어 성능상에도 좋진 않은거 같아요!
Score라는 클래스를 만들어보면 어떨까요?
+
질문주신, 
수업시간에 강의해주신 재성님의 피드백처럼 
stateful한 객체로 만들면 조금 덜 복잡해질수 있을거 같아요! 😄

2023-01-18 15:00 UTC, namjackson commented on src/main/kotlin/blackjack/common/Policy.kt
> +    const val DEALER_INIT_MAX_SCORE = 16
개인적인 의견입니다! 
Policy로 정의해주어도 좋지만,
프로그램이 복잡해지면, 많은 상수가 생기게 되는데, 
관리하기가 까다로워진다고 생각이 들어요! 

Player.INITIAL_CARD_COUNT , DEALER.INIT_MAX_SCORE , Participant. BUST_SCORE 
위처럼 각각이 필요한 곳에서 상수를 선언하여 관리하는 방식은 어떠세요?

2023-01-26 14:18 UTC, 0923kdh commented on src/main/kotlin/blackjack/common/Policy.kt
> +    const val DEALER_INIT_MAX_SCORE = 16
음, 모든 상수를 지금처럼 관리하지는 않아요. 프로그램 전반적으로 중요한 정책이라고 생각되는것들은 지금처럼 관리하고, 프로그램내에서 사용 범위가 적을 경우엔 필요한 곳에서만 선언해서 사용하는걸 선호하는 편이에요!

2023-01-26 14:30 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/BlackJackMachine.kt
>              repeat(INITIAL_CARD_COUNT) {
기능 요구사항 명세에
`딜러는 처음에 받은 2장의 합계가 16이하이면 반드시 1장의 카드를 추가로 받아야 하고, 17점 이상이면 추가로 받을 수 없다.` 라고 나와있어 딜러도 처음에 2장을 받을 수 있도록 했어요.

2023-01-26 14:44 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/Card.kt
> +        return score + denomination.score
그렇네요! 반영했어요

2023-01-26 14:45 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/BlackJackMachine.kt
> +    private val participants: List<Participant>,
반영했어요!

2023-01-26 14:45 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/BlackJackMachine.kt
> +        dealerCardResultFunc: (dealer: Dealer) -> Unit,
나눠서 실행할 수 있도록 했어요! 메서드 하는일이 더 명확해졌네요!

2023-01-26 14:48 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/Player.kt
> +        return !((super.isBust() || super.isBlackJack() || super.isMaxScore()))
추후에 isBust(), isBlackJack(), isMaxScore() 내부적으로 판단 조건이 바뀔수도있고, 조금 더 명시적으로 하고싶어 이렇게 작성했어요!

2023-01-26 14:49 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/Judgment.kt
> +                else -> throw IllegalStateException("게임 결과를 판별하는 중 에러가 발생했습니다.")
승패의 결정하는 역할은 Player에게 위임하는것도 고민했던 방법 중 하나인데요. 승패를 판단하는 객체를 하나 만드는편이 더 좋겠다 싶어 지금처럼 작업해보았어요!

2023-01-26 14:51 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/Judgment.kt
> +                else -> throw IllegalStateException("게임 결과를 판별하는 중 에러가 발생했습니다.")
3단계 진행하면서 score라는 클래스를 만들어서 관리하는것도 고려해보았는데요. 이렇게되면 score 가 상태를 가지게 되면서 점수가 의도치 않게 변경이 될 수 있을거라 생각했고, 그래서 지금과 같은 방향으로 작업했어요. getScore()가 여러번 실행되는건 맞지만, 성능에 영향을 줄 만큼 긴 메서드가 아니라고 생각해요!

2023-01-26 14:54 UTC, 0923kdh commented on src/main/kotlin/blackjack/domain/Judgment.kt
> +                else -> throw IllegalStateException("게임 결과를 판별하는 중 에러가 발생했습니다.")
요구사항에 비기는 상황은 명시되어있지 않아, 이처럼 작성했어요. 비기는 상황까지 꼭 고려하여 작업해야하는 부분일까용?

2023-02-05 02:03 UTC, namjackson approved these changes
안녕하세요 다희님

피드백 반영 잘해주셨네요 고생하셨습니다! 
추가로 참고하실만한 코멘트 남겼으니, 다음 미션 진행시 참고해주세요!
블랙잭 마지막 단계도 화이팅입니다!

2023-02-05 02:03 UTC, merged