Jihoon/step 3
next-step/kotlin-blackjack pull request #405
Opened 2023-01-18 12:20 UTC by hojihun5516

안녕하세요 리뷰어님! 
새해복 많이받으세요 ~ 

user라는 추상클래스를 사용했습니다
이 과정에서 player클래스 내부에서 input을 받게 됐는데 별로 좋은 방법이 아닌것 처럼 느껴져요 (테스트 어려움으로 인해)
좋은 방법이 있을까요??

2023-01-21 02:08 UTC, BeokBeok requested changes
이전 단계 피드백과 블랙잭(딜러) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-01-21 02:08 UTC, BeokBeok commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    }
print와 관련된 내용은 뷰와 관련된 내용이에요.
domains 패키지에 있는 클래스들은 view와 관련된 의존성을 갖지 않도록 코드를 개선해보면 어떨까요? (이하 관련 내용 동일)

2023-01-21 02:08 UTC, BeokBeok commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    }
게임 점수의 상태값을 매번 추가하도록 되어 있네요.
게임 점수의 상태는 결국 게임이 다 끝나고 마지막에 보여주고 있으니, 상태를 한가지만 관리하도록 개선해보면 어떨까요? (이하 관련 내용 동일)

2023-01-21 02:08 UTC, BeokBeok commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    fun isOver21(): Boolean {
```suggestion
    fun isOverBlackjack(): Boolean {
```
21이라는 단어보다는 Blackjack 이라는 단어를 사용하는 것이 더 가독성이 좋아요.

2023-01-28 13:41 UTC, hojihun5516 commented on src/main/kotlin/blackjack/GameRule.kt
> +    fun initUsers(playerNames: List<String>): Gamers {
그렇네요! 
게임규칙이라는 클래스에서 `유저초기화` 라는 메서드 보다는 `initGame`이란 메서드가 더 올바르겠네요

감사합니다

2023-01-28 13:41 UTC, hojihun5516 commented on src/main/kotlin/blackjack/ResultCalculator.kt
> +        val players = users.getPlayers()
지금 구조가 딜러와 플레이어는 `summedCardNumbers`라는 변수로 자신 카드의 합을 갖고있습니다.
그래서 말씀하신 방향으로 설계가 되어있다고 생각합니다.
제가 놓친부분이 있을까요??

2023-01-28 13:41 UTC, hojihun5516 commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    }
네! 서비스로직에서 분기처리를 하도록 변경했습니다

감사합니다

2023-01-28 13:42 UTC, hojihun5516 commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    }
딜러같은 경우는 `player`와의 승, 무, 패 에 대한 기록을 각각 갖고있어야합니다.
그래서 mutableList로 접근하게 됐습니다.
승, 무, 패를 갖고있는
`private win `
`private lose `
`private draw `

이렇게 관리해보라는 말씀이신가요??

2023-01-28 13:42 UTC, hojihun5516 commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    fun isOver21(): Boolean {
감사합니다~

2023-01-30 14:48 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-01-30 14:48 UTC, BeokBeok commented on src/main/kotlin/blackjack/ResultCalculator.kt
> +        val players = users.getPlayers()
summedCardNumber가 User 클래스에 있었군요!
잘 구현해주셨습니다! 👍

2023-01-30 14:48 UTC, BeokBeok commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    }
아무래도 블랙잭 게임이 딜러가 플레이어의 점수를 판단해서 승패 여부를 판단해주므로 이와 같이 작성하신 것으로 보입니다.
제가 의도한 것은, 딜러와 플레이어의 정보를 가지고 승패 여부를 판단해주는 클래스를 만드는 것을 의도하였습니다.
이렇게 하게 되면, 게임의 룰이 변경되었을 때 딜러와 플레이어를 수정하지 않고 분리한 클래스만 수정하면 됩니다.
그리고 딜러와 플레이어는 각각 User를 상속받고 있으므로, 딜러와 플레이어를 하나의 타입으로 작성할 수 있을 것 같아요.

2023-01-30 14:48 UTC, BeokBeok commented on src/main/kotlin/blackjack/GameRule.kt
> +        val dealer = initUser(playerName = "딜러", isDealer = true)
만약 딜러의 이름을 입력받을 수 있게 변경된다면, 이 로직은 어떻게 개선해보면 좋을까요?

2023-01-30 14:48 UTC, BeokBeok commented on src/main/kotlin/blackjack/GameRule.kt
> +import blackjack.views.Output.printHaveCards
GameRule이라는 클래스명만 봤을 때에는, 게임의 규칙을 관리하는 것으로 보이므로 domain의 성격에 가까워보여요.
domain에 view의 의존성을 가지게 되면, view가 변경될 때마다 영향을 받게 돼요.
domain에는 view의 의존성을 가지지 않도록 코드를 개선해보면 어떨까요?

2023-01-30 14:48 UTC, BeokBeok commented on src/main/kotlin/blackjack/domains/participants/Gamers.kt
> +import blackjack.views.Output.printSummedCards
domain은 view에 의존성을 가지지 않도록 코드를 개선해보면 어떨까요? (이하 관련 내용 동일)

2023-01-30 14:48 UTC, BeokBeok commented on src/test/kotlin/blackjack/ScoreCalculatorTest.kt
> +        val blackJack = 21
21이라는 숫자가 계속해서 반복되고 있습니다.
21이라는 숫자는 "블랙잭"을 의미하므로, 이를 정의해놓고 활용해보면 어떨까요?

2023-01-30 14:48 UTC, merged

2023-02-01 10:23 UTC, hojihun5516 commented on src/test/kotlin/blackjack/ScoreCalculatorTest.kt
> +        val blackJack = 21
그러네요!
등록을 해놨는데도 제가 테스트코드에서 사용을 안했네요 

감사합니다!

2023-02-01 10:36 UTC, hojihun5516 commented on src/main/kotlin/blackjack/GameRule.kt
> +        val dealer = initUser(playerName = "딜러", isDealer = true)
외부에서 주입받도록 해봤습니다!

2023-02-01 10:54 UTC, hojihun5516 commented on src/main/kotlin/blackjack/domains/participants/Dealer.kt
> +    }
현재 사용중인 `ResultCalculator`가 있습니다!
다른걸 이야기 하신걸까요??

2023-02-01 11:58 UTC, hojihun5516 commented on src/main/kotlin/blackjack/GameRule.kt
> +import blackjack.views.Output.printHaveCards
네! 감사합니다

2023-02-01 11:58 UTC, hojihun5516 commented on src/main/kotlin/blackjack/domains/participants/Gamers.kt
> +import blackjack.views.Output.printSummedCards
네! 감사합니다