Step2 - 블랙잭
next-step/kotlin-blackjack pull request #442
Opened 2023-06-21 10:02 UTC by konempty

리뷰 잘부탁드려요~!

2023-06-21 12:28 UTC, laco-dev requested changes
블랙잭 미션 고생하셨습니다!

전달 드린 내용과 반영에 따라 구조적으로 변경이 될 수 있어서 핵심 로직 위주로 의견을 드렸습니다.
이후 반영 과정에 따라 다른 부분에 대해서도 같이 피드백을 남기도록 하겠습니다. 🙏🏻

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/CardNumber.kt
> +sealed interface CardNumber {
카드 번호를 인터페이스를 이용한 sealed 형태로 구현을 해 주셨네요! 👍🏻 
독특한 구현 방식이라 좋았습니다.

그런데 플레잉 카드 게임에는 끗수 (Denomination) 이라고 부르는 카드의 숫자는 총 13가지가 존재합니다.
모양 (Suit)와 마찬가지로 enum class로 관리하는 것과 비교하면 어떤 차이가 있을까요?

```kotlin
enum class Denomination(point: Point) {
   Ace,
   One,
   Two,
   ...
   Jack,
   ...
)
```

의견에 따라 카드 번호에 대한 역할 관련 피드백을 다르게 전달드리려고 합니다 🙏🏻

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Card.kt
> +}
모양을 출력하는 방식에 대해서는 UI의 관심사입니다.

가령 스페이드를 이렇게 출력하면 도메인 코드를 모두 수정해야 합니다 `♤`
출력을 결정하기 위한 적절한 곳으로 이동 해주세요!

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    }
마찬가지로 다른 UI 출력 코드도 올바른 위치로 만들어주세요!

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/util/PointCalculator.kt
> +object PointCalculator {
점수를 계산하는 로직은 블랙잭 게임의 핵심 비즈니스 로직입니다.
유틸 패키지가 아닌 도메인에서 계산할 수 있도록 해야 합니다.

그렇다면 점수를 계산하기 위한 역할을 누가 구현을 해야 좋을까요?
아래는 블랙잭 점수를 계산하기 위한 한 가지 Flow 입니다. 내용을 참고해서 올바른 위치를 고민 해주세요

```
1. 카드 한 장의 점수는 끗수의 점수로 결정된다.
2. 카드가 여러장이라면 카드들의 점수를 합산한다.
3. 만약 카드 목록에 에이스 카드가 있을 때, 보너스 점수 10점을 더하더라도 21점 보다 낮다면 보너스 점수를 획득한다.
4. 그렇지 않은 경우 에이스 카드는 1점으로 계산된다.
```

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +data class Deck(private val cardList: LinkedList<Card>) {
코틀린으로 미션을 진행하는 만큼 자바의 컬렉션이 아닌 코틀린 컬렉션으로 구현 해 보면 어떨까요?

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +data class Deck(private val cardList: LinkedList<Card>) {
코틀린의 Backing Property라는 개념을 찾아 보시고 생성자로 가변 컬렉션이 노출되면 어떤 위험성이 있는지 확인 해보세요!

https://kotlinlang.org/docs/properties.html#backing-properties

힌트 : 방어적 복사

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    fun getCard(): Card = checkNotNull(cardList.poll()) { EMPTY_DECK_ERROR_MESSAGE }
getCard()라는 이름이 카드를 한 장 뽑는다는 의미를 충분히 전달하고 있을까요?

카드를 뽑는다는 의미에 적절한 함수 이름은 어떤 게 있을까요?

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/BlackjackGame.kt
> +        return Deck(cardList)
실제 카드게임을 한다고 생각해보세요.
하나의 카드 뭉치를 가지고 서로 다른 사람들이 카드를 뽑습니다.
그리고 사람들은 각자의 카드를 손에 모아 카드들로 가지고 있습니다.

요기서 말하는 카드뭉치와 카드들이 힌트가 될 수 있습니다.
잘 파악 하셨다면 lateinit으로 만들어지는 대신 생성자를 활용 할 수 있을거에요

```
블랙잭 게임을 하기 위해서는 하나의 카드 뭉치와 참가자들이 필요하다
게임을 시작하면 참가자들은 카드 뭉치에서 카드를 두 장씩 받는다
...
```

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/BlackjackGame.kt
> +) {
블랙잭 게임은 컨트롤러일까요? 도메인 모델일까요?

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Users.kt
> +    }
중복된 이름을 가지지 않도록 하는 것은 이미 생성자를 통해 Set 자료구조로 받고 있습니다.
사용하는 측에서 자연스럽게 중복되지 않구나 생각 할 수 있는데 List라는 부생성자가 중복되면 오류를 발생할 것이라는 것을 예측하기가 쉬울까요?

2023-06-21 12:28 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Users.kt
> +data class Users(private val userList: Set<User>) : Iterable<User> {
코틀린의 by 위임을 사용한다면 별도의 오버라이드를 하지 않고 작성할 수 있습니다.
```kotlin
class Users(private val userList: Set<User>): Interable<User> by userList
```

2023-06-22 08:59 UTC, konempty commented on src/main/kotlin/blackjack/domain/Card.kt
> +}
오호 그런 의도로 바라본다면 요 Suit이라는 Enum클래스가 카드 구분자 역할과 출력에 필요한 정보를 가지는 역할, 
요렇게 두개를 한다고 볼수 있겠군요..?
그런 의도는 정말 생각도 못해봤네요 ㅋㅋㅋ 감사합니다

2023-06-22 10:02 UTC, konempty commented on src/main/kotlin/blackjack/domain/Users.kt
> +    }
으흠 저도 그게 고민이긴 했어요 
Set이 있는 생성자만 쓰자니 중복이 있으면 안된다 라는 지식은
Users의 도메인의 종속적인 내용인데 실제로 그걸 처리하는건 외부의 사용처라는게 마음에 걸려서
List를 사용하는 생성자까지 쓰게 되었네요 ㅠㅠ

중복체크를 외부에 위임하는게 더 올바른 코드 일까요..?

2023-06-23 04:59 UTC, konempty commented on src/main/kotlin/blackjack/domain/Users.kt
> +data class Users(private val userList: Set<User>) : Iterable<User> {
오호 일급컬렉션은 외부에 불필요한 노출을 막기위해 쓴다고 생각하는데 위임을 하면 불필요한 메소드 혹은 필드 노출이 일어나기도 해서
일급 컬렉션으로서의 장점을 하나 잃게 된다고 생각해서 개인적으로는 일급컬렉션에서 Delegate쓰는걸 꺼리는데 
Iterable 메소드만 노출한다면 괜찮을수도 있겠네요! 👍

2023-06-23 05:02 UTC, konempty commented on src/main/kotlin/blackjack/util/PointCalculator.kt
> +object PointCalculator {
오호 그렇네요 PointCalculator는 비즈니스 로직을 많이 가지고 있으니 Util의 성격보다는 도메인이 더 잘 어울리겠군요!

2023-06-23 13:20 UTC, laco-dev requested changes
피드백 반영 잘 해주셨습니다.
기준을 맞춰서 알려주셔서 그에 맞게 전체적인 구조를 다시 피드백 드려 보았습니다.

충분히 고민 해 보시고 도전 해보세요! 💪🏻

2023-06-23 13:20 UTC, laco-dev commented on src/main/kotlin/blackjack/util/CardSelector.kt
> +    abstract val deck: Deck
카드 셀렉터의 인터페이스가 Deck에서 카드를 뽑아오는지 다른곳에서 카드를 뽑아오는지는 구현체의 관심사이지 않을까요?

실제로 외부에서는 deck을 사용하지 않고 있어요.

drawCard() 를 추상함수로 만든다면 보다 테스트 환경에서도 간단하게 만들어 볼 수 있을 것 같아요
```kotlin
interface CardSelector {
   fun drawCard(): Card
}

class Deck(...): CardSelector {
   override fun drawCard(): Card = { ... }
}

// Test
class FixedCardSelector(private val card: Card): CardSelector {
   override fun drawCard(): Card = card
}
```

2023-06-23 13:20 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +package blackjack.domain
블랙잭 게임이 컨트롤러로 이동했기 때문에 패키지도 같이 맞춰 주시면 됩니다.

2023-06-23 13:20 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +                game.users.first().deck.size shouldBe BlackjackGame.INITIAL_DECK_SIZE
`INITIAL_DECK_SIZE` 라는 값은 블랙잭 게임에서 내부적으로 결정되는 규칙입니다.
그렇기 때문에 테스트 코드 외에서는 아무곳에서도 사용이 되지 않는데요.

이처럼 테스트 코드에서만 사용되는 코드는 private으로 감춰도 동작하도록 만들 수 있어야 합니다.
기능을 직접 테스트 하는 것이기 때문에 하드코딩 형태로 작성해도 문제 없습니다.

컨트롤러의 테스트라면 프로그램의 규칙이 테스트 이름으로 그대로 드러나도록 작성 해 볼 수 있습니다
```kotlin
// given : 유저가 2명일 때
// when : 게임을 시작하면
// then : 모든 유저는 카드 2장을 가지고 있다
```

2023-06-23 13:20 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +        `when`("해당 게임에서 유저가 히트를 하지 않으면") {
`when` 의 경우 코틀린 예약어이기 때문에 백쿼터가 필요한데요
대문자 When으로 사용할 수 있습니다!

2023-06-23 13:20 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +        }
아래 내용은 반영하지 않아도 괜찮습니다.
참고용으로 남긴 코드입니다

위 코드는 블랙잭 게임을 준비하면서 유저를 같이 만들어 줄 수 있다면 아래와 같이 표현 할 수 있겠네요!
블랙잭 게임이 컨트롤러와 게임이라는 도메인 로직을 모두 가지고 있는데 궁극적으로는 컨트롤러, UI 없이도 블랙잭 게임이 동작하도록 만드는 목표를 가지고 있습니다.

```kotlin
// given
val user = User("홍길동",  Card(Suit.Spade, 10)
val users = Users(user)
val selector = CardSelector (Card(Suit.Diamond, 10))
val game = BlackjacmGame(users, selector)

// when
game.dealCards()

// then
user.totalScore equals 20
```

2023-06-23 13:20 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/DeckTest.kt
> +        }
Kotest로 작성하니 테스트가 글 읽듯이 자연스럽게 읽히네요! 👍🏻

2023-06-23 13:20 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    private val cardQueue: ArrayList<Card> = ArrayList(cardList.map { it.copy() })
ArrayList 대신 MutableList를 사용 해 보면 어떨까요?

2023-06-25 11:00 UTC, konempty commented on src/main/kotlin/blackjack/domain/Users.kt
> +    }
아핫 ㅋㅋㅋ 그렇네요

2023-06-25 11:00 UTC, konempty commented on src/main/kotlin/blackjack/domain/Users.kt
> +data class Users(private val userList: Set<User>) : Iterable<User> by userList {
으흠... 리뷰해주신 내용이 잘 이해가 안되서 다시 질문드려요..! ㅠㅠ
> 이 기능을 구현하기 위해서 여러가지 방법이 있겠지만 UserNames를 정적 팩토리 메소드를 통해 생성자로 전달받는 방법도 있고
> init 블록에서 검사하는 방법도 있고 여러가지 가능성이 있습니다.

요렇게 만드려면 결국 중복을 저장할수 있는 List<User>로 받아서 내부적으로 중복 체크를 해야한다는 말씀이신것 같은데
그렇다면 이전에 리뷰 주신
> List라는 부생성자가 중복되면 오류를 발생할 것이라는 것을 예측하기가 쉬울까요?

 라는 리뷰와 상반되는 내용인데 
호옥시 좀더 자세하게 설명 가능하실까요..?

2023-06-25 11:02 UTC, konempty commented on src/main/kotlin/blackjack/io/ResultView.kt
> +        }
헛!! ㅋㅋㅋ 조심한다고 조심했는데 인덴트가 초과된 부분이 있군요 ㅋㅋㅋ

2023-06-25 11:27 UTC, konempty commented on src/main/kotlin/blackjack/util/CardSelector.kt
> +    abstract val deck: Deck
오호 제 의도와 많이 다른 리뷰네요 ㅋㅋㅋ
저는 ```카드는 무조건 덱에서 온다, 하지만 덱이 어떻게 생겼는지는 모른다```라는걸 의도 했는데
리뷰어님은 ```카드의 출처조차 몰라도 된다```라는 의도 이시군요!
요건 리뷰어님 의견이 좀더 추상화가 잘된것 같아서 마음에 드네요! ㅋㅋㅋ

2023-06-25 12:00 UTC, konempty commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +                game.users.first().deck.size shouldBe BlackjackGame.INITIAL_DECK_SIZE
앗..! ```INITIAL_DECK_SIZE ```는 유저 생성시 유저 패를 초기화 할때도 사용을 하는 값인데
해당 값을 private로 숨기고 테스트에서는 하드코딩하는게 좋다라는 말씀이실까요...?ㅎㅎ

2023-06-25 12:02 UTC, konempty commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +        `when`("해당 게임에서 유저가 히트를 하지 않으면") {
아핫 ㅋㅋㅋ 요거 매크로를 지정해놔서 저는 쓸때 백쿼터가 들어가 있어도 편한데 매번 리뷰어분들이 리뷰주시네요 ㅋㅋ
역시 대문자로 고쳐놔야겠네요

2023-06-25 14:40 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Users.kt
> +data class Users(private val userList: Set<User>) : Iterable<User> by userList {
이전에는 부생성자에서 검사하는 것으로 판단을 했는데요.
아마 이 부분에서 오해가 되지 않았을까 합니다.

결국 부생성자를 주생성자로 만들면서 검증이 꺠질 수도 있어서 조금 애매하네요!!
정적 팩토리 메소드로 하는 방법이 있을 것 같은데, 우선은 넘어가도 될 것 같습니다!

```kotlin
class UserNames(value: Set<String>) {
   constructor(value: List<String>): this(value.toSet())


   companion object {
      fun from(value: List<String) { verify }
   }
}
```

2023-06-25 14:42 UTC, laco-dev commented on src/main/kotlin/blackjack/util/CardSelector.kt
> +    abstract val deck: Deck
이름이 CardSelector라서 위와같이 생각한 것 같습니다!

Deck이 추상화가 되지 않아도 충분히 구현은 가능 할 거에요!

2023-06-25 14:43 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +                game.users.first().deck.size shouldBe BlackjackGame.INITIAL_DECK_SIZE
하드코딩을 의도하기는 했습니다.
현재는 단순히 상수값을 그대로 사용해서 2를 반환하지만 내부적으로 로직을 포함해서 결과적으로 2가 나온다는 상황이 만들어지면 상수는 사라지게 됩니다.

그러면 테스트 코드도 같이 수정이 필요하기 때문에 내부 구현과 상관없이 결과에 집중하기 위함입니다.

2023-06-25 14:43 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/BlackjackGameTest.kt
> +        `when`("해당 게임에서 유저가 히트를 하지 않으면") {
아뇨! 알고 계시다면 바꾸지 않으셔도 괜찮습니다.
저는 백쿼터 좋아해요

2023-06-25 14:59 UTC, laco-dev approved these changes
피드백 반영하느라 정말 고생 많으셨습니다.
이전보다 훨씬 구조가 좋아지는게 보여서 좋았습니다.

이후 미션을 진행하면서 구조가 다시 변경될 수 있기에 간단한 의견 몇가지 남겨드렸습니다.

다음 미션에서는 딜러와 유저 사이의 어떤 부분을 재사용 하고 역할로 잡을 수 있을지 고민 해 보 시면 됩니다.

2023-06-25 14:59 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    }
`cardsList.toMutableList()` 로 충분합니다!

2023-06-25 14:59 UTC, laco-dev commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +        println()
출력 관련한 기능은 ResultView에서 해야 하지 않을까요?

2023-06-25 14:59 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/CardNumber.kt
> +                )
~value 값을 enum이 가지고 있으면 어떨까요?~
```kotlin
enum class CardNumber(private val rawValue: Int) {
   ...
}
fun of(value: Int): CardNumber = values().find { ... }
```

그런데 value 값이 실제로 필요할까요? enum으로 되있어서 바로 생성이 가능하지 않을까요?

2023-06-25 14:59 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    }
포인트를 계산하기 위해서 결국 카드들을 모두 순회해야 하는데, PointCalculator에서 합을 반환해도 되지 않을까요?

2023-06-25 14:59 UTC, merged