Step3 블랙잭(딜러)
next-step/kotlin-blackjack pull request #475
Opened 2023-06-24 18:22 UTC by Wordbe

리뷰 감사합니다 :)

2023-06-25 07:00 UTC, saintbeller96 requested changes
안녕하세요!
블랙잭 미션 잘 구현해주셨습니다🙂
코드가 전반적으로 잘 작성되어 있어 리뷰하기 수월했어요💯
몇가지 피드백을 남겼는데 한 번 고민해보시고 다시 리뷰 요청 부탁드립니다!

2023-06-25 08:59 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Deck.kt
>      constructor(vararg cards: Card) : this(cards.toMutableList())
`DeckFixture` 만들어 보았습니다. 혹시 가짜 생성자는 무엇을 의미하나요?

2023-06-25 10:22 UTC, Wordbe commented on README.md
무승부를 고려하지 못했었네요 반영했습니다 ☺️🙏

2023-06-25 10:24 UTC, Wordbe commented on src/test/kotlin/blackjack/domain/DealerTest.kt
> +    }
`kotest-framework-datatest-jvm` 의 `withData` 의 경우 `FunSpec` 하에서 `context` 내부에서 사용하지 않으면 오류가 발생하더라구요. 그래서 `test` 를 사용하지 못했습니다 😢 이부분은 kotest 에서 업데이트가 필요한 부분인 것 같습니다.

2023-06-25 10:25 UTC, Wordbe commented on src/test/kotlin/blackjack/domain/ParticipantsTest.kt
> +    test("members") {
꼼꼼히 봐주셔서 감사합니다 반영했습니다 ☺️😀

2023-06-25 11:30 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Player.kt
> +    fun isWinner(dealerScore: Int): Boolean {
딜러를 받아오니 밖에서 하던일을 이 메소드 안에서 할 수 있게 되어서 응집도가 좋아진 것 같네요.
감사합니다 😃😀😊

2023-06-25 13:28 UTC, saintbeller96 commented on src/main/kotlin/blackjack/domain/Deck.kt
>      constructor(vararg cards: Card) : this(cards.toMutableList())
가짜 생성자는 말 그대로 임의로 정의한 생성자(사실은 함수)를 사용하는 방법인데요, 보통 top-level function을 사용해 함수를 생성자처럼 사용하고는 합니다🙂
저는 주로 테스트용 Fixture를 만들 때 많이 사용하고 있어요.
```kotlin
// test 모듈

fun Deck(vararg cards: Card): Deck = Cards(cards.toMutableList())

// 또는
fun deck(vararg cards: Card): Deck = Cards(cards.toMutableList())
```

2023-06-25 18:19 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Player.kt
> +        return score <= Cards.WINNING_NUMBER && score >= dealerScore
점수를 생성하니 점수가 할 수 있는 일이 많네요. 로직이 좀 더 응집된 효과가 있는 것 같아요. 감사합니다 👍😀 [19e3cce](https://github.com/next-step/kotlin-blackjack/pull/475/commits/19e3ccec0c2d455db96972f733eaee88d67d1f0c)

2023-06-26 10:24 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Participant.kt
> +    var burst: Boolean = false
참가자의 상태를 반영해봤습니다 😀
구체적인 상태는 좀 더 필요한 상황이 발생하면 반영해볼게요.

2023-06-26 12:53 UTC, saintbeller96 approved these changes
안녕하세요!
피드백 반영 잘 해주셨습니다👍
이번 단계는 Merge해도 될 것 같아요. 
다음 단계도 화이팅입니다💪

2023-06-26 12:54 UTC, merged