[🚀 2단계] - 블랙잭
next-step/kotlin-blackjack pull request #488
Opened 2023-06-25 17:46 UTC by jonghyunhub

안녕하세요 리뷰어님!
리뷰 진행이 늦었네요 🥲 
피드백 잘 부탁드리겠습니다 :)

2023-06-26 12:13 UTC, BeokBeok commented
프로그램을 실행해서 카드를 더 받기 위해 "y"를 입력해도 카드가 더 받아지지가 않네요.
이 부분 개선할 수 있을까요?

2023-06-26 12:21 UTC, jonghyunhub commented
안녕하세요 리뷰어님 :)

그 부분이 제가 만들면서 애매했던 부분이었는데요.

미션 기능 요구사항에는
"게임을 시작하면 플레이어는 두 장의 카드를 지급 받으며, 두 장의 카드 숫자를 합쳐 21을 초과하지 않으면서 21에 가깝게 만들면
이긴다. 21을 넘지 않을 경우 원한다면 얼마든지 카드를 계속 뽑을 수 있다."

라는 말이 적혀있어서 카드를 뽑을때 21이 넘으면 자동으로 종료하는 식으로 코드를 만들었습니다.
이 부분을 제외하고 만드는게 맞을까요?

[image: 스크린샷 2023-06-26 오후 9.20.38.png]



2023년 6월 26일 (월) 오후 9:13, Hyeonseok Kang ***@***.***>님이 작성:

> 프로그램을 실행해서 카드를 더 받기 위해 "y"를 입력해도 카드가 더 받아지지가 않네요.
> 이 부분 개선할 수 있을까요?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/next-step/kotlin-blackjack/pull/488#issuecomment-1607344153>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP7IDMOWKA4QZQLNUHIJ3NTXNF4IPANCNFSM6AAAAAAZTI3RLE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-26 12:37 UTC, BeokBeok requested changes
블랙잭 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/BlackJackApllication.kt
> +class BlackJackApllication {
```suggestion
class BlackJackApplication {
```
오타가 있네요. 😅

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/CardNumberCalculator.kt
> +        if (cardNumber == CardNumber.A) {
CardNumber가 Ace인지 아닌지를 판단하고 있네요.
CardNumber는 카드 번호와 관련된 책임을 가지고 있으니, CardNumber 클래스에서 Ace를 판별할 수 있도록 개선해보면 어떨까요?

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/CardNumberCalculator.kt
> +        const val ACE_MINIMUM = 1
```suggestion
        private const val ACE_MAXIMUM = 11
        private const val ACE_MINIMUM = 1
```
클래스 내부에서만 접근하는 상수값이라면, private 접근자를 붙여보면 어떨까요?

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Game.kt
> +            throw PlayerLoseException("${player.name}의 카드가 21을 넘었습니다.")
숫자 21이라는 조건이 변경된다면, 비즈니스 로직에는 변경할 수 있지만 에러를 출력하는 문구까지 챙기기는 어렵습니다.
조건이 변경되더라도 에러 문구도 같이 변경될 수 있도록 개선해보면 어떨까요?

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Player.kt
> +        }
```suggestion
        cards.addAll(drawCards)
```
addAll을 사용하시면 간단하게 전체 리스트를 추가할 수 있습니다.

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Player.kt
> +    }
함수명만 봤을 때에는 카드들을 얻을 수 있을 것이라 예상했지만, 실제로 리턴타입은 String이네요. 🤔 
또한, 이 함수의 사용처는 ResultView에서 사용하고 있네요.
즉, View에서 사용하기 위한 코드로 보입니다.
View와 연관된 코드는 View에서 처리해야하지 않을까요? 🤔

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Player.kt
> +            return playerList.toList()
방어적 복사 활용 👍

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/RuleChecker.kt
> +    fun checkSumOfCardNumbers(sum: Int): Boolean {
checkSumOfCardNumbers 함수는 합이 21 이하인지 체크하는 것으로 이해가 됩니다.
또한, 이와 비슷한 로직이 Game 클래스에 checkPlayerIsLose 함수로 구현해주신 것으로 보이는데요.
RuleChecker는 어떤 책임을 가지고 Game 클래스는 어떤 책임을 가질까요?
또한, 종현님은 클래스를 분리하는 기준이 무엇인지 궁금합니다!

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
Card 클래스에 카드 전체 리스트의 개수를 의미하는 상수를 정의해주셨네요. 👍 
다만, 이 상수값이 Card 클래스에 있는 것이 적합한지 의문이 됩니다.
카드 전체 리스트를 의미하는 Deck 클래스에 위치하는 것이 좋지 않을까요?

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/card/CardNumber.kt
> +    ONE(1),
```suggestion
    ACE(1),
```
카드 중에는 1이라는 것은 존재하지 않습니다.
기본적으로 Ace를 1로 사용하고 있으며, 조건에 따라 11이 됩니다. 🙏

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        repeat(2) {
숫자 2는 어떤 것을 의미할까요? 🤔

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/deck/DeckShuffleStarategy.kt
> +interface DeckShuffleStarategy {
전략 패턴 사용 👍

2023-06-26 12:37 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/deck/RandomDeckShuffleStrategy.kt
> +        deck.shuffle(Random(System.currentTimeMillis()))
```suggestion
        return deck.shuffled(Random(System.currentTimeMillis()))
```
파라미터의 타입이 MutableList로 되어있고, shuffle 함수를 통해서 원본을 변경하고 있네요.
원본을 변경하게 되면, 원본을 참조하는 곳에서 예상치 못한 동작을 하게 됩니다.
방어적 복사를 활용해서 원본을 손상시키지 않도록 개선해보면 어떨까요?

2023-06-26 22:05 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        repeat(2) {
매직 넘버 신경쓰면서 만들려고 했는데 제가 놓친 부분이 있었네요! 😅 
감사합니다 ✔️

2023-06-26 22:28 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
개인적으로 이런 부분이 정말 어려운것같네요.
만들때만 하더라도 카드 전체 숫자를 생각했을때 이것은 카드에 있으면 좋겠다는 생각이었는데.
지금 생각해보니 전체 카드의 갯수는 Deck에 속하는 성질이네요 ✔️

2023-06-26 22:31 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/card/CardNumber.kt
> +    ONE(1),
아하.. 그렇군요 ㅋㅋ... 룰이 생각보다 복잡해서 놓쳤던 것 같네요 감사합니다 ✔️

2023-06-26 22:43 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/CardNumberCalculator.kt
> +        if (cardNumber == CardNumber.A) {
카드에 적힌 숫자를 가지고 계산한다. => CardNumberCalculator
카드에 적힌 숫자를 판별한다. => CardNumber

이런식으로 책임을 나누고 

CardNumberCalculator가 계산을 한다.
각 카드에서 숫자를 읽을때 CardNumber에게 카드에 적힌 숫자를 주도록 판별한다.
라는 말씀이실까요~?

이런 포인트가 헷갈리네요!

로또 미션을 진행할때도 
로또 번호가 정의된 enum 클래스를 만들고
"로또 번호를 기반으로 로또 당첨금의 통계를 낸다." 라는 책임을 어디에 넣을까 고민했었습니다.

미션을 진행하면서 제가 느낀 바로는 

enum에 정의 되어 있는 값을 읽는다. ex) 로또 번호에 적힌 숫자를 판별한다.  카드에 적힌 숫자를 판별한다.
enum에 정의 되어 있는 값을 기반으로 새로운 값을 도출한다. ex) 로또 당첨 등수 통계를 낸다. 카드에 적힌 숫자의 합을 계산한다.

이런 기준으로 책임을 나누면 괜찮은 건지 궁금합니다!

2023-06-26 22:48 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/Game.kt
> +            throw PlayerLoseException("${player.name}의 카드가 21을 넘었습니다.")
이런 디테일이 중요하군요! 👍
감사합니다 🤗

2023-06-26 22:52 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/Player.kt
> +        }
addAll을 나중에 추가해서 이런 코드가 발생한것 같네요 🥲 
꼼꼼하게 코드를 점검해보는 습관을 만들어야겠습니다 ✔️

2023-06-26 23:25 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/RuleChecker.kt
> +    fun checkSumOfCardNumbers(sum: Int): Boolean {
미션을 진행하면서 책임을 나누는 작업에서 혼동스러운 부분이 많아서 이런 비슷한 리뷰를 여러번 받아왔는데요.
아직 이런 부분이 많이 어렵네요.

사실 솔직하게 말하자면 
제가 생각했을 때, 책임을 나누고 나눈 책임을 객체들에게 적절하게 분배하는 일이 
아직 저에게는 익숙하지 않고 낯선 작업이여서 이런 일이 생기는것 같아요 🥲

특히나, Game 객체 같은 핵심이 되는 객체에게 책임을 어느정도까지 주는 것이 맞을까? 
이런 부분이 더더욱 어렵게 다가오는것 같습니다.

맨 처음 미션을 받고 생각했을 때의 사고의 흐름을 간단하게 적어보자면

1. 블랙잭 게임이니까 이 게임을 관리하고 진행하는 책임을 가지는 Game 객체를 만들어야겠다.
2. 게임을 관리한다는 건 어떤거지?
3. 게임의 룰에 따라 플레이어들에게 카드를 나눠주는 역할을 게임에게 할당하면 되겠다!
4. 게임을 진행하다가 패배하는 플레이어가 나오면 종료하는것도 Game의 책임인거 같은데..?
5. 패배하는 플레이어의 조건을 검증하는것도 Game에게 주면 너무 많은것 같으니 이건 RuleCheck에게 나눠주자.

이렇게 생각하면서 만들었던것 같아요.
저만의 명확한 기준이 딱! 잡히면 좋을텐데 
평소에 책임을 적절하게 분배하는 연습을 안해서 그런지,
아직 그런게 확립이 안되어서 코드를 읽는 입장에서 애매한 부분들이 많이 생기는 것 같네요.

리뷰어님께서는 요구사항을 받았을때 그것을 기반으로 책임을 나누는 명확한 기준이 있으신지 궁금하네요 🙋

2023-06-27 00:32 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/Player.kt
> +    }
메서드 네이밍에 맞게 방어적 복사로 cards의 복사본만 리턴하고 
따로 출력은 View로 보내는게 맞겠네요 ✔️
감사합니다 ㅎㅎ

2023-06-27 01:19 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/deck/RandomDeckShuffleStrategy.kt
> +        deck.shuffle(Random(System.currentTimeMillis()))
이 부분은 잘 이해가 되지 않아서 질문 남겨봅니다~

제가 알기론 방어적 복사는 객체 내부의 특정 변수를 외부에서 마음대로 건드리지 못하도록 막으려는 의도로 하는것으로 아는데요
shuffleDeck 메서드를 Player의 shuffleDeck() 메서드에서만 호출하고 있고 Player 객체 생성시에 딱 한번만 호출하고 있습니다.
이 경우에도 방어적 복사를 적용하는게 맞을까요?

2023-06-27 12:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/CardNumberCalculator.kt
> +        if (cardNumber == CardNumber.A) {
> 각 카드에서 숫자를 읽을때 CardNumber에게 카드에 적힌 숫자를 주도록 판별한다.
라는 말씀이실까요~?

네 맞습니다!
너무 어렵게 생각하지 않으셔도 됩니다.
Ace는 CardNumber에서 정의하여 관리하고 있습니다.
그렇다면, 모든 클래스 중에서 Ace에 대해 가장 잘 아는 곳은 CardNumber이지 않을까요?
CardNumberCalculator에서는 카드번호에 대해서 계산만 잘하도록 구현하시면 됩니다! 😅

2023-06-27 12:42 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/deck/RandomDeckShuffleStrategy.kt
> +        deck.shuffle(Random(System.currentTimeMillis()))
종현님이 말씀하신 방법도 좋은 방법이며, 현 구조에서는 문제가 없어보입니다. 👍 
다만, 가급적이면 원본을 바꾸지 않는 방법으로 코드를 작성하시는 것을 지향하셨으면 좋겠어서 코맨트를 작성했습니다. 🙏 

원본을 바꾸게 되는 경우, 어떤 일이 발생하게 되는지 예시를 들어드리자면 아래와 같습니다.
```kotlin
// 이해를 돕기 위한 코드이니, 디테일이 부족한 부분은 양해부탁드려요!

class Test(val deck: List<Card>)

val deck = mutableListOf<Card>()
deck.add(Card(1))
deck.add(Card(2))
val test = Test(deck = deck)

RandomDeckShuffleStrategy().shuffleDeck(deck)
```
위 경우, `test.deck.first()`는 반드시 Card(1)일 것이라 장담할 수 있을까요? 🤔

2023-06-27 12:56 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-06-27 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/ui/InputView.kt
>          return false
소문자 y도 추가해주셨네요. 👍 
이렇게 대문자 소문자 둘 다 나열하실수도 있겠지만, lowercase를 사용하시면 하나의 조건문으로 해결하실 수 있어요!
```suggestion
        return playerAnswer.lowercase() == "y"
```

2023-06-27 12:56 UTC, BeokBeok commented on src/test/kotlin/blackjack/domain/CardNumberCalculatorTest.kt
> +    @ValueSource(strings = ["TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN"])
```suggestion
    @ValueSource(strings = ["A", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN"])
```
일반적으로 Ace도 숫자 계산은 카드 숫자를 기본으로 합니다! 💪

2023-06-27 12:56 UTC, BeokBeok commented on src/test/kotlin/blackjack/domain/CardNumberCalculatorTest.kt
> +    @ValueSource(strings = ["TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN"])
```suggestion
    @EnumSource(value = CardNumber::class)
```
EnumSource를 활용하시면 전체 enum을 불러올 수 있어요!

2023-06-27 12:56 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/card/CardNumber.kt
> +        private const val ACE_MINIMUM = 1
제가 의도한 것은 `if (cardNumber == CardNumber.A)` 이 로직만 CardNumber에서 처리하는 것을 의도했습니다. 😅

2023-06-27 16:12 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/RuleChecker.kt
> +    fun checkSumOfCardNumbers(sum: Int): Boolean {
요컨대, "클래스의 이름에 따라 책임이 달라지게 된다." 라는 거군요!
클래스의 이름에 따라 같은 로직을 가지고 있는 클래스임에도 어떤것은 되고 안되는지 여부가 달라지는게 신기하네요~
어쩐지 이름짓는게 제일 어려웠네요 😅

제가 책임을 나누었던 과정에 대해 질문을 주셔서 제 머릿속에 있던것들을 구체화해보고,
구체화한것을 표현해본 뒤 피드백을 받는 과정이 저도 매우 좋았습니다 👍

스스로 생각하는 과정에서 많이 배웠네요!
피드백 감사합니다 🤗

2023-06-27 16:44 UTC, jonghyunhub commented on src/test/kotlin/blackjack/domain/CardNumberCalculatorTest.kt
> +    @ValueSource(strings = ["TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN"])
요 부분은 조금 궁금한것이 있어서 질문 남겨봅니다~

요구사항에서 "예외로 Ace는 1 또는 11로 계산할 수 있으며" 라는 문구로 다른 숫자들과는 별개로 특수한 케이스로 지정을 하였는데요.
저는 이것을 구현할때 생각했던것으로

플레이어가 뽑은 카드가 ACE 일 때,
기존의 카드의 숫자합과 ACE의 숫자합이 21보다 작거나 같으면
"21에 최대한 가깝게 만들고 그 다음 카드를 안뽑으면 그만일 것! " 이라는 생각을 하지 않을까? 
라는 의도로 

새로 A를  뽑았을 때 "기존 숫자의 카드 합 + ACE <= 21" => (ACE = 11 )
새로 A를  뽑았을 때 "기존 숫자의 카드 합 + ACE > 21" => (ACE = 1 )

이런 사고의 흐름으로 계산 로직을 만들어보았습니다.

그래서 기존에는 A는 다른 숫자들과는 별개의 특수한 상황으로 보는것이 맞는 것 같아
 숫자들과는 구분지어서 테스트를 작성하였는데요~

리뷰어님의 의견을 들어보니 ACE도 숫자 계산을 해야하는군요!
이 부분도 일종의 테스트하기 어려운 로직인 것 같아 전략패턴을 적용해서 고쳐보았습니다.

서론이 길었는데요. 그래서 질문이 무엇인지 말씀을 드리면~!

요구사항에는 구체적인 명시가 없이 "1또는 11로 처리할 수 있다." 라는 말만 적혀있어서 개발자 입장에서 애매해지는 부분이 되는것 같아요.
기능 요구사항은 A를 만들어오라고 했는데 저는 A'을 만들어 버린 것일까요? 😅

리뷰어님은 ACE를 1 또는 11로 처리하실때 어떤식으로 구현하셨는지 궁금하네요! 
그리고 이런 요구사항이 애매한 상황에서 어떤식으로 대처하시는지 리뷰어님의 경험도 궁금합니다!

~~(질문 요구사항이 너무 많은가요? 🥲)~~

2023-06-27 17:13 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/card/CardNumber.kt
> +        private const val ACE_MINIMUM = 1
카드 숫자를 판별하는것만 따로 빼서 할당해야 하는군요! 👍

2023-06-28 11:53 UTC, BeokBeok commented on src/test/kotlin/blackjack/domain/CardNumberCalculatorTest.kt
> +    @ValueSource(strings = ["TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN"])
아마 블랙잭 게임 룰이 복잡해서 그런 것 같은데요. 😅 
현실 세계에서 게임을 한다고 가정해보면 많은 도움이 되더라구요.
그리고 객체는 서로 협력 관계임을 인지하고 계시면 좋을 것 같습니다.
플레이어마다 자신이 뽑은 카드 리스트를 가지고 있지만, 플레이어 스스로가 카드 점수를 알지는 못합니다. (블랙잭 게임을 모르는 사람도 있잖아요?)
그렇다면 플레이어는 언제 카드 점수를 알 수 있을까요?
보유한 카드들의 점수를 공개해야할 때이지 않을까요?
그 때에는 플레이어 입장에서 "내가 가지고 있는 카드 리스트를 알려줄테니 카드 점수가 몇점인지 알려줘" 라고 누군가(객체)에게 메시지를 보냅니다.
그러면 그 객체는 카드리스트만 보고 점수를 구해주면 됩니다.
바로 이 시점에 ACE가 1점인지 11점인지 판단해서 계산해주면 되지 않을까요? 😄 

> 그리고 이런 요구사항이 애매한 상황에서 어떤식으로 대처하시는지 리뷰어님의 경험도 궁금합니다!

저는 해당 기능이 어느 시점에 필요한지를 파악하고, 그 후에 구조를 잡는 것 같습니다. 😅 
이 부분은 시행착오를 겪으시면 될 것 같습니다!

2023-06-28 12:04 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-06-28 12:04 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        this.deck = deckShuffleStrategy.shuffleDeck(deck).toMutableList()
방어적 복사를 잘 활용해주셨네요. 👍 
지금도 좋지만, 가급적이면 새로운 컬렉션을 리턴하도록 개선해보면 어떨까요?
```suggestion
        return deckShuffleStrategy.shuffleDeck(deck).toList()
```

2023-06-28 12:04 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/DynamicProceedAceStrategy.kt
> +class DynamicProceedAceStrategy : ProceedAceStrategy {
ACE 점수를 적용하는 로직에 전략 패턴이 필요한지 고민해보시면 좋을 것 같습니다.
카드 리스트를 받아서 카드 리스트 중 ACE가 있는지 판단해서 조건에 따라 계산하도록 개선해보면 어떨까요?

2023-06-28 12:04 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/card/CardNumber.kt
>          }
👍 👍 👍

2023-06-28 12:04 UTC, BeokBeok commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
try-catch 문을 잘 활용해주셨네요. 👍 
특히 PlayerLoseException 을 만들어주신 부분이 참 좋았는데요.
Exception을 잘 만들어주셨지만, 실제로 Exception이 발생했을 때 단순히 println만 하는 것은 어떤 의미가 있을까요? 🤔 
에러를 좀 더 우아하게 처리해보면 어떨까요?

2023-06-28 12:04 UTC, merged

2023-06-28 12:36 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/DynamicProceedAceStrategy.kt
> +class DynamicProceedAceStrategy : ProceedAceStrategy {
저는 이것도 테스트하기 어려운 로직이라고 생각해서 따로 뺐었는데
리뷰어님의 말씀을 듣고 생각해보니 이 문제의 원인은 책임이 잘못된 객체에 할당되어서 생긴 것이네요!
감사합니다 👍

2023-06-29 15:03 UTC, jonghyunhub commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
요 부분은 궁금한게 있어서 질문 남겨봅니다~ 

여기서 try-catch문을 사용한 히스토리를 말씀드리면은

`private fun checkPlayerIsLoseByAskingPlayerWantToDraw(blackJackGame: BlackJackGame, it: Player) {
        try {
            askPlayerWantToDrawCard(blackJackGame, it)
        } catch (e: PlayerLoseException) {
            println()
        }
    }

    private fun askPlayerWantToDrawCard(blackJackGame: BlackJackGame, player: Player) {
        while (continueDrawingCards(player)) {
            drawPlayer(blackJackGame, player)
            blackJackGame.checkPlayerIsLose(player)
        }
        resultView.printPlayerCardList(player)
        println()
    }`

checkPlayerIsLoseByAskingPlayerWantToDraw() 메서드 내부에서 패배하는 플레이어가 나오는 경우를 구현하는 와중에
프로그래밍 제약 조건인" indent는 1로 유지한다." 를 지키기 위해 메서드 추출을 여러번 진행하는 과정을 거쳐서 제약 조건을 지키려고 하였습니다.

하지만, 메서드를 여러번 추출하고 보니 정작 "21이 넘으면 묻는것을 멈추고 호출한곳으로 되돌아가 다음 플레이어에게 물어본다." 중
"멈추고 호출한 곳으로 되돌아간다." 를 구현하기 위한 방법으로 
에러를 터트리고 try-catch문으로 잡는 방법밖에 떠오르지 못해서 이런식으로 구현을 하였습니다.

사실 try-catch문이 예상치 못한 예외가 발생하고 그것을 해결하기위해 사용하는 문법인데
저는 본래 용도와는 다르게 사용을 했습니다.

그래서 궁금한 사항 두가지를 적어보자면!

1. try-catch를 사용해서 이런식으로 구현을 해도 괜찮은 걸까요?
2. 이 상황에서 에러를 우아하게 처리하려면 어떻게 해야할까요? 아무리 생각해도 떠오르지 않네요 🥲

양질의 피드백 너무 감사합니다. 덕분에 많이 배우고 있습니다~! 🙇🏻‍♂️

2023-06-30 12:20 UTC, BeokBeok commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        }
> try-catch를 사용해서 이런식으로 구현을 해도 괜찮은 걸까요?

A. 코맨트에 작성했던 것처럼, 지금과 같은 방식이라면 좀 더 개선이 필요하지 않을까 싶습니다.
로또 미션의 마지막 단계를 진행하셨다면, 힌트에 아래와 같은 내용을 보셨을 것입니다.
>참고로 코틀린에서는 아래와 같이 예외 처리를 한다. 장기적으로는 아래와 같이 예외 처리하는 걸 연습해 본다.
논리적인 오류일 때만 예외를 던진다.
논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.
실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환한다.
일반적인 코틀린 코드에서 try-catch를 사용하지 않는다.

여기서, 말씀하신 현상들이 논리 오류인지 아닌지 고민해보셔야 합니다.
플레이어의 합이 21이 넘는 것이 오류가 아니라 규칙이 아닐까요?

> 이 상황에서 에러를 우아하게 처리하려면 어떻게 해야할까요? 아무리 생각해도 떠오르지 않네요 🥲

A. 위 답변과는 관계없이, 에러를 우아하게 처리하는 것에 대한 답변을 드리자면, 어떤 경우에 Exception을 던지시는지 고민해보시면 좋을 것 같습니다.
위에서 인용된 내용을 참고하자면, 코틀린에는 에러를 처리하는 방법이 두 가지가 있습니다.
코틀린에서의 에러를 처리하는 방법에 대해서 학습해보시면 좋을 것 같습니다.
관련해서 좋은 아티클을 하나 공유해드리겠습니다!

ref. https://medium.com/@galcyurio/kotlin%EC%97%90%EC%84%9C%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EB%B0%A9%EB%B2%95-48a5cd94a4e6