[블랙잭] step3
next-step/kotlin-blackjack pull request #506
Opened 2023-06-27 16:43 UTC by jinyoungchoi95

안녕하세요 현구님:)

이전 리뷰에 대해서 궁금한점이 있어 여기에서 이어서 적어두겠습니다 :)

> name 에 equals 가 구현되면서 서로 같은 이름이라면 같은 플레이어로 인식될 것 같아요.
> 이 부분을 보완할 방법을 고민해봐야할 것 같아요.

`Name`이  vo가 되면서 같은 플레이어로 인식될 수도 있을 것 같다는 것으로 이해하였는데요. 개발의도는 `Player`에서 equals를 재정의하지 않았기 때문에 같은 플레이어로 인식하지 않는다라는 생각이었어요. data class도 아니구요.
그래도 동일한 플레이어로 인식될 수 있다라는 생각에는 동의하기 때문에 그 정책을 그대로 두면서 보완할 방법을 생각해보았는데요 🤔 
equals를 재정의할만큼 해당 식별이 필요로하지 않았기 때문에 [테스트를 추가](b2fb1c35876cc9ae006b8c913a5a68223490a37a)하여 이를 보완하면 어떨까했어요.
테스트를 통해 문서화를 보완함과 동시에 이름이 동일해도 `Player`가 다르다는 것을 보장하게끔 한 것인데 요것에 대해서 현구님의 생각이 궁금합니다 🤔 

리뷰 감사합니다 🙇‍♂️

2023-06-29 09:40 UTC, Hyeon9mak requested changes
안녕하세요 진영님, 3단계 잘 진행해주셨습니다.

> Name이 vo가 되면서 같은 플레이어로 인식될 수도 있을 것 같다는 것으로 이해하였는데요. 개발의도는 Player에서 equals를 재정의하지 않았기 때문에 같은 플레이어로 인식하지 않는다라는 생각이었어요. data class도 아니구요.
그래도 동일한 플레이어로 인식될 수 있다라는 생각에는 동의하기 때문에 그 정책을 그대로 두면서 보완할 방법을 생각해보았는데요 🤔
equals를 재정의할만큼 해당 식별이 필요로하지 않았기 때문에 테스트를 추가하여 이를 보완하면 어떨까했어요.
테스트를 통해 문서화를 보완함과 동시에 이름이 동일해도 Player가 다르다는 것을 보장하게끔 한 것인데 요것에 대해서 현구님의 생각이 궁금합니다 🤔

제가 코드를 읽고 오해했어요 🙏 진영님 말씀대로 `Player` 는 이름을 통해 동등성을 확인받지 않겠네요!
그런데 거기에 맞춰 테스트 코드 작성까지... 👍 

이미 좋은 코드지만 조금 더 완성도를 높여보기 위한 부분들 코멘트 남겨보았어요.
궁금하신 점 코멘트, DM 남겨주세요 🙇‍♂️

2023-07-01 09:04 UTC, jinyoungchoi95 commented on README.md
> +- [ ] 게임 결과에 승패도 포함하여 반환한다.
🙄

2023-07-01 10:18 UTC, jinyoungchoi95 commented on src/main/kotlin/blackjack/domain/BlackjackGame.kt
>      }
좋은 것 같습니다 :)

2023-07-01 17:43 UTC, jinyoungchoi95 commented on src/main/kotlin/blackjack/domain/player/Dealer.kt
> +
화면단에서 딜러임을 프린트하고, 딜러 이름 호출 시 예외가 발생하도록 두었습니다 :)

2023-07-01 17:59 UTC, jinyoungchoi95 commented on src/main/kotlin/blackjack/domain/gamestate/finished/Finished.kt
> +}
sealed class는 abstract class에서 조금 더 부가적인 클래스로 알고있어요. 간단하게는 부모가 자식에 대해서 abstract는 알지 못하지만 sealed class는 컴파일러가 그걸 알 수 있는 구조로, when절에서 구현된 자식클래스들에 대한 when절이 모두 반영되었다면 컴파일단계에서 이를 확인할 수 있어요.

사실 사용처는 현재는 하위 자식객체에 대한 것들을 상위에서 사용할만한게 크게 보이지 않는데요 🤔 패키지 동일공간 제약을 주는 정도...? sealed class는 공부하면서 느꼈던 건 활용처가 enum의 확장판이지 않을까 라는 생각도 했어요.

뭔가 구조를 변경하면 사용가능해질 것 같은데 sealed class에 대한 니즈가 잘 떠오르지는 않는 것 같아요. 현구님은 sealed class를 어떤 상황에서 사용하시나요??

2023-07-01 18:00 UTC, jinyoungchoi95 commented
안녕하세요 현구님:)

빠르게 리뷰요청을 드리려하였으나 반영이 늦어졌습니다.....

리뷰 감사합니다 🙇‍♂️

2023-07-02 12:52 UTC, Hyeon9mak approved these changes
안녕하세요 진영님! 피드백 반영 고생하셨습니다.
4단계 진행을 위한 간단한 코멘트 남겼으니 확인해주세요.
바로 다음 단계로 가시죠~

2023-07-02 12:52 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/domain/BlackjackGame.kt
>          check(turn.isDealingTurn()) { "first draw 턴이 아닙니다." }
4단계를 진행하시면서 예외 메세지를 조금 더 다듬어보면 좋겠어요 😄 
(반말-존댓말, first draw 대신 "첫번째 턴" 등..)

2023-07-02 12:52 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/domain/gamestate/finished/Finished.kt
> +}
저도 sealed class 의 컨셉을 "상속관계 클래스 파일들을 여기저기 퍼뜨려 놓지 말고 한곳에 모아둬라.", "when 키워드를 사용할 때 깔끔하게 사용할 수 있게 해주겠다." 정도로만 생각하고 있어요. 그 이상으로 활용은 사실 상속보단 구현으로 다루거나, by 키워드(delegate pattern)를 활용하는게 낫다고 생각해요.

때문에 상속을 이용할 때 abstract 대신 sealed 를 기본 베이스로 사용하고, 같은 패키지에 두기 애매한 관계에서만 abstract 를 사용해요.

2023-07-02 12:52 UTC, merged