2단계 - 블랙잭
next-step/kotlin-blackjack pull request #509
Opened 2023-06-28 05:35 UTC by lullaaaby13

안녕하세요 리뷰어님
아직 부족한게 많아 보이는데 리뷰 통해서 방향좀 잡아보고 싶습니다 ㅜㅜ
리뷰 잘부탁드립니다 😄

2023-06-29 04:20 UTC, sah3122 requested changes
블랙잭 구현 잘해주셨습니다 :) 
고민해볼만한 코멘트 몇가지 남겨두었는데 확인 부탁드려요!

2023-06-29 08:42 UTC, lullaaaby13 commented on src/main/kotlin/blackjack/domain/Dealer.kt
> +                .shuffled()
혹시 어떤 상황에서 일급컬렉션으로 정의하는 것이 권장될까요?

2023-06-29 08:55 UTC, lullaaaby13 commented on src/main/kotlin/blackjack/domain/Player.kt
> +    var status: PlayerStatus = PlayerStatus.INIT,
클라이언트 코드에서 의도치 않게 상태를 변경할 수 있다! 일까요?
접근제어자를 private 으로 수정하겠습니다 😄

2023-06-29 11:42 UTC, lullaaaby13 commented on src/main/kotlin/blackjack/domain/Dealer.kt
> +    }
생각해보긴 했었는데 찾아보니 블랙잭 게임 특성상 52장의 카드가 모두 소진되는 일은 절대 일어나지 않을 거라 생각해서 따로 처리하진 않았거든요!
(물론 플레이어가 최대 8명으로 제한 된다는 가정입니다)
그래도 처리를 해주는 것이 좋을까요?!

2023-06-30 11:46 UTC, sah3122 commented on src/main/kotlin/blackjack/domain/Dealer.kt
> +                .shuffled()
일급 컬렉션을 정의하는것이 도메인적으로 의미를 가지는 경우 선언하는 것이 좋다고 생각합니다 😄

2023-06-30 11:47 UTC, sah3122 commented on src/main/kotlin/blackjack/domain/Dealer.kt
> +    }
말씀 주신것 처럼 모두 소진되는 일이 없을수 있겠네요 😄

2023-06-30 12:13 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
몇가지 생각거리를 남겨두었는데 다음 미션을 진행하며 반영 부탁드립니다. 
현재 점수 계산로직이 미션 요구사항을 제대로 만족하지 못하여 코멘트 남겨두었으니 확인 부탁드려요 🙏

2023-06-30 12:13 UTC, sah3122 commented on src/main/kotlin/blackjack/ui/BlackJackRoundManager.kt
>      fun round(player: Player) {
블랙잭 게임을 진행하는 로직을 담고 있기때문에 ui 패키지에 속하는것이 부자연스럽게 느껴지네요 😄

2023-06-30 12:13 UTC, sah3122 commented on src/main/kotlin/blackjack/domain/Player.kt
> -    var status: PlayerStatus = PlayerStatus.INIT,
블랙잭 게임을 진행하며 플레이어의 상태를 유지해보는건 어떨까요 ?

2023-06-30 12:13 UTC, sah3122 commented on src/test/kotlin/Playground.kt
> +    "List를 shuffled하면 무작위로 섞인 새로운 리스트가 반환 된다." {
테스트 코드는 테스트의 의도를 검증하기 위한 단언문은 필수로 정의되어 있어야 합니다.

2023-06-30 12:13 UTC, sah3122 commented on src/main/kotlin/blackjack/domain/Dealer.kt
> +        }
burst 상태의 플레이어가 카드뽑기를 시도한경우 Exception 을 던지는건 어떨까요 ?

2023-06-30 12:14 UTC, merged

2023-07-01 13:07 UTC, lullaaaby13 commented on src/main/kotlin/blackjack/ui/BlackJackPlayerNameReader.kt
> +    fun read2(): List<PlayerName> {
이름 바꾼다는걸 깜빡했습니다 😢

2023-07-01 13:10 UTC, lullaaaby13 commented on src/main/kotlin/blackjack/domain/Hand.kt
> +        return hardTotal() + ACE_SOFT
ACE가 2장 모두 11점으로 사용하는 경우는 없기 때문에(22점 -> burst)
여러 장이어도 한 장의 ACE만 11점으로 사용 가능하다고 생각했습니다!

2023-07-01 13:11 UTC, lullaaaby13 commented on src/main/kotlin/blackjack/domain/Round.kt
> +class Round(val player: Player) {
라운드라는 개념으로 분리를 시도하려다가 안지웠네요 😢