Step2: 블랙잭
next-step/kotlin-blackjack pull request #524
Opened 2023-07-02 01:17 UTC by shlee4290

안녕하세요. 제출이 많이 늦었네요 ㅠㅠ
리뷰 잘 부탁드립니다 🙇

2023-07-02 09:10 UTC, saintbeller96 requested changes
안녕하세요!
블랙잭 2단계 미션 잘 구현해주셨습니다👍
몇가지 피드백을 남겼는데 확인 후 리뷰 요청 부탁드립니다🙂

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/controller/BlackJackController.kt
> +}
List<Player>를 일급 컬랙션으로 만든 뒤, 해당 객체에 카드를 뽑는 책임을 넘기면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/controller/BlackJackController.kt
> +}
이 함수가 하는 역할은 3가지 인 것 같아요.
1. 카드를 더 받을지 결정
2. 플레이어가 카드를 더 받는다면 game이 player에게 카드 전달
3. View에 출력

확장 함수 또한 객체의 행위를 표현하는 만큼,
이 모두를 Player가 가지는 것이 적절할지 고민해보시면 좋을 것 같습니다🙂

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/Player.kt
> +    fun dealCard(card: Card) {
플레이어가 카드를 받는 행위를 블랙잭에선 `hit`이라고 표현해요.
도메인 모델이 현실 대상을 더 잘 묘사할 수 있도록 도메인에 어울리는 이름을 사용하면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Card.kt
> +}
Card을 인터페이스로 선언해주셨네요!
하지만 인터페이스는 일반적으로 객체의 행위를 추상화한 개념이니 만큼, 상태만 가지고 있는 인터페이스는 조금 어색한 것 같아요.
Card는 무늬, 숫자로 구성된 개념이니 만큼 클래스로 표현해주면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/CardDeck.kt
> +    fun pop(): Card?
Card를 nullable 타입으로 제공해야 하는 특별한 이유가 있을까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/CardDeckImpl.kt
> +    private val cards = Stack<Card>()
클래스의 프로퍼티는 가능하면 생성자에서 주입받으면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/CardDeckImpl.kt
> +    }
Shuffle된 카드덱이라는 의미를 잘 드러내는 클래스 이름을 사용하는 건 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Cards.kt
> +    }
지금 Cards의 다른 함수를 테스트하기 위해선 Cards를 생성하고 add 함수를 직접 호출해준 후에야 다른 함수를 테스트할 수 있어요.
마찬가지로 특별한 경우가 아니라면 클래스의 프로퍼티는 생성자를 통해 주입받으면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Cards.kt
> +    }
카드를 더 받을지 안받을지 판단하는 건 Cards가 아닌 Player의 책임인 것 같습니다🙂
플레이어의 canReceiveMoreCard 함수가 해당 책임을 가져가면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Cards.kt
> +    }
이 경우는 확장함수로 표현하는 것보다 연산자로 표현하는 것이 가독성이 더 좋을 것 같아요.
```kotlin
1.lessThanMaxNumber

1 < MAX_NUMBER

```

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Cards.kt
> +        private const val MAX_NUMBER = 21
21이란 점수는 블랙잭에서 중요한 의미를 가진 점수에요.
`MAX_NUMBER` 보단 `BLACKJACK_POINT` 같은 이름으로 표현하는 건 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Clover.kt
> +value class Clover private constructor(override val denomination: Denomination) : Card {
위에서도 언급했지만 Card 인터페이스가 행위를 추상화하지 않았기 때문에 Clover 클래스는 단순히 무늬만 표현하는 클래스가 되어버렸어요.
예를 들어 Clover 클래스와 Heart 클래스의 차이는 `무늬`라는 값 뿐인 것 같아요.
타입으로 무늬를 구분하는 것이 아닌, Card를 무늬, 숫자를 가지는 클래스로 변경하면 어떨까요?

2023-07-02 09:10 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Denomination.kt
> +        override fun toString() = "A"
toString()을 오버라이딩 하는 대신 별도의 문자열 프로퍼티로 가지고 있으면 어떨까요?

2023-07-06 14:45 UTC, shlee4290 commented on src/main/kotlin/domain/card/CardDeck.kt
> +    fun pop(): Card?
non-null type으로 변경했습니다~

2023-07-06 14:46 UTC, shlee4290 commented
피드백 주신 부분 반영해보았습니다. 감사합니다~

2023-07-07 14:08 UTC, saintbeller96 requested changes
안녕하세요!
블랙잭 2단계도 잘 구현해주셨습니다👍
몇가지 피드백을 남겼는데 확인 후에 다시 리뷰 요청 부탁드려요🙂

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/controller/Players.kt
> +    }
Game과 Player가 서로를 참조하고 있어요.
순환 참조가 발생하면 객체 사이 의존성을 파악하기 힘들 뿐더러 시스템에 예기치 못한 오류를 발생시킬 수 있습니다.
의존성의 흐름을 한 방향으로만 유지하도록 변경하면 어떨까요?

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/controller/Players.kt
> +    }
도메인 계층에서 View 계층에 의존하고 있는 것 같아요.
도메인에서 View의 관심사를 신경쓰지 않도록 바꾸면 어떨까요?

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/Game.kt
> +    }
확장 함수는 기존 클래스의 변경 없이도 클래스의 기능을 확장할 수 있게 만들어주는 좋은 도구입니다.
하지만 확장 함수를 남용하게 되면 객체가 원래 해야할 책임/역할이 코드 곳곳에 분산되어 객체의 응집도가 낮아질 수 있어요.
위 경우는 확장함수로 표현하지 않고도 충분히 가독성 있는 코드가 될 것 같아요.
```suggestion
    fun start() {
        players.onEach { 
            it.hit(cardDeck.pop() 
            it.hit(cardDeck.pop() 
        }
    }
    // 이하 생략
```

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/Player.kt
> +    private val cards = Cards()
cards를 생성자를 통해 주입받으면 어떨까요?

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/Player.kt
> +    }
Cards를 정의하셨으니 해당 객체를 반환하면 어떨까요?

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Card.kt
> +        private val clovers = ConcurrentHashMap<Denomination, Card>()
종류 구분 없이 가능한 조합의 카드를 모두 생성해둔다음 제공하면 어떨까요?
```suggestion
   private val availableCards: Map<Pair<Denomination, CardType>, Card> = 카드 조합
   
   fun of(denomination: Denomination, cardType: CardType): Card {
       return availableCards[ denomination to cardType ] ?: throw Exception()
   }
```

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Card.kt
> +        }
이 팩토리 함수들은 모두 테스트를 위해 존재하는 함수들인 것 같아요.
테스트 모듈에서 fixture로 제공하면 어떨까요?

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/card/CardDeck.kt
> +        }
�CardDeck의 팩토리 함수라면 CardDeck 타입을 반환해야 할 것 같아요.

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Cards.kt
> +    }
count를 활용해도 좋을 것 같아요.

```suggestion
    private fun numberOfAce(): Int {
        return cards.filter {
            it.denomination == Denomination.ACE
        }.size
    }
    private fun numberOfAce(): Int = cards.count {
        it.denomination == Denomination.ACE
    }
```

2023-07-07 14:08 UTC, saintbeller96 commented on src/main/kotlin/domain/card/ShuffledCardDeck.kt
> +            }
이렇게도 표현해볼수 있을 것 같아요🙂
```suggestion
        this.cards.addAll(cards.shuffled())
```

2023-07-07 15:59 UTC, shlee4290 commented on src/main/kotlin/controller/Players.kt
> +    }
Players 클래스는 도메인 layer가 아닌 controller에서 사용할 클래스로 만들어 controller 패키지에 넣어뒀습니다.

2023-07-07 16:04 UTC, shlee4290 commented on src/main/kotlin/controller/Players.kt
> +    }
Players -> Game, Players -> Player, Game -> Player 방향으로 의존하고 있어 현재 상태에서 순환 참조는 없네요.

2023-07-07 16:24 UTC, saintbeller96 approved these changes
안녕하세요!
피드백 잘 반영해주셨습니다💯
몇가지 사소한 리뷰를 추가했는데 다음 단계 진행하시면서 함께 반영해주시면 좋을 것 같아요.
다음 단계도 화이팅입니다💪

2023-07-07 16:24 UTC, saintbeller96 commented on src/main/kotlin/controller/Players.kt
> +    }
제가 Game이 Players를 참조하고 있는 걸로 착각했네요😅

2023-07-07 16:24 UTC, saintbeller96 commented on src/main/kotlin/controller/Players.kt
> +    }
Players는 Player의 일급 컬렉션이면서 도메인 로직을 호출하고 있으니 Players는 도메인 계층에 포함될 것 같아요.
만약 View 계층에서 사용하고자 한다면 출력 데이터를 담은 별도의 객체로 제공하면 어떨까요?
왜냐하면 객체는 일반적으로 자신의 상태를 감추기 때문에 출력 데이터를 제공하는 역할에는 적합하지 않을 수 있습니다.

2023-07-07 16:24 UTC, saintbeller96 commented on src/main/kotlin/domain/Game.kt
> +class Game(val players: List<Player>, private val cardDeck: CardDeck = ShuffledCardDeck.createNew()) {
마찬가지로 Players가 Player의 일급 컬랙션이니 만큼, List<Player> 대신 Players를 참조하는 것이 좋아보여요🙂

2023-07-07 16:24 UTC, saintbeller96 commented on src/main/kotlin/domain/card/Cards.kt
> +        if (sumOfAllCases.contains(BLACKJACK_POINT)) {
contains가 infix 함수이니 만큼 다음과 같이 표현할 수 있을 것 같아요.
```suggestion
        if (BLACKJACK_POINT in sumOfAllCases) {
```

2023-07-07 16:25 UTC, merged