[Step2] 블랙잭
next-step/kotlin-blackjack pull request #528
Opened 2023-07-02 09:31 UTC by songyi00

리뷰어님 안녕하세요 😁
2단계 미션 구현 완료했습니다!
리뷰 잘 부탁드립니다! 🙇🏻‍♀️

2023-07-02 13:00 UTC, ujusy requested changes
안녕하세요, 블랙잭 step2 고생하셨습니다 👍 
깔끔하게 구현해주셔서 읽기 수월했습니다 :)
고민해볼 몇 가지 코멘트 남겼습니다
반영 후 다시 리뷰 요청 주세요 🙌

2023-07-03 14:06 UTC, songyi00 commented on src/test/kotlin/blackjack/fake/FakeCardGenerator.kt
> +    }
@ujusy 그렇군요👍 제가 사용한건 `Fake`가 아니라 `Stub`에 가깝네요! 추가로 찾아보니 `Stub`과 `Mock`의 차이는 **상태 검증**이냐, **행동 검증**이냐로 구분할 수 있을 것 같은데 `Stub`이 하드코딩된 값 자체를 반환하면서 이를 바탕으로 테스트하려는 메서드의 상태를 검증한다면 `Mock`은 테스트하려는 메서드가 어떤 행위를 하는지에 대한 검증이라고 이해했습니다. 
그럼 결국 크게 보았을 때 `Stub`은 `Mock`에 포함되는 개념이라고 생각해도 될까요?

2023-07-03 14:38 UTC, songyi00 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    fun sumOfScoreWithAceAsOne(): Int {
불변 객체의 경우 프로퍼티를 lazy로 두어 한번만 초기화되도록 하면 중복되는 계산을 피해 메모리 절약을 할 수 있겠네요 👍

2023-07-03 14:49 UTC, songyi00 commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    }
앗 그러네요👍 실제로 업무에서 구현을 하다보면 메서드가 한가지 일만 해야한다는 것을 알면서도 **객체의 상태변경 + 반환**을 함께 하게 되는 경우가 많더라구요 🥲
리뷰어님은 메서드가 상태를 변경하는 일을 했다면 반환하는 함수는 따로 만드시는 편인가요?!

2023-07-04 05:47 UTC, ujusy commented on src/main/kotlin/blackjack/domain/BlackJackGame.kt
> +    }
객체를 새로 생성하지 않고 객체의 상태변경을 하는 경우에는 그 객체를 가지고있기 때문에 반환할 이유가 없어보여요 :) 
하지만 객체를 새로 생성하여 반환하는 경우라면 그거에 알맞는 함수명을 작성할 것 같아요!
빌더와 조정자에 대한 글인데 한번 읽어보셔도 좋을 것 같습니다 
- https://jessyt.tistory.com/141

2023-07-04 05:55 UTC, ujusy commented on src/test/kotlin/blackjack/fake/FakeCardGenerator.kt
> +    }
포함되는 개념보다는 사용하는 경우 그리고 목적이 다른 것 같아요!! 
Stub 은 **객체의 상태**를 검증하고 싶을 때 많이 사용하고있는데, 예를 들면 이메일 템플릿 객체가 랜더링한 결과물이 내가 원하는 결과로 잘 나왔는지 확인하고 싶을 때 사용해볼 수 있을 것 같아요.
Mock의 경우는 **결과를 직접 지정**해서 지정한 명세에 따라서 동작하도록 만든것이구요. 실제로 함수가 잘 호출되었는지 검증하는데 더 목적이 있고 테스트 속도 개선 및 검증하고 싶은 테스트에 집중하고 싶을 때 검증하고자 하는 것을 제외한 다른 객체들을 모킹하여 사용하는 것 같습니다 :)

2023-07-05 11:54 UTC, ujusy approved these changes
리뷰 반영 잘해주셨습니다 💯 
더 코멘트드릴 내용은 없어 머지하도록 하겠습니다 😁
다음 미션도 화이팅입니다 💪

2023-07-05 11:54 UTC, ujusy commented on src/main/kotlin/blackjack/domain/CardGenerator.kt
> +fun interface CardGenerator {
functional interface 로 반영해주셨네요 👍

2023-07-05 11:54 UTC, merged