🚀 3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #533
Opened 2023-07-02 18:21 UTC by jonghyunhub

안녕하세요 리뷰어님!
이번 미션은 난이도가 있어서 시간이 생각보다 오래걸렸네요 😅

딜러와 플레이어와 겹치는 부분이 있고 다른 부분이 있어서 구현하는데 고민이 많이 되었습니다.
하여, 제가 생각한 포인트를 간단하게 정리해서 적어보겠습니다. 

* 딜러와 플레이어와 겹치는 부분 => 딜러와 플레이어의 부모가 되는 인터페이스를 만들어서 추상화 진행

* 딜러와 플레이어의 다른 부분(ex. 카드를 뽑는 기준 - 딜러는 16을 기준으로 카드를 뽑고 플레이어는 21을 기준으로 카드를 뽑음) 
=> 객체 조합을 이용하여 위임한뒤, 요청을 한 객체의 타입이 무엇인지를 기준으로 다르게 로직 적용

이게 제 생각에는 최선으로 객체지향적 설계를 구현한것인데 더 좋은 방법이 있을지 모르겠네요.
피드백 잘 부탁드리겠습니다~ 🙇🏻‍♂️

2023-07-03 12:38 UTC, BeokBeok requested changes
이전 단계 피드백과 블랙잭(딜러) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-07-03 12:38 UTC, BeokBeok commented on src/main/kotlin/blackjack/README.md
> +- [x] 딜러 타입일 때 카드 숫자 합을 16을 기준으로 검사한다.(딜러는 카드를 뽑을때 16을 기준으로 체크한다)
<img width="285" alt="스크린샷 2023-07-03 오후 9 17 37" src="https://github.com/next-step/kotlin-blackjack/assets/48344355/ddf6eba2-c5fc-4fec-8adb-094994c444e1">

딜러는 두 장을 받지만, 한 장만을 오픈해야 합니다.
이 부분도 적용해보면 어떨까요?

2023-07-03 12:38 UTC, BeokBeok commented on src/main/kotlin/blackjack/controller/BlackJackController.kt
> +        return gamerList.toList()
방어적 복사 활용 👍 👍

2023-07-04 08:12 UTC, jonghyunhub commented on src/main/kotlin/blackjack/README.md
> +- [x] 딜러 타입일 때 카드 숫자 합을 16을 기준으로 검사한다.(딜러는 카드를 뽑을때 16을 기준으로 체크한다)
제가 미처 확인을 못한 부분이 있었네요 😅

2023-07-04 09:09 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/BlackJackGamer.kt
> +interface BlackJackGamer {
추상화로 중복을 많이 제거했다고 생각했는데 아직 중복이 많이 남아있었네요! 고쳐보겠습니다 💪

2023-07-04 10:01 UTC, jonghyunhub commented on src/test/kotlin/blackjack/domain/CardNumberCalculatorTest.kt
> +        val startSum = 11
저의 로직에서는 
* A와 더해서 21보다 작으면 11로 
*  21보다 크면 1로
계산하는 로직이 있어서 이를 위한 계산의 경계값으로 11을 가지고 계산을 했습니다.

지금 읽어보니 11이라는 숫자가 매직넘버가 되는 상황이네요!
테스트 코드에서도 매직넘버를 신경쓰면서 코드를 짜야겠습니다 감사합니다 👍

2023-07-04 10:09 UTC, jonghyunhub commented on src/test/kotlin/blackjack/domain/PlayerTest.kt
> +    fun `플레이어의 전적은 NONE인데 조회할 경우 IllegalArgumentException을 throw 한다`() {
Player의 맴버변수중 gameRecord가 승패가 결정이 나야 초기화가 되는 녀석이라 그것을 위해 만든 타입이었는데
생각해보니 불필요한 맴버변수네요! 👍

2023-07-04 10:10 UTC, jonghyunhub commented
ACE는 다른 숫자와 다르게 특별한 계산 로직이 들어가는 녀석이라 다른 숫자들과 분리해서 테스트를 진행하였습니다

2023-07-04 15:19 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-07-04 15:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/ui/ResultView.kt
> +        val (shape, number) = cards[0]
destructuring declaration 활용 👍

2023-07-04 15:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/ui/ResultView.kt
> +        val (shape, number) = cards[0]
```suggestion
        val (shape, number) = cards.first()
```
숫자 0대신 first를 사용하시면 가독성을 챙기실 수 있습니다. 😄

2023-07-04 15:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/RuleChecker.kt
> +import blackjack.domain.gamer.*
ktlint가 적용되지 않은 것 같습니다.
커밋 시 ktlint가 잘 동작하는지 확인 부탁드립니다. 🙏

2023-07-04 15:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/gamer/AbstractBlackJackGamer.kt
> +abstract class AbstractBlackJackGamer : BlackJackGamer {
클래스명에는 Abstract와 같은 예약어는 사용하지 않는 것을 권장합니다. 🙏

2023-07-04 15:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/gamer/AbstractBlackJackGamer.kt
> +abstract class AbstractBlackJackGamer : BlackJackGamer {
BlackJackGamer을 인터페이스가 아닌 부모 클래스로 만들어도 되지 않을까요?
추가로 abstract와 open과의 차이점에 대해서 학습해보시면 좋을 것 같습니다.

2023-07-04 15:19 UTC, BeokBeok commented on src/test/kotlin/blackjack/domain/CardNumberCalculatorTest.kt
> +        val cardList = listOf(Card(shape = CardShape.DIAMOND, ace))
확실히 이전보다 보기 좋아진 것 같습니다. 👍 👍

2023-07-04 15:19 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/gamer/Player.kt
>  class Player(private val name: String) : AbstractBlackJackGamer() {
name을 private로 설정하셨지만, getName 함수를 통해 name을 얻어올 수 있습니다.
생성자에는 private로 하고 getName 함수를 통해 접근하도록 하신 이유는 무엇일까요?

2023-07-04 15:19 UTC, merged

2023-07-07 14:38 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/gamer/Player.kt
>  class Player(private val name: String) : AbstractBlackJackGamer() {
출력할때 gamer의 name이 필요해서 getName으로 열어놨는데 이럴경우 어떻게 하는게 좋을까요?
고민이 되는것이 출력문을 gamer 내부로 넣자니 출력은 도메인의 관심사는 아니라서 꺼내오는것으로 바꿨네요.🤔
이럴 경우 어떻게 하는것이 좋을까요~?

2023-07-07 15:10 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/gamer/Player.kt
>  class Player(private val name: String) : AbstractBlackJackGamer() {
프로퍼티의 getter와 getName 함수는 어떤 차이가 있을까요?
```kotlin
val player = Player(name= "플레이어")

// 1
player.name 

// 2
player.getName()
```
1번과 2번은 어떤 차이점이 있을까요?

2023-07-07 15:42 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/gamer/Player.kt
>  class Player(private val name: String) : AbstractBlackJackGamer() {
아~ 저는 외부에서 name을 접근하지 못하게 막아야한다고 말씀하시는줄 알았는데
코틀린이 제공하는 문법을 두고 굳이 getName을 왜 사용하는지에 대해 여쭤보시는거였군요!

제가 만든 코드는  BlackJackGamer라는 상위 타입 클래스로 추상화를 하고 
출력시 BlackJackGamer의 name을 꺼내와야 하는 상황이라 부득이하게 getName을 만들고 override를 사용했는데
이런 경우에도 프로퍼티의 getter가 사용이 가능할까요?

2023-07-08 00:31 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/gamer/Player.kt
>  class Player(private val name: String) : AbstractBlackJackGamer() {
AbstractBlackJackGamer에서 name을 캡슐화하면 되지 않을까요?

2023-07-08 09:38 UTC, jonghyunhub commented on src/main/kotlin/blackjack/domain/gamer/Player.kt
>  class Player(private val name: String) : AbstractBlackJackGamer() {
아 이런방법이 있었네요~!! 감사합니다 👍👍👍