3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #534
Opened 2023-07-03 01:03 UTC by ohsung

안녕하세요
반선호님 리뷰 요청 드립니다.

감사합니다.

2023-07-04 09:38 UTC, vsh123 requested changes
안녕하세요!
3단계 구현 잘해주셨네요!! :) 

몇가지 코멘트를 남겨놓았으니 확인부탁드릴게요~

2023-07-04 09:38 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/Player.kt
> +    var draw: ((String) -> Boolean)? = null
개인적으로는 해당 프로퍼티가 Player에 필요할까라는 의문이 드는데요!! 이렇게 위치시키신 이유가 있을까요?

2023-07-04 09:38 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/GameState.kt
> +        fun Player.ofGameState(dealer: Player): GameState {
- Dealer.result()를 호출하게되면 해당 인자로 dealer가 아닌 player가 들어오는 것 같은데요!! 인자명을 player로 해주는게 어떨까요? 
- Player클래스의 함수가 아닌 확장함수로 만드신 이유가 있을까요?

2023-07-04 09:38 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/Dealer.kt
> +    fun result(player: List<Player>): Map<GameState, Int> = player.map { this@Dealer.result(it) }.groupingBy { it }.eachCount()
players와 같이 복수형으로 작성해주시면 좋을 것 같아요~

2023-07-04 09:38 UTC, vsh123 commented on src/test/kotlin/blackjack/DealerTest.kt
> +            }
```suggestion
            cards = mutableListOf(
                Card(Suit.HEART, Number.KING),
                Card(Suit.HEART, Number.SIX)
            )
```

위와 같이 작성이 가능해 보여요!

2023-07-04 09:38 UTC, vsh123 commented on src/test/kotlin/blackjack/PlayerTest.kt
> +    "딜러가 21 내카드가 22 인 result " {
딜러가 21 내카드가 20 인 result가 맞아보여요!

2023-07-04 09:38 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/Dealer.kt
> +class Dealer(name: String = "딜러") : Player(name) {
상속보다는 조합을 사용해보면 어떨까요?

https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/

2023-07-04 23:00 UTC, ohsung commented on src/main/kotlin/baclkjack/domain/play/GameState.kt
> +        fun Player.ofGameState(dealer: Player): GameState {
별다른 이유는 없습니다. GameState 상태를 가지고 있어서 만들었습니다.
Player 의 함수가 더 좋을까요?!

2023-07-05 00:40 UTC, ohsung commented on src/main/kotlin/baclkjack/domain/play/Player.kt
> +    var draw: ((String) -> Boolean)? = null
isDraw() 를 통해 카드 드로우 입력을 받기위해 만들었는데요.
Interface로 변경등 다른 방법도 있는데요 좋은 방법이 아닌가요?!

2023-07-05 00:44 UTC, ohsung commented on src/main/kotlin/baclkjack/domain/play/Dealer.kt
> +class Dealer(name: String = "딜러") : Player(name) {
좋은 리뷰 감사합니다.
수정하겠습니다.

2023-07-05 17:13 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/Dealer.kt
> +class Dealer(player: Player = Player("딜러")) : User by player {
위임까지 사용하셨군요!! 💯

2023-07-05 17:13 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/Dealer.kt
> +class Dealer(player: Player = Player("딜러")) : User by player {
아래 이미지는 
- player를 프로퍼티로 미선언했을 경우(현재) (왼쪽)
- player를 프로퍼티로 선언했을 경우(오른쪽)
일 경우 각각의 java코드로 디컴파일된 결과를 보여주는건데요!

위임을 사용했을 경우 코틀린에서 어떤식으로 처리하시는지 이해하시고 사용하시면 더 좋을 것 같아서 참고차 공유드립니다 :) 
<img width="2022" alt="image" src="https://github.com/next-step/kotlin-blackjack/assets/32254689/47b5dd67-0455-40c9-aa62-9a1c6cd0c1ce">

2023-07-05 17:13 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/Player.kt
> +    var draw: ((String) -> Boolean)? = null
해당 함수는 결국 inputView.inputCardDraw(it)를 domain레벨까지 가져와서 호출한다는 느낌이 있어서요~
view와 domain을 이어주는 controller레벨에서도 처리가 가능하지 않을까 하는 궁금증이 들어서 코멘트를 남겼습니다!

2023-07-05 17:17 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/GameState.kt
> +        fun Player.ofGameState(dealer: Player): GameState {
확장함수의 설명에 보면 기존 클래스의 함수 수정 없이 말들 수 있는 함수라고 설명이 되어있는데요!
저는 이런 케이스를 
* class를 수정할 수 없는 경우(List와 같이)
* 유틸성 함수
* 도메인로직과 전혀 상관없는 함수
로 이해하고 사용하고 있습니다!

현재 작성주신 코드에서는 충분히 Player의 함수로 넣을 수 있고, 도메인의 역할에도 맞다고 생각해서 단순 함수로 선언해도 좋지 않을까 생각해요 :) 

https://kotlinlang.org/docs/extensions.html

2023-07-05 17:18 UTC, vsh123 requested changes
안녕하세요!
피드백 반영 잘해주셨네요!!

문의주신 내용과 관련하여 코멘트를 남겨놨으니 확인부탁드리겠습니다~

2023-07-05 17:18 UTC, vsh123 commented on src/main/kotlin/baclkjack/domain/play/GameState.kt
> +        fun User.ofGameState(player: User): GameState {
user로 바뀌었으니 user가 맞겠네요..!

2023-07-06 00:40 UTC, ohsung commented on src/main/kotlin/baclkjack/domain/play/Player.kt
> +    var draw: ((String) -> Boolean)? = null
입력값 컨트롤러가 아닌 도메인에서 처리해야 된다고 생각하는데요. 
카드를 받을 지 말지는 컨트롤러에서 결정이 하는게 아니고 Player 가 결정 하는거라고 생각해서요.
isDraw를 통해서 Dear와 Player 같이 사용하기도 하고요

좋은 방향에 대해서도 조언 부탁 드립니다.

2023-07-06 00:40 UTC, ohsung commented on src/main/kotlin/baclkjack/domain/play/Dealer.kt
> +class Dealer(player: Player = Player("딜러")) : User by player {
좋은 정보 감사합니다.

2023-07-07 03:43 UTC, vsh123 approved these changes
안녕하세요!
피드백 반영 잘해주셨네요!! 💯 

다음 스텝을 위해 이번 스텝은 머지하도록 할게요!
마지막까지 화이팅입니다!

2023-07-07 03:43 UTC, merged