[블랙잭] step4
next-step/kotlin-blackjack pull request #537
Opened 2023-07-03 18:27 UTC by jinyoungchoi95

안녕하세요 현구님:)

마지막 미션이네요! 요구사항은 간단했으나... 생각보다 변경점이 많아서 당황했던 것 같네요 🤣 하나하나 변경하고싶었으나 수익 계산 부분에서는 생각치 못하게 한번에 큰볼륨으로 변경하게 되어서 아쉽습니다 😢 

리뷰 감사합니다 🙇‍♂️

2023-07-04 10:20 UTC, Hyeon9mak requested changes
안녕하세요 진영님! 
우려하신 것과 달리 대부분 테스트 코드나 에러 메세지 변경인거 같아 보이네요 😄 
이미 이전 단계에서부터 완성도가 높았기 때문에 큰 변화 없이 요구사항이 모두 충족된거 같아요 👍 👍 
아주 간단한 코멘트 하나만 남겼습니다.
추가로 궁금하신 사항이 있다면 질문 남겨주시고, 없으시다면 바로 approve 하도록 하겠습니다.
마지막까지 화이팅! 💪

2023-07-04 10:20 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/Application.kt
> +    val players: List<Participant> = inputPlayerNames().map { Player.of(it, inputPlayerBettingMoney(it)) }
`Application.kt` 에서 `BlackjackGame` 왜 다른 클래스에 대한 의존을 최소화하도록 해보면 어떨까요? 😉

2023-07-04 10:20 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/domain/gamestate/GameState.kt
> +    fun stay(): GameState
👍

2023-07-04 10:20 UTC, Hyeon9mak commented on src/test/kotlin/blackjack/domain/player/MoneyTest.kt
> +    }
👍 👍

2023-07-06 16:23 UTC, jinyoungchoi95 commented on src/main/kotlin/blackjack/Application.kt
> +    val players: List<Participant> = inputPlayerNames().map { Player.of(it, inputPlayerBettingMoney(it)) }
현재 `BlackjackGame`이 도메인 비즈니스를 너무 많이 담고 있어서 해당 클래스에 뷰클래스를 담기보다는 `ConsoleBlackjackGame`을 두어 의존을 분리하였습니다 :)

2023-07-06 16:24 UTC, jinyoungchoi95 commented
안녕하세요 현구님:)
리뷰 감사합니다 🙇‍♂️

2023-07-07 06:36 UTC, Hyeon9mak approved these changes
안녕하세요 진영님, 블랙잭 미션 마지막까지 고생하셨습니다.
요구사항도 모두 충족해주셨고, 완성도도 높아서 미션 마무리 하면 될 것 같습니다 😄 👍 
이펙티브코틀린 강의도 이제 막바지네요.
마지막 미션 완주까지 화이팅입니다! 💪 
고생하셨습니다~

2023-07-07 06:36 UTC, Hyeon9mak commented on src/main/kotlin/blackjack/controller/ConsoleBlackjackGame.kt
> +import blackjack.domain.player.Player
아하, 코멘트 의도가 조금 잘못 전달된 것 같아요.
view 와 domain 간 흐름을 관제하는 객체에서 domain 세부 사항을 모두 알 필요는 없다는 의미였어요.
의존하는 domain 객체가 적으면 적을수록 유지보수가 쉬워질테니까요.
`BlackjackGame` 을 통해서 원시적인 데이터만 주고 받는다면 player 에 대한 의존이 사라질 것 같네요.

2023-07-07 06:36 UTC, merged