Step4 - 블랙잭(베팅)
next-step/kotlin-blackjack pull request #539
Opened 2023-07-04 10:48 UTC by konempty

마지막 4단계도 리뷰 잘부탁드립니다~!

2023-07-04 12:54 UTC, laco-dev requested changes
4단계 미션 고생 많으셨습니다.

오늘 강의를 기반으로 혹시 수정이 될 수 있으니 몇가지 필요한 내용에 대해서만 먼저 의견을 남겨드렸습니다. 💪🏻

2023-07-04 12:54 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/user/Player.kt
> +    }
블랙잭 게임에서 Hit는 하나의 상태로 볼 수 있습니다.
예를 들어 이미 버스트 상태라면 더 뽑는지 여부 상관없이 그냥 버스트입니다.

오늘 강의에서 블랙잭 게임에 대한 상태를 참고 해 보시면 됩니다. 🙏🏻

2023-07-04 12:54 UTC, laco-dev commented on src/test/kotlin/blackjack/util/DefaultInterfaceImplements.kt
> +val TEST_USER_BET_MONEY_GETTER = { _: String -> 10000 }
지금은 여러 환경에서 이 코드를 사용하지 않기 때문에 문제가 없지만, 여러 사람이나 다른 조건에서 테스트가 필요한 경우 상수처럼 사용되는 Fixture는 확장이 어렵습니다.
가령 배팅 금액이 얼마일 때 어떠한 테스트를 한다는 불가능합니다.

객체지향 구현을 연습하듯이 구현체를 만들어서 전달하도록 해 보면 좋습니다
```kotlin
class FixedBetMoneyGetter(val betMoney: Long) : BetMoneyGetter { ... }
```

2023-07-04 12:54 UTC, laco-dev commented on src/test/kotlin/blackjack/domain/UserTest.kt
> +                user.status shouldBe PlayerStatus.HIT
정상적으로 생성된 케이스에서 유저의 상태 정보 검증이 필요할까요?
테스트에서 필요한 관심사 외에는 최대한 관심사를 줄일수록 좋아요.

테스트를 하기 애매하다면 이름을 다시 고민 해 보는 것도 좋습니다
예를 들어 위 테스트는 아래와 같이 표현할 수 있습니다
```kotlin
Given : 비어있지 않은 이름이 주어지면
When : 유저를 생성할 때
Then : 정상적으로 생성된다 (shouldNotThrows)
```

2023-07-07 07:57 UTC, konempty commented on src/main/kotlin/blackjack/domain/user/Player.kt
> +    }
요 바로 위 리뷰를 수정하다보니까 해당 코드가 자연스럽게 사라지긴 했는데
여기에서 리뷰해주신 내용이 이해가 안되서 질문드려요..!
제 의도는 플레이어가 버스트상태, 블랙잭, 히트가 아니면
결국 플레이어의 상태는 스탠드로 정해진다 라는 의도 였는데
리뷰어님은 요 코드를 어떤식으로 고치길 의도하셨는지 궁금합니다 ㅎㅎㅎ...

2023-07-07 23:46 UTC, laco-dev commented on src/main/kotlin/blackjack/domain/user/Player.kt
> +    }
반환 값을 의도했어요.
checkHit()에서 버스트 상태를 다시 검사하고 있다는 점을 놓치고 있었네요.

status를 이 시점에서 바꾸고 있다 보니 착각 한 것 같습니다!

2023-07-07 23:55 UTC, laco-dev approved these changes
수익률 계산 테스트가 문서인것처럼 잘 읽혀서 좋았습니다!
그 외 여러가지 복잡한 피드백을 드렸는데 잘 따라와주셔서 감사합니다.

이후의 남은 미션에서도 더 좋은 경험 얻어가시기를 기대하겠습니다.
블랙잭 미션 고생 많으셨습니다.

2023-07-07 23:55 UTC, merged