Step2
next-step/kotlin-blackjack pull request #614
Opened 2023-11-14 16:07 UTC by wjdtlr0920

블랙잭 미션.. 어떻게든 했지만 너무 못한것 같아서 창피하네요..ㅠ
잘 부탁드립니다...

2023-11-15 04:24 UTC, laco-dev requested changes
블랙잭 미션 고생 많으셨습니다.
중간부터, 의문이 들어서 설계 기준의 확인이 필요할 것 같아서 확인을 우선 멈추었습니다.

객체지향 프로그래밍은 자율적인 객체들이 협력을 통해 동작합니다.
하지만 모든 객체들이 스스로 해야할 비즈니스 로직이 별도 domain 패키지에 따로 작성이 되었습니다.
유즈케이스라는 개념으로 접근을 하신 것인지, 아니면 모델은 비즈니스 로직을 가지면 안된다를 기준으로 잡고 계신지 궁금합니다.

또한 PR을 올려주실 때에는 `.gitignore` 를 적용하는 방법을 학습하시면 좋을 것 같습니다.
그 외에 현재 기준에서 몇가지 의견을 먼저 남겨드렸습니다.

2023-11-15 04:24 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/model/vo/ChoiceDeal.kt
> +        }
`ChoiceIsDeal` 의 종류는 `AGREE` `DISAGREE` 두 종류입니다.
마찬가지로 enum class로 관리되면 더욱 용이하지 않을까요?

또한, "y" "n"으로만 입력해야 한다는 것도 UI에서 고민하는 내용이기 때문에 만약 정말 이 기능을 필요로 하는 곳이라면 아래처럼 작성이 되야 할 수도 있습니다...
매우 귀찮겠죠..?

```kotlin
val inputValue = "네"
val choiceIsDeal: String = when (inputValue) {
   "네" -> "y"
   "아니오" -> "n"
}
return ChoiceIsDeal.from(...)
```

2023-11-15 04:24 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/model/vo/CardNumber.kt
> +data class CardNumber(val cardNumber: Triple<String, Int, Int>) {
`CardNumber` 에 대해서도 Number 타입이 그대로 활용될 수 있는데, 별도로 Raw 타입이 포장된 이유를 모르겠습니다

2023-11-15 04:24 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/model/vo/CardNumber.kt
> +    enum class Number(val mName: String, val value: Int, val secretValue: Int) {
코틀린은 프로퍼티의 접근자에 따라 getter(), setter()가 만들어지기 때문에 멤버 변수를 의미하는 m을 사용하지 않습니다.

backing property 목적으로 사용되는 경우라면 `_`를 사용합니다.
https://kotlinlang.org/docs/properties.html#backing-properties

2023-11-15 04:24 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/domain/DealCard.kt
> +object DealCard {
객체지향 프로그래밍의 객체는 자율적으로 역할을 수행합니다.
하지만 지금 구조에서는 객체가 스스로 해야할 비즈니스 로직이 모두 외부에서 작성이 되어 있습니다.

모든 비즈니스 로직을 외부에 작성하도록 하신 기준이 무엇인가요?
그렇다면 이 개념상 모든 모델과 값 객체는 로직을 가지면 안된다. 로 봐야 할까요?

2023-11-15 04:24 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/domain/DealCard.kt
> +import step2.blackjack.model.vo.ChoiceIsDeal
`domain` `model` `vo` 세개의 패키지가 어떤 차이를 가지는 것인지 궁금합니다.

domain이 이론적으로 비즈니스 로직만 해야하는 순수 도메인 개념이고 UI에 종속적인 개념이 model이라면 도메인은 model을 알아서는 안됩니다.

또한 model과 vo는 현재 전혀 차이가 없다고 느껴집니다.

2023-11-15 14:45 UTC, wjdtlr0920 commented on .gradle/buildOutputCleanup/cache.properties
> +gradle.version=7.6
죄송합니다. 제가 봐도 너무 볼품 없이 제출한 것 같아 너무 죄송하네요.. 다음에 제출 드릴 때는 말씀해주신 피드백 주신 내용과 코드를 정리하여 다시 제출 하도록 하겠습니다!

2023-11-15 14:45 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/view/InputView.kt
> +private const val INPUT_DEAL_CARD_DESCRIPTION = "%s는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)"
수정하겠습니다.

2023-11-15 14:46 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/view/ResultView.kt
> +private const val DEFAULT_AROUND_COUNT = 21
수정하겠습니다.

2023-11-15 15:01 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/model/UserList.kt
> +            val userList = userListText.split(DELIMITER).map { name -> User.from(name) }
InputView, ResultView와 같은 View에서 어느정도의 책임?을 가져야 하는지 구분이 잘 되지 않습니다..
예를 들어 InputView에서 유저 이름을 가진 문자열을 받아 UserList라는 객체를 만들어 리턴을 하게 만들어도 괜찮은 걸까요..?

2023-11-15 15:07 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/model/vo/CardSign.kt
> +    }
CardSign 이라는 value class를 가져가고 싶어 사용을 해봤습니다!
그럼 혹시 말씀하신 내용은 Card Class 내부에 Sign이라는 EnumClass를 만들어 사용하는게 더 나은 방법이라는 말씀 맞으실까요??

2023-11-15 15:09 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/model/vo/CardSign.kt
> +        private const val DIAMOND_VALUE = "다이아"
UI가 그릴때 필요한 것을 객체가 그대로 가지고 있는게 좋겠다 싶었는데 말씀하신 것을 보니 UI쪽에서 컨트롤 하는게 맞아보이네요!! 피드백 감사합니다!!

2023-11-15 15:16 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/model/vo/CardNumber.kt
> +data class CardNumber(val cardNumber: Triple<String, Int, Int>) {
이렇게 한 이유는 CardNumber Class 내부에 있는 Enum Class인 Number를 다른 곳에서 참조하지 못하게 하려고 했었습니다.
제가 개념이 잘 안잡혀서 그런것 같습니다..

2023-11-15 15:30 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/domain/DealCard.kt
> +object DealCard {
상수의 경우 객체 내부나 같은 파일에 선언해두면 되는 줄 알았습니다.. 수정하겠습니다!

2023-11-15 15:36 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/domain/DealCard.kt
> +import step2.blackjack.model.vo.ChoiceIsDeal
domain은 이론적인 비즈니스 로직에만 사용하는 객체들로 구성하고, model은 domain에서 사용할 model을 위한 패키지 였는데 잘못 구현한 것 같습니다..

model과 vo의 차이는 반성하겠습니다..

2023-11-23 12:14 UTC, laco-dev approved these changes
구조상의 의문이 들어서 남겨드렸는데, 도메인 객체들이 스스로 할 수 있도록 잘 개선 해 주셨네요! 객체와 테스트도 잘 분리가 되어서 이해하기에 좋았습니다. 👍🏻 

어렵게 생각하신 부분과 몇가지 더 고민 해 볼만한 내용이 있어서 같이 남겨드렸는데요.

다음 3단계 요구사항에서는 딜러도 한명의 게임 참여자가 된다는 것을 인지할 필요가 있습니다. 😱 

충분히 고민 해보시고, 천천히 나아가 보시면 되겠습니다.

2023-11-23 12:14 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/domain/model/Dealer.kt
> +    fun handsOut(gambler: Gambler): Unit = gambler.receive(deck.peek())
Unit 반환 타입은 생략이 가능하기 때문에 따로 명시하지 않아도 됩니다.

2023-11-23 12:14 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/domain/model/Dealer.kt
> +value class Dealer private constructor(private val deck: Deck) {
딜러가 덱을 가지고, 카지노처럼 나눠주는 개념으로 만들어졌네요. 👍🏻 

이 방법도 좋다고 생각하지만 다르게 바라보면 딜러가 여러개의 게임(?)에 영향을 줄 수 있는 존재가 되어 버릴 수도 있다고 생각합니다.
```kotlin
val gamblers1: Gamblers
val gamblers2: Gamblers
val gamblers3: Gamblers
val dealer: Dedaler

dealer.handsOutAll(gamblers1)
dealer3.handsOutAll(gamblers3)
dealer3.handsOutAll(gamblers2)
...
```

그렇다면 하나의 블랙잭 게임이라는 관점으로 접근한다면, 딜러도 게임의 참여 구성원으로 볼 수 있습니다.

```kotlin
하나의 블랙잭 게임(딜러, 겜블러, 덱)
```

이 내용이 다음 요구사항을 구현하는데 있어, 어떤 관점으로 해석할지 고민 해 보시면 됩니다.

2023-11-23 12:14 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/view/InputView.kt
> +        }
이동작은 Name 객체에서 검증을 하고 있으니 중복으로 하지 않아도 되겠네요.

2023-11-23 12:14 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/controller/BlackjackController.kt
> +        while (gambler.cards.min().toInt() < Score.from(BLACKJACK_NUMBER).toInt() && InputView.drawHitAndStay(gambler)
`gambler.cards.min().toInt() < Score.from(BLACKJACK_NUMBER).toInt()` 이 역할은 겜블러가 더 뽑을 수 있는지로 겜블러가 스스로 결정할 수 있도록 해보면 어떨까요?

```kotlin
gambler.shouldDraw()
```

마찬가지로 테스트도 이어서 작성할 수 있겠습니다
> 카드들의 점수 합이 21점을 초과하면 겜블러는 더이상 카드를 뽑을 수 없다

2023-11-23 12:14 UTC, laco-dev commented on src/main/kotlin/step2/blackjack/view/InputView.kt
> +    fun drawInputNamesView(): Names {
> InputView, ResultView와 같은 View에서 어느정도의 책임?을 가져야 하는지 구분이 잘 되지 않습니다..
예를 들어 InputView에서 유저 이름을 가진 문자열을 받아 UserList라는 객체를 만들어 리턴을 하게 만들어도 괜찮은 걸까요..?

자동차 경주 마지막 미션에서 봐왔던 구조도를 다시 살펴보시면, 뷰는 도메인을 알지만 도메인은 뷰를 모르도록 하는 것을 지키고 있습니다.

입력이라는 것이 누구의 역할인가로 본다면?
쉽게 생각해서 콘솔에서 입력하다가 키오스크로 입력이 변경되었으면 어떻게 되는것이지? 를 예로 들어볼 수 있을 것 같아요.

2023-11-23 12:14 UTC, merged

2023-11-24 04:06 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/domain/model/Sign.kt
> +enum class Sign(val sign: String, val number: Int, val secretNumber: Int) {
바꿔놓고보니 말씀하신게 더 효율적이라는게 느껴지네요

enum class Sign 이라는 클래스도 Model로 보는게 맞을까요??

data class, value class, class들은 model같은데 enum class는 뭔가 model이란 느낌을 못받는것 같아요..

2023-11-24 04:27 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/domain/model/Dealer.kt
> +    fun handsOut(gambler: Gambler): Unit = gambler.receive(deck.peek())
반환 값이 없다는 것에 대해 명시해 주고 싶었는데 Unit인 경우에는 명시하지 않는게 더 나은 방법인 건가요??

2023-11-24 07:35 UTC, wjdtlr0920 commented on src/test/kotlin/step2/blackjack/NamesTest.kt
> +    }
여쭤보고 싶은게 있습니다!

gamblers[0].name shouldBe Name("aaa")
gamblers[1].name shouldBe Name("bbb")

위 코드를 아래 코드로 변경 했는데 실패를 하더라고요.. Names는 성공을 하는데 왜 Gamblers는 실패를 하는걸까요..?

gamblers shouldContainExactly listOf(Gambler.from(Name("aaa")), Gambler.from(Name("bbb")))

2023-11-24 09:51 UTC, wjdtlr0920 commented on src/main/kotlin/step2/blackjack/view/InputView.kt
> +    fun drawInputNamesView(): Names {
위 내용은 아닌데 여쭤볼게 있습니다..

개발하다보니 21이라는 숫자가 여기저기서 너무 필요해지는데 만약 Domain Layer에서 21의 숫자가 여기저기서 필요하면 도메인 최상위에 상수관련 모음 파일을 만들고 거기서 도메인에 필요한 곳들이 가져다 써야 하는건가요? 아니면 필요한 클래스나 파일마다 따로 21이라는 숫자를 가지고 있어야 하는건가요??

아니면 설계가 잘못되어서 그런걸까요??ㅠ