[step1] 코틀린 DSL
next-step/kotlin-blackjack pull request #617
Opened 2023-11-14 19:21 UTC by 10000001a

안녕하세요 리뷰어님!
세번째 미션 잘 부탁드리겠습니다!

이번 미션에서는 Kotest로 JUnit5의 ParameterizedTest처럼 작동하도록 테스트를 작성해보았습니다. 관련해서도 피드백 부탁드리겠습니다🙇‍♂️

DSL이라는 개념이 익숙치 않아서 몇 가지 궁금한 점이 있습니다.
1. DSL은 프로그래밍 언어보다는 사람의 언어처럼 사용할 수 있도록 하는게 좋다고 이해했는데요, 아래 코드의 if문과 같이 프로그래밍적인 표현도 같이 섞어서 쓰기도 하는지 궁금합니다!
```
introduce {
    name(it.name)
    if (it.company != null)
      company(it.company)
}
```

2. 테스트나 빌드 환경이 아닌 운영 코드에도 코틀린 DSL을 사용하는 경우가 있는지 궁금합니다!

2023-11-15 11:44 UTC, Flamme1004K commented
> DSL은 프로그래밍 언어보다는 사람의 언어처럼 사용할 수 있도록 하는게 좋다고 이해했는데요, 아래 코드의 if문과 같이 프로그래밍적인 표현도 같이 섞어서 쓰기도 하는지 궁금합니다!
> introduce {
>     name(it.name)
>     if (it.company != null)
>       company(it.company)
> }

아뇨! 저는 if문과 같이 프로그래밍적인 표현은 섞어쓰지는 않습니다.

> 테스트나 빌드 환경이 아닌 운영 코드에도 코틀린 DSL을 사용하는 경우가 있는지 궁금합니다!

네! 저 같은 경우에는 복잡한 쿼리처럼 직접 코드로 표현하면 어려운 것을 DSL로 사용하고 있습니다.

2023-11-15 11:45 UTC, Flamme1004K requested changes
안녕하세요!

블랙잭 미션 오신 것을 환영합니다! 

1단계 미션 잘 해주셨는데, 테스트 케이스에 대한 부분이 DSL 요구사항과 다른 부분이 있네요. 변경 후 다시 리뷰요청 부탁드립니다.

감사합니다!

2023-11-15 11:45 UTC, Flamme1004K commented on src/test/kotlin/study/DslTest.kt
> +class DslTestKotest : FunSpec({
테스트 검증 대상이 아래와 같은 DSL로 표현되어야 할 것 같은데, 상이한 것 같아요

```
  PersonDslTestData(
                    "홍길동",
                    "활빈당",
                    listOf("착한 마음씨", "호형호제 못함"),
                    listOf("전투", "곳간 털기"),
                    listOf(Pair("Korean", 5), Pair("English", 0))
                )
```

가 아닌,

```kotlin
introduce {
  name("박재성")
  company("우아한형제들")
  skills {
    soft("A passion for problem solving")
    soft("Good communication skills")
    hard("Kotlin")
  }
  languages {
    "Korean" level 5
    "English" level 3
  }
}
```

으로 변경해보시길 바래요!

2023-11-15 12:01 UTC, 10000001a commented on src/test/kotlin/study/DslTest.kt
> +class DslTestKotest : FunSpec({
리뷰 감사합니다!

`PersonDslTestData`의 의도는 `withData`를 사용해서 ParameterizedTest를 시도하려고 했는데요,
그 부분을 DSL로 변경하면 테스트는 이미 완성된 Person 객체를 가지게 될 것 같아요.
그렇게 되었을 때, 테스트 내부에서는 Person의 필드가 잘 존재하는지만 확인하면 되는 것일까요..?

2023-11-17 05:47 UTC, Flamme1004K approved these changes
안녕하세요!

1단계 미션 고생하셨습니다! 머지하도록 하겠습니다!

본격적인 블랙잭 미션이네요! 화이팅입니다!

2023-11-17 05:47 UTC, Flamme1004K commented on src/test/kotlin/study/DslTest.kt
> +class DslTest : FunSpec({
테스트 케이스 잘 반영 해주셨군요 👍

2023-11-17 05:47 UTC, Flamme1004K commented on src/test/kotlin/study/DslTest.kt
> +        }
kotest의 [collection-matchers](https://kotest.io/docs/assertions/collection-matchers.html)를 사용해 보는 건 어떨까요~?

2023-11-17 05:48 UTC, merged