[step3] 🚀 3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #655
Opened 2023-11-24 03:10 UTC by jaeyeonme

안녕하세요. 리뷰어님.
`상속을 활용해 중복을 제거해 본다.` 를 추상클래스로 구현해보았습니다.

2023-11-24 23:42 UTC, hjjae2 requested changes
안녕하세요, 재연님!

몇 가지 코멘트 남겼는데요, 확인 한번 부탁드립니다! 🙇

2023-11-24 23:42 UTC, hjjae2 commented on src/main/kotlin/domain/Dealer.kt
> +    fun playDealerTurn(deck: Deck) {
테스트 코드를 위해 만들어진 메서드일까요? 프로덕션 코드에선 사용처가 없는 것 같은데, 지워도 되는 메서드일까요?

2023-11-24 23:42 UTC, hjjae2 commented on src/main/kotlin/enum/GameResult.kt
> +        fun determine(playerScore: Int, dealerScore: Int, maximumScore: Int): GameResult {
이 기능에 대한 테스트 코드도 작성되면 좋겠네요! 👍

2023-11-24 23:42 UTC, hjjae2 commented on src/main/kotlin/enum/GameResult.kt
> +        fun determine(playerScore: Int, dealerScore: Int, maximumScore: Int): GameResult {
사소한 의견입니다! maximumScore 는 인자로 받을 필요가 있을까요? 

(`MAXIMUM_SCORE` 만 사용되고 있고, 이 값만 사용될 
 것으로 예상되기에)`MAXIMUM_SCORE` 를 그대로 사용해볼 순 없을까요?

maximumScore 값 변경에 대해 용이할 수 있겠지만, 이 값은 변경의 가능성이 적고 인자에 잘못된 값이 들어올 수 있는 여지가 생긴 것 같아 이점이 있어보이지는 않네요. 🤔

2023-11-24 23:42 UTC, hjjae2 commented on src/main/kotlin/enum/GameResult.kt
> +            }
게임의 결과는 Player 중심으로 계산이 되는군요. 다만, GameResult 라는 네이밍으로부터는 이 의도(= Player 중심으로 계산이 되는지)를 파악하기 어려워 보입니다. 

이를 개선해볼 수 있을까요? 🤔

2023-11-24 23:42 UTC, hjjae2 commented on src/main/kotlin/domain/Player.kt
> +    var result: GameResult = GameResult.DRAW
setter 에 대한 접근을 private 으로 제한해볼까요? 

혹은 위 코멘트와 관련지어 Player 가 result 를 반환하는 형태로 구성해보는 것도 생각해볼 수 있겠네요!

2023-11-25 06:46 UTC, jaeyeonme commented on src/main/kotlin/enum/GameResult.kt
> +    DRAW("무승부");
네 출력을 위해 추가된 속성입니다. view 쪽에서 처리를 해주려고 했는데, 이 부분도 하드코딩이 되지 않을까 생각해서 추가해줬던 것 이었습니다.

2023-11-25 06:56 UTC, jaeyeonme commented on src/main/kotlin/domain/Dealer.kt
> +    fun playDealerTurn(deck: Deck) {
프로덕션 코드에서는 사용하고 있지 않는 코드로 되어 버렸군요. 이것도 리팩토링 해보겠습니다.

2023-11-25 07:09 UTC, jaeyeonme commented on src/main/kotlin/enum/GameResult.kt
> +        fun determine(playerScore: Int, dealerScore: Int, maximumScore: Int): GameResult {
변경 가능성이 적다면 이점이 있어보이지는 않네요! 이 부분도 리팩토링 해보겠습니다.

2023-11-25 07:14 UTC, jaeyeonme commented on src/main/kotlin/enum/GameResult.kt
> +            }
메소드 네이밍을 개선해보겠습니다.

2023-11-25 07:20 UTC, jaeyeonme commented on src/main/kotlin/domain/Player.kt
> +    var result: GameResult = GameResult.DRAW
넵 이것도 리팩토링 해보겠습니다.

2023-11-25 07:25 UTC, jaeyeonme commented
안녕하세요. 리뷰어님!
프로덕션에서 사용하고 있지 않은 코드를 `메서드를 프로덕션 코드로 통합` 으로 진행하였습니다.

2023-11-25 09:45 UTC, jaeyeonme commented on src/main/kotlin/enum/GameResult.kt
> +    DRAW("무승부");
다시 view 쪽으로 옮기는 방향으로 리팩토링 했습니다.

2023-11-26 06:26 UTC, hjjae2 approved these changes
안녕하세요, 재연님!

의견 드린 부분에 대해서 잘 반영해주셨네요. 👍 

코멘트 남긴 내용이 있는데요, 다음 미션에서 함께 확인 부탁드릴게요! 고생하셨습니다. 🙇

2023-11-26 06:26 UTC, hjjae2 commented on src/main/kotlin/domain/Player.kt
> +        get() = matchResult
[private set](https://kotlinlang.org/docs/properties.html#getters-and-setters) 을 이용해 볼 수 있겠네요!

```kotlin
    var result: GameResult = GameResult.DRAW
        private set
```

2023-11-26 06:26 UTC, merged

2023-11-26 08:15 UTC, jaeyeonme commented on src/main/kotlin/domain/Player.kt
> +        get() = matchResult
이 부분도 개선해보겠습니다!