Step3 - 블랙잭(딜러) 구현
next-step/kotlin-blackjack pull request #658
Opened 2023-11-24 18:49 UTC by Yunho-Park

2023-11-25 17:38 UTC, MyStoryG requested changes
윤호님 안녕하세요.
3단계 구현 잘해주셨네요! 👍 
몇 가지 코멘트 남겼으니 확인 후 다시 리뷰 요청 부탁 드리겠습니다.

2023-11-25 17:38 UTC, MyStoryG commented on src/main/kotlin/blackjack/domain/Player.kt
> +        private set
프로그래밍 요구 사항에 아래와 같은 항목이 있습니다.
이 요구 사항을 만족 시켜보면 어떨까요?

> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

2023-11-25 17:38 UTC, MyStoryG commented on src/main/kotlin/blackjack/domain/Dealer.kt
>          val card = stack.draw() ?: throw IllegalStateException("카드가 부족합니다.")
카드가 부족하다는 안내는 딜러의 역할이기 보다는 CardBundle이 더 적합할 것 같습니다.

2023-11-25 17:38 UTC, MyStoryG commented on src/test/kotlin/blackjack/domain/BlackjackUtilTest.kt
> +    @ValueSource(ints = [1, 21, 22])
1인 경우도 테스트 해주셨네요!
다만 실제로 1인 경우는 없을 것 같아요.

2023-11-25 17:38 UTC, MyStoryG commented on src/test/kotlin/blackjack/domain/BlackjackUtilTest.kt
> +    @CsvSource(value = ["21,1,true", "1,21,false"])
이 경우도 해당 테스트에 부합하는 데이터가 맞긴 하지만 앞선 테스트에서 별도로 검증되는 특별한 값인 것 같아요. 다른 데이터 값으로 진행해 보는 것도 좋을 것 같네요.

2023-11-25 17:38 UTC, MyStoryG commented on src/test/kotlin/blackjack/domain/DealerTest.kt
> +        Assertions.assertThat(player.canDrawMore()).isFalse()
여러 케이스에 대해서 테스트하실 때는 assertAll 키워드를 사용해 보시면 좋을 것 같아요.

참고 : https://velog.io/@ki960213/assertThat-vs-assertAll-vs-assertSoftly

2023-11-26 14:44 UTC, Yunho-Park commented on src/main/kotlin/blackjack/view/Output.kt
> +    }
반영했습니다 [14a376f](https://github.com/next-step/kotlin-blackjack/pull/658/commits/14a376f678bcb87cb6d69db9118fd677dfb8d330)

2023-11-26 15:02 UTC, Yunho-Park commented on src/main/kotlin/blackjack/view/Output.kt
> +    println("${dealer.name}: ${buildDealerResult(players)}")
유저의 승/패를 반전시키지 않은채로 딜러의 승/패로 카운트했네요 수정했습니다 [e81bd9d](https://github.com/next-step/kotlin-blackjack/pull/658/commits/e81bd9d3888c94536e19f56baab6d9688c89bf4a)

2023-11-26 15:05 UTC, Yunho-Park commented on src/main/kotlin/blackjack/domain/BlackjackUtil.kt
> +        if (playerScore == dealerScore) return null
반영했습니다 [ee2426d](https://github.com/next-step/kotlin-blackjack/pull/658/commits/ee2426dc82f30ccf1ba00fe3ae9b7e64bfc2f117)

2023-11-26 15:20 UTC, Yunho-Park commented on src/main/kotlin/blackjack/controller/BlackjackMain.kt
>      }
반영했습니다 [eae3238](https://github.com/next-step/kotlin-blackjack/pull/658/commits/eae3238794056fe8b8b8c68f81f57c83df4c53d9)

2023-11-26 15:22 UTC, Yunho-Park commented on src/main/kotlin/blackjack/domain/BlackjackUtil.kt
> +    const val DEALER_DRAW_THRESHOLD = 16
반영했습니다 [97e7031](https://github.com/next-step/kotlin-blackjack/pull/658/commits/97e70317b5ce434d915f36363dd8792b7ef01163)

2023-11-26 15:57 UTC, Yunho-Park commented on src/main/kotlin/blackjack/domain/Player.kt
> +        private set
점수와 결과를 하나로 묶으면 어떻게든 3개로는 줄일 수 있겠는데요,
2개로는... 점수랑 결과를 매번 다시 계산해야 가능할것같습니다.

어디 저장하려면 `Pair<Player, Int>` 나 `Pair<Player, Result>` 를 써서 컨트롤러가 가지고 있을수는 있겠지만,
Pair의 first와 second가 무엇인지 바로 알기 어렵다는점에서 가급적 피하고싶은 형태입니다

괜찮은 방법이 있을까요?

2023-11-26 16:04 UTC, Yunho-Park commented on src/main/kotlin/blackjack/domain/Dealer.kt
>          val card = stack.draw() ?: throw IllegalStateException("카드가 부족합니다.")
반영했습니다 [2e98942](https://github.com/next-step/kotlin-blackjack/pull/658/commits/2e98942bf7ccd666b9806510fb017b94ec8f8e22)

2023-11-26 16:09 UTC, Yunho-Park commented on src/test/kotlin/blackjack/domain/BlackjackUtilTest.kt
> +    @ValueSource(ints = [1, 21, 22])
아래 피드백과 같이 반영했습니다 [40acf77](https://github.com/next-step/kotlin-blackjack/pull/658/commits/40acf77475ce600b22ea38a63fa738df0bef9930)

2023-11-26 16:25 UTC, Yunho-Park commented on src/test/kotlin/blackjack/domain/DealerTest.kt
> +        Assertions.assertThat(player.canDrawMore()).isFalse()
오 좋은 기능이네요 반영했습니다 [1dece6a](https://github.com/next-step/kotlin-blackjack/pull/658/commits/1dece6aa9d63f8df052ab9cbe9591fa1b50ad6f2)

2023-11-27 10:33 UTC, MyStoryG commented on src/main/kotlin/blackjack/domain/Player.kt
> +        private set
묶을만한 데이터에 대한 새로운 데이터 타입을 정의해도 좋을 것 같네요. 개인적으로는 반드시 모든 것을 반영해야 하기 보다는 지금처럼 윤호님이 생각하시기에 더 나은 구조라면 유지해도 좋을 것 같아요.
요구 사항이긴 하지만 윤호님이 줄일 수 있는 방법에 대해 고민한 것만으로도 충분히 요구 사항에 대한 학습이 된 것 같다고 생각합니다.

2023-11-27 10:35 UTC, MyStoryG approved these changes
윤호님 안녕하세요!
피드백 반영 잘 해주셨습니다!
질문주신 내용은 해당 코멘트에 남겼습니다.
마지막 4단계도 화이팅입니다!

2023-11-27 10:35 UTC, merged