🚀 4단계 - 블랙잭(베팅)
next-step/kotlin-blackjack pull request #669
Opened 2023-11-26 16:44 UTC by mins99

안녕하세요 리뷰어님! 3단계 리뷰를 반영하고 4단계 미션을 진행하여 리뷰 요청 드립니다~!
블랙잭 게임 자체가 낯설어서 그런지 여전히 규칙과 관련해서 잘 이해한게 맞는지 헷갈리네요ㅠㅠ
4단계도 베팅 금액을 어떻게 봐야 할지 조금 헷갈려서 우선 제가 이해한 대로 작성했습니다. 놓친 케이스가 있다면 편하게 말씀주세요~

### 베팅 금액 규칙
- 플레이어만 블랙잭인 경우 플레이어는 베팅금액의 1.5배를 돌려받는다
- 딜러와 플레이어가 동시에 블랙잭인 경우 플레이어는 베팅금액을 돌려받는다
- 딜러가 21을 초과하는 경우 그 시점까지 남아있던 플레이어들은 베팅 금액을 돌려받는다
- 그 외의 경우에는 베팅 금액을 잃는다

그나저나 드디어 블랙잭 마지막 미션이네요! 잘 부탁드립니다 🙇

2023-11-26 16:46 UTC, mins99 commented on src/test/kotlin/blackjack/model/game/MatchResultTest.kt
> +            }
https://github.com/next-step/kotlin-blackjack/pull/650#discussion_r1403604407 의견 주셨던 부분 반영하니 테스트 코드도 훨씬 깔끔해져서 너무 뿌듯 만족입니다 😍

2023-11-26 16:47 UTC, mins99 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +        this(name, bettingAmount, Hit(cards))
베팅금액을 어떤 타입으로 할지 고민이 있었는데 1원을 베팅해서 블랙잭이 되는 경우 1.5원을 받게 되어 Double 로 했습니다

2023-11-26 16:48 UTC, mins99 commented on README.md
> +- [x] 게임을 완료한 후 각 플레이어별로 승패를 출력한다.
놓쳤던 구현사항 체크도 추가 +_+

2023-11-27 08:58 UTC, pci2676 requested changes
설계 자체를 워낙 잘 해주셔서 이번 단계도 수월하게 작성해주신것 같습니다.

조금 개선해 볼 부분에 리뷰를 남겨두었으니 확인해주세요.

2023-11-27 08:58 UTC, pci2676 commented on src/main/kotlin/blackjack/model/game/BettingResult.kt
> +        }
이 메서드는 MatchResult내에서 제공할 수 있을것 같아보입니다.

혹시 이곳에 구현하신 이유가 있으실까요?

2023-11-27 08:58 UTC, pci2676 commented on src/main/kotlin/blackjack/controller/BlackjackController.kt
> +        }
조금 욕심을 내보면 좋을것 같습니다.

players를 일급컬렉션으로 관리하여 구현해보시면 어떨까요?

2023-11-27 08:58 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Dealer.kt
>          private const val SIXTEEN = 16
앗 제가 놓친 부분이 있어 남겨둡니다.

16을 상수로 표현할때는 상수로서 의미의 전달이 중요합니다.

그러나 '16'을 '십육'으로 표현해서는 16이라는 숫자가 코드에서 어떤 의미를 갖는지 표현하기 쉽지 않아보입니다.

16이 정확히 무슨 의미를 뜻하는지를 드러내는것이 좋고 만약 그 정도로 의미가 없다면 굳이 상수로 추출을 안해도 된다고 저는 생각합니다.

2023-11-27 08:58 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Dealer.kt
> +            isDrawCondition(player) -> Rank.DRAW
굳이 변경안하셔도 되지만 확장함수를 이용하여 아래와 같이 표현하는 것도 하나의 방법입니다.

https://kotlinlang.org/docs/extensions.html

```suggestion
            player.isWinningCondition() -> Rank.WIN
            player.isDrawCondition() -> Rank.DRAW
```

2023-11-27 08:58 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +    fun isNotBust() = state !is Bust
이 부분도 제가 놓쳤던 부분이네요..

객체 지향적으로 코드를 작성할때는 is를 이용하여 객체의 타입을 직접 추론하는 부분은 가능한 지양해서 작성하시는 것을 추천드립니다.

인터페이스로 구현체를 캡슐화 해둔 부분이 노출됩니다.

2023-11-27 08:58 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
>3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

이번 프로그래밍 요구사항을 준수해보시면 좋을것 같습니다. 😄

2023-11-27 14:32 UTC, mins99 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
이 부분에 있어 조금 고민이 되어서 남겨봅니다!

변수를 줄이기 위해서 현재 구조에서 name, bettingAmount(혹은 state) 를 가지는 객체를 하나 더 만들어야 할 것 같은데요,
이 경우에 수정해야하는 부분이 너무나 많아지고, 구현상 depth 가 깊어져서 저는 오버엔지니어링으로 느껴집니다.
사실상 name과 bettingAmount 값은 내부 로직이 있는 것도 아니어서 변수가 과하다고 생각이 들지도 않구요.
리뷰어님이 생각하시는 적절한 분리 방향이 있으실까요~?

2023-11-27 15:32 UTC, mins99 commented on src/main/kotlin/blackjack/model/game/BettingResult.kt
> +        }
MatchResult 의 역할이 많아지는건 아닌가 해서 별도의 클래스를 두었었습니다
[7780288](https://github.com/next-step/kotlin-blackjack/pull/669/commits/7780288ccffef2f319b45dce8fd6ad0a08e3d2ab)에 합친 로직으로 수정해보았습니다!

2023-11-27 15:33 UTC, mins99 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +    fun isNotBust() = state !is Bust
[284ce9e](https://github.com/next-step/kotlin-blackjack/pull/669/commits/284ce9ecbd6450d873a543f69b9a43769c8ebfa1) 에 반영했습니다
isBust, isBlackJack, isStay 를 모든 State 의 구현체에 작성했는데 상태패턴인 경우 어쩔 수 없이 써야 하는거겠죠..?

2023-11-28 02:56 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
>이 경우에 수정해야하는 부분이 너무나 많아지고, 구현상 depth 가 깊어져서 저는 오버엔지니어링으로 느껴집니다.
사실상 name과 bettingAmount 값은 내부 로직이 있는 것도 아니어서 변수가 과하다고 생각이 들지도 않구요.

이 부분은 저도 사실 동감하는데요 😅 

아무래도 이 프로그램은 교육이 목표이니 한번쯤 지켜서 해보면서 실제로 좋아하지는지 나빠지는지 더 좋은 방법은 없었을지를 고민해보는것도 좋은 포인트가 될 것 같아 추천드리는 바입니다.

그래서 state를 가지고 하는 행위가 딜러와 참여자가 조금 겹치는 부분 있으니 이를 하나의 클래스로 추상화해서 제공하는 방법도 있을것 같습니다.

추가로 bettingAmount를 이용하여 상금을 계산하는 로직은 Player내부로 제공하는것도 고민해볼만 하네요

2023-11-28 02:57 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
위 부분에 대한 의견을 코멘트로 한번만 남겨주시면 이번미션은 종료해도 될 것 같습니다 😄 

워낙 설계를 잘해주셔서 더 코멘트를 드릴 부분이 없네요

2023-11-28 08:19 UTC, pci2676 requested changes
코멘트로 남겨둔 부분에 대해 답변주시면 바로 머지할 수 있을것 같네요!

확인 부탁드립니다

2023-11-30 14:21 UTC, mins99 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
안녕하세요 리뷰어님! 코멘트 보고나서 계속 고민이 생겨 이것 저것 시도 중이라 답변이 늦어지고 있네요~! 
공식 리뷰 기간 끝나기 전까지만 고민 조금 더 해보고 답변 남겨도 될까요? ㅎㅎ
화요일에 수업으로 피드백 받고 혼자 이렇게 저렇게 수정해보는 중입니다 하핫;;
아무쪼록 늦지않게 답변(혹은 피드백 반영?) 남기겠습니다! 정말이지 어려운 미션이네요.. 😂

2023-12-04 14:14 UTC, mins99 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
안녕하세요 리뷰어님~! 정말 정말 너무 늦게 답변을 달게 되어 우선 죄송합니다 흑흑..
결론을 먼저 말씀드리자면,, 다양하게 고민도 해보고 조금씩 수정도 해보았는데, 시간적 여유가 없어서 완성하지는 못했습니다 😢 
아직 남은 지뢰찾기 미션도 있고 해서ㅠㅠ 공식적인 리뷰 요청은 여기서 마무리 하고 싶어요.

그치만 시간이 남으면(추후에 없는 시간을 만들어서라도..!) 변수 줄이는 건 혼자서 도전해보겠습니다!
그동안 좋은 리뷰 주셔서 너무 감사드립니다 🙇 리뷰어님 덕분에 많이 배울 수 있었습니다!

2023-12-05 00:51 UTC, pci2676 commented on src/main/kotlin/blackjack/model/player/Player.kt
> +data class Player(val name: String, val bettingAmount: Double = 0.0, var state: State) {
저도 리뷰가 재미있었습니다.  
그 동안 고생 많으셨습니다 😄

2023-12-05 00:52 UTC, pci2676 approved these changes
즐거운 리뷰였습니다!

그동안 고생 많으셨습니다 😄

2023-12-05 00:52 UTC, merged