[step4] 블랙잭 베팅
next-step/kotlin-blackjack pull request #684
Opened 2023-11-29 15:34 UTC by Ahn-seokjoo

베팅 가능 추가입니다.

2023-11-30 13:39 UTC, sah3122 requested changes
마지막 미션도 구현 잘해주셨습니다 👍 
이대로 마무리하기 아쉬워 사소한 생각거리를 남겨두었는데 확인 부탁드려요 😄

2023-11-30 13:39 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/entity/AllParticipantWithBetAmount.kt
> +class AllParticipantWithBetAmount(
해당 클래스의 역할이 어떤것일까요 ? 
`ParticipantNamesWithBetAmount`과 같은 클래스는 entity로 정의하기 보단 입력값을 전달해주는 dto 로 정의하는것이 적절한것 같습니다 😄

2023-11-30 13:39 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/ui/InputValueValidator.kt
> +fun Int.validateBetAmountValue() {
베팀 금액 클래스를 정의하여 유효성 검사를 추가해보는건 어떨까요 ?

2023-11-30 13:39 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/entity/state/ParticipantResultState.kt
> +    WIN("승"), LOSE("패"), DRAW("무"), BLACKJACK("블랙잭");
ParticipantResultState enum 에서 승 / 무 / 패에 대한 베팅 금액 정보를 담고 있는것도 좋을것 같아요 😄 
BLACKJACK 과 같은 정보는 승 / 패에 관련된 정보가 아닌 플레이어의 상태또는 점수에 대한 정보인것 같습니다. 
현재 정의되어 있는 GameCurrentState를 활용해보는건 어떨까요 ?

2023-11-30 13:39 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/entity/Participants.kt
> +    fun getParticipantsLoss(dealer: Dealer): Int = participants.sumOf { it.getResultBetAmount(dealer) } * -1
딜러의 베팅금액 결과를 제공하는 기능은 딜러 클래스가 제공해주는것이 어떨까요 ?

2023-11-30 13:39 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/domain/Participant.kt
> +        }
BLACKJACK 의 경우는 승리한 상황에서 계산되는 특별한 케이스 일것 같아요 😄

2023-11-30 13:39 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/entity/BlackJackGamer.kt
> +        participants.forEach { participant ->
이번 미션은 객체지향 생활체조의 원칙을 지켜야 합니다 😄 
들여쓰기는 1까지만 허용하여 들여쓰기가 충접되어 있는 부분을 의미있는 메서드로 분리해보면 좋을것 같아요 👍

2023-11-30 13:39 UTC, sah3122 commented on src/test/kotlin/blackjack_dealer/BetAmountTest.kt
> +class BetAmountTest : StringSpec({
개인적으로 테스트 코드는 클래스를 기준으로 작성하곤 합니다. 
베팅 금액에 관련된 테스트는 참가자 또는 딜러 테스트 코드에 추가하는것이 적절할것 같아요 😄

2023-11-30 15:23 UTC, Ahn-seokjoo commented on src/main/kotlin/blackjack_dealer/ui/InputValueValidator.kt
> +fun Int.validateBetAmountValue() {
49a24fad4758785351ae716e32a7e461fa8549b2 수정해보았습니다

2023-11-30 15:31 UTC, Ahn-seokjoo commented on src/test/kotlin/blackjack_dealer/BetAmountTest.kt
> +class BetAmountTest : StringSpec({
18282ed8501ff2853ca37be437ca61b6c945fdb6 맞는 것 같네요 ㅠ 동의합니다

2023-11-30 15:32 UTC, Ahn-seokjoo commented on src/main/kotlin/blackjack_dealer/domain/Participant.kt
> +        }
유저가 블랙잭이고, 딜러도 블랙잭이면 무승부가 나올수 있지 않나요 ?? 항상 승리 케이스이진 않을 것 같아서요 !

2023-11-30 16:06 UTC, Ahn-seokjoo commented on src/main/kotlin/blackjack_dealer/entity/state/ParticipantResultState.kt
> +    WIN("승"), LOSE("패"), DRAW("무"), BLACKJACK("블랙잭");
1345c30c69e99ddbb41cf31fa805419094fcd565 리뷰대로 수정했더니 더 깔끔해졌네요~ 확인 부탁드립니다 !

2023-12-01 13:37 UTC, sah3122 approved these changes
마지막 피드백까지 반영 잘해주셨습니다 👍 
그동안 적지않은 피드백 반영해주신다고 너무 고생많으셨어요. 💯 
블랙잭 미션은 여기서 마무리 짓도록 할게요 🙏 
미션이 종료되어도 궁금한점이나 함께 의논하고 싶은 내용이 있다면 언제든 편하게 DM 주시면 됩니다 !

2023-12-01 13:37 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/domain/Dealer.kt
> +    fun getDealerProfits(participants: Participants): Int = participants.sumOf { it.getResultBetAmount(this) } * -1
피드백반영 👍

2023-12-01 13:37 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/entity/BlackJackGamer.kt
> +            doBlackJackForEachParticipant(
메서드 분리 👍

2023-12-01 13:37 UTC, sah3122 commented on src/main/kotlin/blackjack_dealer/entity/state/ParticipantResultState.kt
> +enum class ParticipantResultState(val state: String, val multiplyNumber: Int) {
multiplyNumber 보단 `수익률`이라는 의미를 나타내면 더 좋을것 같습니다 !

2023-12-01 13:38 UTC, merged