STEP4: 블랙잭(배팅)
next-step/kotlin-blackjack pull request #686
Opened 2023-11-29 16:15 UTC by wooddy-kim

## 작업내역
- 플레이어의 배팅 금액을 입력받아 최종 수익을 출력하도록 구성
- 플레이어가 블랙잭인 경우 배팅 금액의 1.5 배율 적용

## 리뷰 포인트
이전 구조에서 큰 변화는 없고 `GameReward` 라는 객체를 추가하여 수익을 나타낼 수 있도록 구성해보았습니다.

사실 이전 리뷰에서 코멘트 주셨던 부분을 반영해보려고 했는데요. 
블랙잭 룰 및 관련된 용어들에 대해서 익숙하지 않다보니 만족스럽지 못한 코드가 작성되더라고요.
그래서 작성된 코드는 롤백하고 현 요구사항만 만족할 수 있는 코드를 새롭게 작성했습니다.

2023-12-01 13:08 UTC, kyucumber requested changes
안녕하세요.
제가 리뷰 알람을 놓쳐서 리뷰를 굉장히 늦게 남겨드렸네요. 죄송합니다.

간단한 몇가지 코멘트 남겨두었습니다. 다음 요청 시 머지하도록 할게요. 마지막까지 수고 많으셨습니다.

2023-12-01 13:08 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/Amount.kt
> +    fun multiply(ratio: Double): Amount = Amount(value * ratio)
중요한 부분은 아닌데요, operator overloading으로 표현해볼수도 있을 것 같네요~

https://kotlinlang.org/docs/operator-overloading.html#binary-operations

2023-12-01 13:08 UTC, kyucumber commented on src/main/kotlin/blackjack/domain/GameReward.kt
> +sealed interface GameReward {
GameReward와 관련된 부분 단위 테스트가 작성되면 좋았을 것 같아요.

2023-12-03 14:16 UTC, wooddy-kim commented
@kyucumber 
리워드 클래스 단위 테스트가 누락되어 추가했습니다.
연산자 오버라이딩은 적절한 걸 찾지 못하였는데요. 어떤 연산자를 사용하는 게 좋을까요?

블랙잭 미션 진행하는 동안 꼼꼼하게 리뷰해주셔서 큰 도움이 되었습니다
감사합니다👍

2023-12-04 13:59 UTC, kyucumber commented
마지막에 알림을 못 봐서 리뷰가 다소 늦었는데요. 다시 한번 죄송하다고 말씀드리고 싶네요. 😭

2023-12-04 14:00 UTC, merged