[Step2] 블랙잭
next-step/kotlin-blackjack pull request #739
Opened 2024-11-29 15:40 UTC by eunice0035

블랙잭 게임을 잘 이해하지 못해서 구현하는데 생각보다 오래걸렸네요ㅠ

2024-11-30 12:18 UTC, Wordbe requested changes
콜백기반 이벤트 핸들링이 인상깊네요 😀
어떤 의도로 이 구조를 선택했는지 한번 설명해주실 수 있을까요?

나머지 코멘트 드린 부분도 한 번 읽고 보시고, 가능하신 부분은 반영 부탁드립니다 😀

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/ui/InputView.kt
> +    fun printCardDrawMessage(name: String) {
새로운 카드를 받고, 결과를 출력하는 것인데, print~ 라고 명명되어 조금 헷갈릴 수 있어보이네요 🧐

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Card.kt
> +        if (SpecialNumber.entries.any { it.name == number }) {
반대의 조건을 걸어서 early return 하면 가독성이 좀 더 좋아질 수 있을 것 같아요 😀

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Game.kt
> +    fun initTurn(onPrintResultCallback: ((List<Player>) -> Unit)) {
외부에서 사용하지 않으니 감춰볼까요? 😀

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Card.kt
> +data class Card(val number: String, val symbol: SYMBOL) {
카드는 2~10 숫자만 올 수 있으니, 그런 검증이 필요해보이고 
그 카드들은 한번 생성되면 게임이 종료될때까지 바뀌지는 않으니 각각을 고유한 하나의 인스턴스로 미리 만들어놔도 좋을것 같아요 🙂

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/CardDeckStrategy.kt
> +interface CardDeckStrategy {
(옵션)
전략이라는 말보다 간단하게 Deck 이라고 하셔도 괜찮을 것 같다는 생각이 드네요.

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Game.kt
> +    fun startTurn(
여기두요 🙂

2024-11-30 12:18 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/Game.kt
> +        while (!currentPlayer.isDone() && onTurnStarted(currentPlayer) == "y") {
y 를 상수로 만들어볼까요? 😀

2024-11-30 12:18 UTC, Wordbe commented on src/test/kotlin/blackjack/domain/GameTest.kt
> +}
구현이 되지 않았네요 😲

2024-12-01 10:52 UTC, eunice0035 commented on src/main/kotlin/blackjack/ui/InputView.kt
> +    fun printCardDrawMessage(name: String) {
밑의 getUserAnswer와 통일성을 맞추기 위해 setUserAnswer로 수정했습니다.

2024-12-01 10:53 UTC, eunice0035 commented on src/main/kotlin/blackjack/domain/Card.kt
> +        if (SpecialNumber.entries.any { it.name == number }) {
any가 아니라 none 조건을 확인하도록 변경했습니다!

2024-12-01 10:54 UTC, eunice0035 commented on src/main/kotlin/blackjack/domain/Card.kt
> +data class Card(val number: String, val symbol: SYMBOL) {
미리 카드들을 인스턴스로 만들어놓게 했습니다!
Card 클래스의 생성자를 private으로 만들고, createCard를 통해서만 카드를 받을 수 있도록 수정했습니다~

2024-12-01 11:00 UTC, eunice0035 commented
> 콜백기반 이벤트 핸들링이 인상깊네요 😀 어떤 의도로 이 구조를 선택했는지 한번 설명해주실 수 있을까요?

UI layer에서 Model layer 사이의 의존성을 없애고 싶어서 콜백 구조를 사용했습니다. 모델이나 UI 단에서 변경이나 수정이  필요할 경우 좀 더 쉽게 수정할 수 있을 것 같아서 해당 구조를 사용했습니다.

2024-12-01 12:30 UTC, Wordbe approved these changes
고생하셨습니다 잘 반영해주셨네요!
다음 스텝으로 넘어가시죠 🚀🚀🚀

2024-12-01 12:30 UTC, merged