[Step2
next-step/kotlin-blackjack pull request #759
Opened 2024-12-02 05:07 UTC by Seokho-Ham

2024-12-02 11:15 UTC, wisemuji requested changes
안녕하세요 석호님!

어려운 블랙잭 2단계 구현을 너무 잘 해주셨습니다 💯 깔끔한 구현이 좋았습니다
다음 단계로 넘어가기 전에 먼저 고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다!

2024-12-02 11:15 UTC, wisemuji commented on README.md
기능 목록을 잘 정리해주셨습니다 👍
이상적으로는 이렇게 작성하신 기능 목록이 결국에는 커밋 단위, 테스트 시나리오까지 이어지면 좋습니다.

2024-12-02 11:15 UTC, wisemuji commented on README.md
다음을 참고하여 블랙잭 게임에 대한 이해도를 높여보면 어떨까요?

- [high1.com/casino/contents.do?key=1764](https://www.high1.com/casino/contents.do?key=1764)
- [namu.wiki/w/블랙잭(카드게임)](https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84))

예를 들어 bust, stay, blackjack이라는 도메인 용어와 규칙을 적용해볼 수 있을 것 같아요 🙂

2024-12-02 11:15 UTC, wisemuji commented on src/main/kotlin/blackjack/BlackJackGame.kt
> +            players.forEach { player -> (1..2).forEach { _ -> player.addCard(deck.getSingleCard()) } }
Kotlin의 [repeat](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/repeat.html)을 적용해보면 어떨까요?

2024-12-02 11:15 UTC, wisemuji commented on src/main/kotlin/blackjack/CardMark.kt
> +}
도메인 객체에 뷰 요구사항이 포함되는게 적절할까요? 자동차 경주 5단계 요구사항을 참고하여 도메인 로직과 뷰 로직을 명확하게 분리하고, 의존 방향을 정리해보시면 좋을 것 같아요 🙂 

![image](https://github.com/user-attachments/assets/ccf970ed-3ebd-4405-b95a-ab2e6fb76e3e)

2024-12-02 11:15 UTC, wisemuji commented on src/main/kotlin/blackjack/Deck.kt
> +            }.toMutableList()
"과연 블랙잭 게임에서 생성될 수 있는 카드의 경우의 수가 몇 개인지"를 고려하여 사전에 카드를 만들어두는 전략을 구현해주셨네요!

2024-12-02 11:15 UTC, wisemuji commented on src/test/kotlin/blackjack/PlayerTest.kt
> +        player.addCard(createBasicCard(CardNumber.TEN, CardMark.HEART))
아래와 같이 생성자 파라미터(프로퍼티 아님)를 활용하면 테스트 코드 작성 시 전제 조건 주입을 더 쉽게 할 수 있습니다. 
```kotlin
class PlayerCards(cards: List<Card>) {
    // cards 초기화
}
```
테스트 코드 작성만을 위해서 생긴 코드라고 생각한다면 맘에 안 드는 변경사항일 수 있는데요, 석호님은 어떻게 생각하세요?

2024-12-02 11:15 UTC, wisemuji commented on src/main/kotlin/blackjack/Player.kt
> +        return false
테스트용 코드가 같이 커밋된 것 같습니다!

2024-12-02 11:15 UTC, wisemuji commented on src/main/kotlin/blackjack/PlayerCards.kt
> +        return cards.toList()
방어적 복사를 잘 활용해주셨네요 👍 

특히 코틀린에서는 다음과 같이 [backing property](https://kotlinlang.org/docs/properties.html#backing-properties)[로](https://kotlinlang.org/docs/properties.html#backing-properties)%EB%A1%9C) 작성하면 불변 타입만 외부에 공개하여 변경을 내부에 감출 수 있습니다.

예시:
```kotlin
    private val _tests: MutableList<String> = mutableListOf()
    val tests: List<String> get() = _tests.toList()
```

2024-12-02 11:15 UTC, wisemuji commented on src/main/kotlin/blackjack/PlayerCards.kt
> +            this.cards.add(card)
Deck의 getSingleCard 리턴 타임이 nullable하게 설계되어 있는데요, 덱의 카드가 모두 소진되었을 때 null을 리턴하는 상황이 어색하게 느껴지진 않을까요?

2024-12-02 11:15 UTC, wisemuji requested changes
안녕하세요 석호님!

어려운 블랙잭 2단계 구현을 너무 잘 해주셨습니다 💯 깔끔한 구현이 좋았습니다
다음 단계로 넘어가기 전에 먼저 고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다!

2024-12-05 07:20 UTC, Seokho-Ham commented on src/main/kotlin/blackjack/PlayerCards.kt
> +            this.cards.add(card)
이 부분에 대해서 궁금한게 있습니다!
코틀린에서는 보통 명시적으로 예외를 던지기보다는 null을 반환하도록 구현한다는 리뷰를 몇번 받았었는데 이런 상황에서는 Deck에서 예외를 그냥 던지는게 더 나을까요?
언제 null을 반환하고 언제 예외를 던져야할지 아직 감이 잘 안잡히네요😂

2024-12-05 07:23 UTC, Seokho-Ham commented on src/test/kotlin/blackjack/PlayerTest.kt
> +        player.addCard(createBasicCard(CardNumber.TEN, CardMark.HEART))
해당 테스트는 Player의 패를 추가하는 행위에 대한 테스트라서 PlayerCards의 생성자를 변경해야할까 싶습니다.🤔
내부에 여러개의 카드를 추가할 수 있는 메서드를 생성하도록 해보겠습니다!

2024-12-05 07:23 UTC, Seokho-Ham commented on src/main/kotlin/blackjack/CardMark.kt
> +}
지금 생각해보니 뷰에 대한 부분이네요. 개선해보겠습니다!😁

2024-12-05 07:25 UTC, Seokho-Ham commented on src/main/kotlin/blackjack/Player.kt
> +        return false
덕분에 코드의 허점을 찾았습니다..ㅎㅎ 변경하겠습니다!

2024-12-05 08:37 UTC, Seokho-Ham commented
안녕하세요 수현님!
피드백 바탕으로 작업 진행 후 리뷰 요청드립니다!

2024-12-05 12:59 UTC, wisemuji approved these changes
안녕하세요 석호님! 리뷰 반영을 넘 잘 해주셨습니다 💯

개인적으로 생각하는 블랙잭 미션의 꽃은 바로 다음 단계에서 딜러와 플레이어의 책임을 어떻게 나눌지 고민하는 과정에 있다고 생각해요!
동일한 역할과 책임처럼 보이지만, 블랙잭 도메인을 익히다 보면 미묘하게 다른 영역이 있는데요, 어떻게 나누면 좋을지에 초점을 맞춰 미션을 진행하시면 많은 것을 얻어가실 수 있을 것 같아요

다음 미션도 화이팅입니다 👍

2024-12-05 12:59 UTC, wisemuji commented on src/main/kotlin/blackjack/view/OutputView.kt
> +    private const val CLOVER_STR = "클로버"
뷰와 도메인 분리 👍

2024-12-05 12:59 UTC, wisemuji commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        )
구문의 가독성을 위해 [buildString](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/build-string.html)을 사용해보는 것도 고려해 보시면 어떨까요~?

2024-12-05 12:59 UTC, wisemuji commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        players.forEach { printPlayerCards(it) }
이러한 구문을 함수 reference로 넘길 수 있습니다.
```suggestion
        players.forEach(::printPlayerCards)
```
lambda로 작성하는 것과 어떤 차이가 있는지 참고할 수 있는 글을 소개해드릴게요 :slightly_smiling_face:
https://proandroiddev.com/kotlin-lambda-vs-method-reference-fdbd175f6845

참고로 저는 가능한 곳에서는 함수 reference를 활용하는 것을 지향합니다. lambda로 가져온 데이터를 별도로 조작하지 않고 그대로 함수 시그니처로 넘긴다는 것을 드러낼 수 있기 때문입니다.

2024-12-05 12:59 UTC, wisemuji commented on src/test/kotlin/blackjack/FixedDeck.kt
> +}
functional interface를 활용하면 아래와 같이 만들 수도 있겠군요!

장단점이 있으니 반영 여부는 석호님이 판단해주세요 🙂 

```suggestion
private val CACHED_CARDS =
    mutableListOf(
        Card(CardNumber.ACE, CardMark.HEART),
        Card(CardNumber.TEN, CardMark.HEART),
        Card(CardNumber.ACE, CardMark.HEART),
        Card(CardNumber.TEN, CardMark.HEART),
    )
    
fun fixedDeck() = Deck {
    CACHED_CARDS.removeLastOrNull()
}
```

2024-12-05 12:59 UTC, wisemuji commented on src/main/kotlin/blackjack/domain/PlayerCards.kt
> 코틀린에서는 보통 명시적으로 예외를 던지기보다는 null을 반환하도록 구현한다는 리뷰를 몇번 받았었는데 이런 상황에서는 Deck에서 예외를 그냥 던지는게 더 나을까요?
언제 null을 반환하고 언제 예외를 던져야할지 아직 감이 잘 안잡히네요😂

로또 미션 4단계 힌트 코드를 보면 아래와 같은 내용이 있습니다!
> 참고로 코틀린에서는 아래와 같이 예외 처리를 한다. 장기적으로는 아래와 같이 예외 처리하는 걸 연습해 본다.
논리적인 오류일 때만 예외를 던진다.
논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.
실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환한다.
일반적인 코틀린 코드에서 try-catch를 사용하지 않는다.

덱의 카드가 모두 소진된 경우는 어떤 예외 상황에 해당된다고 생각하시나요? 석호님의 의견이 궁금합니다!

2024-12-05 12:59 UTC, wisemuji commented on src/main/kotlin/blackjack/Main.kt
>      }
아래 요구사항도 반영되어야 할 것 같아요!
> indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

2024-12-05 12:59 UTC, wisemuji commented on src/main/kotlin/blackjack/Main.kt
> +            ) {
게임의 종료 조건을 판단하는건 컨트롤러에서 하는 것이 맞을까요? 
즉, 컨트롤러가 없다면 블랙잭 게임을 하지 못하려나요?

2024-12-05 12:59 UTC, merged

2024-12-05 14:47 UTC, Seokho-Ham commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        )
이런게 있었군요! 다음 미션에서 적용해보겠습니다!

2024-12-05 14:48 UTC, Seokho-Ham commented on src/main/kotlin/blackjack/view/OutputView.kt
> +        players.forEach { printPlayerCards(it) }
코틀린에서도 가능하다는걸 리뷰 통해서 알게 되었네요! 감사합니다:)

2024-12-05 14:58 UTC, Seokho-Ham commented on src/main/kotlin/blackjack/domain/PlayerCards.kt
Deck의 카드가 더이상 없는데 뽑으려고 하는건 논리적인 오류가 맞는것 같네요. 
대신 예외를 던지기보다는 sealed class를 반환하도록 해서 게임이 종료되도록 로직을 작성해보도록 하겠습니다!

참고한 글도 링크로 남겨봅니다.
https://elizarov.medium.com/kotlin-and-exceptions-8062f589d07

2024-12-05 15:00 UTC, seokho-ham commented on src/main/kotlin/blackjack/Main.kt
> +            ) {
안그래도 이부분은 코드를 작성하면서도 로직이 도메인 객체로 옮겨져야한다고 생각되었는데 좋은 방법을 떠올리지 못했습니다😅
다음 미션에서 한번 개선해보겠습니다!