2단계 - 블랙잭
next-step/kotlin-blackjack pull request #760
Opened 2024-12-02 12:47 UTC by eshc123

## 주요 내용
2단계 - 블랙잭 구현하였습니다.

감사합니다.

2024-12-02 15:13 UTC, Flamme1004K requested changes
안녕하세요!

2단계 미션 매우 잘 해주셨습니다. 몇 가지 코멘트 남겼으니 확인 후 다시 리뷰 요청 부탁드립니다.

화이팅입니다!

2024-12-02 15:13 UTC, Flamme1004K commented on README.md
> +2. 게임 시작 시 플레이어들에게 두 장의 카드를 지급받는다.
기능 요구사항 정리 잘해주셨어요!

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/CardsDeckGenerator.kt
> +}
카드 생성기 잘 해주셨네요!

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/BlackJackApplication.kt
> +class BlackJackApplication {
BlackJackApplication를 보면, BlackJackGame class으로 도메인을 분리할 수 있어 보여요. 🤔

도메인에서 분리된 BlackJackGame에서는 카드와 플레이어로 인해서 게임이 진행될 수 있다고 봅니다.

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/PlayerCardDeck.kt
> +    private val aceCards: MutableList<Card> = mutableListOf(),
같은 카드인데, cards와 aceCards를 두개로 나눈 이유를 알 수 있을까요?

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/PlayerCardDeck.kt
> +    fun addCard(card: Card) {
PlayerCardDeck에서도 17 이상이면 추가로 받지 못하는 로직이 있어야 하지 않을까 하네요~

2024-12-02 15:13 UTC, Flamme1004K commented on src/test/kotlin/blackjack/PlayerCardDeckTest.kt
> +                cards = mutableListOf(Card(CardNumber.JACK, CardSuit.CLOVER), Card(CardNumber.EIGHT, CardSuit.CLOVER)),
aceCards만 4개 넣은 경우에는 몇 점이 나와야 할까요?

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/Player.kt
> +data class Player(
전체적인 클래스 구조는 매우 잘 잡아주셨어요! 단, 예외가 발생할 구간이 몇몇 보이는데요. 예외에 대한 검증 코드이 없네요. 한번 예외가 발생할 수 있는 부분을 찾아 검증 로직을 추가해 보세요.

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/Player.kt
> +    }
블랙잭 게임에서는 합이 21이면 모두 블랙잭은 아니에요! 블랙잭 상태에 대해 알아보고, 코드를 변경해 볼까요?

2024-12-02 15:13 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/Player.kt
> +    fun findClosestToBlackJackNumber() = deck.findPossibleCardScores().minBy { (BLACK_JACK_NUMBER - it).absoluteValue }
가까운 숫자들을 반환하는 것보다, ACE 계산 로직을 리팩토링하여 스코어 하나만 주는 게 어떨까 하네요~

2024-12-06 13:18 UTC, eshc123 commented on src/main/kotlin/blackjack/domain/PlayerCardDeck.kt
> +    private val aceCards: MutableList<Card> = mutableListOf(),
ace 카드와 그외의 카드의 연산이 달라서 용이하게 하기 위함이었습니다.

2024-12-06 13:21 UTC, eshc123 commented on src/test/kotlin/blackjack/PlayerCardDeckTest.kt
> +                cards = mutableListOf(Card(CardNumber.JACK, CardSuit.CLOVER), Card(CardNumber.EIGHT, CardSuit.CLOVER)),
14점이 나와야 옳은건데 고려하지 못했습니다..!

2024-12-07 14:24 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/PlayerCardDeck.kt
> +    private val aceCards: MutableList<Card> = mutableListOf(),
그렇군요! 다 같은 카드인데, 두 개로 나누게 된다면, 현재로서는 괜찮지만 추후에는 aceCards에 다른 카드가 들어가는 코드가 만들어질 수 있어 보여요.

스코어링 로직을 변경하여 cards와 aceCards를 하나의 묶음으로 만들어보는 건 어떨까요?

2024-12-11 10:06 UTC, Flamme1004K approved these changes
안녕하세요!

2단계 미션 피드백 반영 잘 해주셨습니다! 추가 코멘트 남겼는데, 3단계 미션 진행 중에 반영해도 충분해 보이네요.

머지하도록 하겠습니다!

3단계 미션 화이팅입니다!

2024-12-11 10:06 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/PlayerCardDeck.kt
> +        score = CardScore(cardsSum)
해당 계산 로직은 좀 더 개선이 가능해보이네요! 블랙잭 미션 4단계까지 진행하면서 로직을 좀 더 간결하게 개선할 수 있을지 고민해보세요!

2024-12-11 10:06 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/Player.kt
> +    fun findEnabledMoreCard(isDealer: Boolean = false): Boolean = deck.score.isEnabledMoreCard(isDealer)
player에게 카드를 받을 수 있는지에 대한 상태를 관리하는 방향으로 리팩토링을 해보는 건 어떨까요?

아마 위와 같이 리팩토링을 하면 addCard() 를 할 때마다 플레이어의 상태가 변경되어질거에요.

2024-12-11 10:06 UTC, Flamme1004K commented on src/main/kotlin/blackjack/domain/GamePlayers.kt
> +) : Collection<Player> by players {
오~ delegation을 사용하셨군요 👍👍

GamePlayers에 사용할 list 함수를 추가적으로 선언하는 것보다, list 함수를 delegation하여 사용하는 것이 더 효율적이라고 생각하신걸까요~?

2024-12-11 10:06 UTC, Flamme1004K commented on src/test/kotlin/blackjack/CardScoreTest.kt
> +
요 테스트케이스는 다음 미션 때 빛을 발휘하겠네요!

2024-12-11 10:06 UTC, Flamme1004K commented on src/test/kotlin/blackjack/PlayerCardDeckTest.kt
> +            )
`@CsvSource` 로 반복적인 테스트 케이스를 하나로 모을 수 있어보여요!

2024-12-11 10:06 UTC, Flamme1004K commented on src/test/kotlin/blackjack/CardDeckTest.kt
> +class CardDeckTest {
CardDeckTest, CardScoreTest, PlayerCardDeckTest, PlayerTest 모두 훌륭하게 잘 해주셨어요!

나머지 남은 domain 클래스도 테스트 코드 작성해주시면 더 좋겠네요~ 🤩

2024-12-11 10:06 UTC, merged