[Step2] 블랙잭 미션 제출합니다.
next-step/kotlin-blackjack pull request #775
Opened 2024-12-06 16:37 UTC by ahn-sj

안녕하세요 리뷰어님! 요근래 골골대느라 제출이 많이 늦었습니다.. 
이번 리뷰 잘 부탁드립니다 !

2024-12-07 14:21 UTC, Flamme1004K requested changes
안녕하세요! 몸은 좀 괜찮으신가요?  11월 12월 기온차가 너무 커서 많은 분들이 아프시더라고요 ㅜ.ㅜ;; 저도 지난주에 골골 됐네요. 항상 건강 챙기시길 바랍니다.

2단계 미션은 매우 잘 해주셨어요! 몇 가지 코멘트 남겼으니 확인 후 리뷰 요청 부탁드립니다.

감사합니다!

2024-12-07 14:21 UTC, Flamme1004K commented on README.md
> +  - [x] 플레이어는 이름을 가진다.
기능 요구 사항 잘 정리해주셨어요!

구현이 완료 된 기능에 대해서는 체크하는게 좋겠죠?

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/BlackJackApplication.kt
> +    val gamePlayer = Players(playerNames.map { Player(PlayerName(it)) })
```suggestion
    val gamePlayer = Players.of(playerNames)
```

정적 팩토리 메서드로 playerNames를 통하여 만들어 주는 건 어떨까요?

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/BlackJackApplication.kt
> +        }
플레이어의 상태 관리 코드 잘 해주셨어요!

제 생각에는 InputView.inputMoreCard(player.name) 를 통해서, player의 상태를 변경해줄 수 있어보이는데요. 플레이어의 상태를 받지 않는다 라는 상태로 변경하고, while문에서 input에 대한 값을 비교하는 게 아닌, player의 상태를 통하여 비교하는 방향으로 변경해보는 건 어떨까요?

그러면, BlackJackGame class로 현재의 로직을 넣을 수 있어보여요!

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/CardNumber.kt
> +    ONE("A", 1),
ONE 보다는 ACE로 표현해주는 건 어떨까요?

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Cards.kt
> +
backingProperty 사용 잘 해주셨네요~! 👍

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Cards.kt
> +    }
```suggestion
    fun bestScore(): Int {
        return possibleScoreSum().filter { it <= BLACKJACK }.max()
    }
```

max() / maxOrNull() 중에 maxOrNull를 사용한 이유가 있으실까요?

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Cards.kt
> +    }
Bust / BlackJack 등등 블랙잭 게임에서는 여러 상태 값이 존재하죠! 상태 값을 플레이어가 가질 수 있도록 만들어보는 건 어떨까요?

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Cards.kt
> +        private const val BLACKJACK = 21
블랙잭 게임은 카드의 합이 21이라고, 모두 블랙잭은 아니에요!

한번, 블랙잭에 대한 상태가 어떻게 만들어지는지 알아보시고, 적용해 보시겠어요?

2024-12-07 14:21 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Deck.kt
> +data class Deck(private val _cards: MutableList<Card> = createCardPack().shuffled().toMutableList()) {
잘 만들어 주셨네요~ 👍

2024-12-07 14:21 UTC, Flamme1004K commented on src/test/kotlin/blackjack/CardsTest.kt
> +    "보유한 카드팩의 합이 21이 넘으면 버스터(탈락)가 된다." {
테스트 케이스 매우 잘 만들어주셨어요!

단, 버스터에 대한 테스트 케이스만 있네요.

카드 점수에 대한 테스트가 있었으면 좋겠어요 :) 일반적인 카드 점수 테스트부터 ACE에 대한 테스트 여러개가 있는 테스트까지 여러 상황에 대한 테스트 케이스 작성 부탁드릴게요~

2024-12-07 14:21 UTC, Flamme1004K commented on src/test/kotlin/study/DslTest.kt
> + */
저번 커밋 로그까지 섞여서 들어왔네요.

다음에는 미션 및 온라인 코드 리뷰 페이지를 통해서 3단계 미션에 대한 부분만 커밋이 남도록 만들어주세요~

2024-12-08 05:49 UTC, ahn-sj commented on src/main/kotlin/blackjack/BlackJackApplication.kt
> +        }
말씀을 들어보니 플레이어는 진행 상태를 필드로 가지는게 괜찮은 방법인 것 같네요 !

> InputView.inputMoreCard(player.name) 를 통해서, player의 상태를 변경해줄 수 있어보이는데요.

다만, 전달해주신 방법에서 이 내용을 제가 잘 이해하지 못한 부분인데요, 
제가 이해한 방식을 수도 코드로 나타내면 다음과 같습니다!
```kotlin
fun inputMoreCard(name: PlayerName): Boolean {
    println("${name.value}는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)")
    // player의 상태를 입력값에 따라 player의 상태를 변경한다.
    // 1. y인 경우 player.takable() -> 받을 수 있는 상태로 변경
    // 2. n 경우 player.nonTakable() -> 받을 수 없는 상태로 변경
}
```

이랬을 때 화면(InputView)에서 변경이 일어나는 건 아닐까.. 하는 생각이 들었는데요,
그래서 혹시 제가 이야기 해주신 맥락을 다르게 이해한건지 궁금하여 여쭈어봅니다..!

2024-12-08 05:55 UTC, ahn-sj commented on src/main/kotlin/blackjack/Cards.kt
> +
백킹 프로퍼티를 처음 사용해보았을 때 [장단점을 남겼던 적](https://github.com/next-step/kotlin-lotto/pull/1066#discussion_r1862150970)이 있는데요,
개인적으로 변경 불가능한 컬렉션을 관리할 수 있다는 점에서 전 단점보다 장점이 많다고 생각되는데, 혹시 형준님은 백킹 프로퍼티를 자주 사용하시거나 선호하시는 편이신지 궁금합니다 !

2024-12-08 05:57 UTC, ahn-sj commented on src/main/kotlin/blackjack/Cards.kt
> +        private const val BLACKJACK = 21
🫢😵‍💫😱🤯

2024-12-08 06:13 UTC, ahn-sj commented on src/main/kotlin/blackjack/Cards.kt
> +    }
BLACKJACK = 21로 지정을 했기 때문에 만약, 22점을 초과하는 스코어라면 max()에 의해 아무런 엘리먼트를 찾을 수 없어서 NoSuchElementException이 발생했기 때문이었습니다.

다만, 이건 제가 블랙잭에 대한 규칙을 잘 숙제하지 못한 탓에 이러한 문제가 발생됐다고 생각되는데요,
아래 코멘트에서 규칙과 관련하여 이야기 해주셨듯이 다음 PR에서 해당 내용을 개선해보겠습니다 ! 

> 블랙잭 게임은 카드의 합이 21이라고, 모두 블랙잭은 아니에요!
한번, 블랙잭에 대한 상태가 어떻게 만들어지는지 알아보시고, 적용해 보시겠어요?

2024-12-08 07:20 UTC, Flamme1004K commented on src/main/kotlin/blackjack/BlackJackApplication.kt
> +        }
네네! 맞아요! 단, 상태를 변경해주는 것은 inputMoreCard 보다는, BlackJackApplication.class 내부에서 진행이 되어야한다고 생각해요!
```
while (player. takable()) {
            var 추가드로우여부 = InputView.inputMoreCard(player.name)
            if(!추가드로우여부) {
                      break;
            }
            player.take(deck.pick())
            OutputView.printPlayerCard(player)
        }
```

아마 이런 모습이 되지 않을까 하네요!?

2024-12-08 07:25 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Cards.kt
> +
backingProperty를 상황에 맞게 사용하는 것 같아요!

cards class 처럼 클래스 내부에서 가변 배열을 다루어야한다면, backingProperty를 사용하는 편입니다. 그렇지 않은 경우에는 최대한 불변을 맞춰 코드를 작성하고 있어요.

추가로, backingProperty 말고, 정말 list 함수 대부분을 사용해야하는 경우에는 delegate도 간혹 사용하고 있습니다 :) 

- https://kotlinlang.org/docs/delegation.html

2024-12-13 12:41 UTC, ahn-sj reviewed
한 가지 피드백 내용에 대해서 약간은 다른 저의 시선이 있어서 제 생각을 남겨보았습니다!

2024-12-13 12:41 UTC, ahn-sj commented on README.md
> +- [ ] 플레이어의 상태(Bust, Blackjack)를 추가
지난번에 피드백 주셨던 내용들을 정리하고 반영하는 과정에서 플레이어의 상태를 추가할까에 대한 고민을 해보았습니다.

현재의 요구사항에서는 카드의 스코어를 계산하는 방식으로도 해결이 가능해보였고, 별도로 화면에 버스터나 블랙잭이라는 상태 결과를 보여주어야 하는 곳이 없는걸로 보여서 해당 내용은 제외하였는데요,
혹시 형준님이 의도하신게 있으셨는데 제가 미처 바라보지 못한 부분이 있는건지 궁금합니다 !

2024-12-13 13:48 UTC, Flamme1004K commented on README.md
> +- [ ] 플레이어의 상태(Bust, Blackjack)를 추가
별도로 화면에 버스터나 블랙잭이라는 상태 결과를 보여주어야 하는 곳은 없죠! 아마, 블랙잭 미션의 마지막 미션까지도 상태에 대한 결과를 보여주는 뷰는 존재하지 않을거에요.

성재님이 작성해준 블랙잭 코드는 매우 잘 작성이 되었고, 매우 블랙잭 게임과 유사하게 돌아가고 있었습니다. 이 중에서 좀 더 부족한 부분을 채워줄 수 있는 방법이 코드에 블랙잭 게임에 대한 도메인 룰을 더해주는게 어떨까 했구요. 그 중 하나가 플레이어에 대한 상태이죠. 기본적인 블랙잭 도메인에는 BUST, BLACKJACK, STAY, HIT 라는 플레이어에 대한 상태를 가지고 있습니다. 각 상태는 카드 숫자와 유저 액션에 따라 다르게 적용됩니다. 

제가 생각하는 백엔드 관점에서의 뷰는 그저 프론트의 화면을 그려주는 요구사항입니다. 뷰가 그려지는 안에서는 매우 복잡한 도메인 로직이 실행이 되죠. 매우 복잡한 도메인 로직을 뷰만 만들어질 수 있도록 단순하게 구현되면 좋겠지만, 어느 정도는 내가 만드는 도메인에 대한 구조가 잡혀야 되고, 이 구조 속에서 계속해서 단순화해서 구현해야 하는 부분이라고 생각합니다.

저는 그 구조 중 하나를 잡는 게 바로 도메인에 있는 규칙이라고 생각합니다. 플레이어의 상태도 블랙잭 게임의 규칙이 될 수도 있겠죠. 이 규칙이 현재로서는 제외해도 괜찮겠지만, 도메인이 복잡해지고, 기존의 규칙에 새로운 규칙을 추가할 때마다 많은 변경이 있다고 생각해요. 이 많은 변경을 최소화하고 단순화하고자 구조를 잡는 거고, 이것을 증명하기 위해 테스트 코드가 있다고 생각해요.

글이 생각보다 길어졌네요. 한번 읽어보시고 더 다양한 이야기 해보시죠~ ㅎㅎ

2024-12-13 13:54 UTC, Flamme1004K approved these changes
안녕하세요!

2단계 미션 매우 잘 해주셨어요! 이만 머지하도록 하겠습니다.

3단계 미션 화이팅입니다~

감사합니다!

2024-12-13 13:54 UTC, Flamme1004K commented on src/main/kotlin/blackjack/Players.kt
> +}
정적 팩토리 메서드 사용 좋네요~!

2024-12-13 13:54 UTC, Flamme1004K commented on src/main/kotlin/blackjack/BlackJackApplication.kt
> +    }
피드백 반영 잘 해주셨어요!

나중에 player가 카드를 뽑는 행위를 인터페이스화 시키면 해당 로직도 BlackJackGame에 넣을 수 있어보이네요 😊

2024-12-13 13:55 UTC, merged

2024-12-13 14:12 UTC, ahn-sj commented on README.md
> +- [ ] 플레이어의 상태(Bust, Blackjack)를 추가
안녕하세요 형준님! 정성 가득한 답변에 깜짝 놀랐습니다.......! (정말요.. 🤩🤩)

얼마전에 저도 신규 프로젝트에서 설계하는 과정에서 '우리 회사의 비즈니스 전략은', '우리 도메인 특성은'에 대해 고민했던 시기가 있었습니다. 이는, 형준님이 이야기 해주신 구조처럼 변경이 적고, 확장 가능한 설계를 위해 필요했던 고민이었는데요, 무엇을 운운하기에 성숙한 경험을 가지지는 못했지만 도메인 지식은 정말정말 중요하다는걸 느꼈었습니다.
이러한 관점에서 형준님이 해주신 코멘트는 저에게 조금 더 숲을 바라볼 수 있게 가이드 해주신 말씀이라 너무 감사드립니다..!

다음 PR에서는 플레이어의 상태에 대한 부분과 다음 스텝의 요구사항들도 블랙잭 도메인을 생각하면서 미션을 진행해보겠습니다.
너무너무 좋은 말씀해주셔서 감사합니다 !!!! 💯💯

2024-12-14 06:57 UTC, Flamme1004K commented on README.md
> +- [ ] 플레이어의 상태(Bust, Blackjack)를 추가
좋습니다!! 다음 미션 기대하겠습니다! 화이팅입니닷 +_+!