[Step3] 3단계 - 블랙잭(딜러)
next-step/kotlin-blackjack pull request #776
Opened 2024-12-06 17:08 UTC by nooblette

안녕하세요 동철님 3단계 미션 제출 드립니다.

구현 내용은 다음과 같습니다.
1. step2 리뷰 내용 반영 (카드를 뽑고 리스트에서 제거하는 행위를 Deck.kt으로 위임)
2. step3 기능 목록 작성, 클래스의 책임을 함께 작성
3. step3 기능 구현

3단계 미션도 잘 부탁드립니다. 🙇  감사합니다.

2024-12-07 12:04 UTC, sah3122 requested changes
딜러 미션 구현 잘해주셨습니다 👍 
몇가지 생각거리를 남겨두었는데 확인 부탁드려요 !

2024-12-07 12:04 UTC, sah3122 commented on src/main/kotlin/blackjack/dealer/Dealer.kt
> +class Dealer(
딜러 클래스 정의 👍

2024-12-07 12:04 UTC, sah3122 commented on src/main/kotlin/blackjack/dealer/Dealer.kt
> +) : Player(name = name, hand = hand) {
딜러와 플레이어를 상속 구조로 정의해주셨는데, 딜러와 플레이어는 직접적인 상속관계를 가지기 보단 두 클래스간 공통 인터페이스만 분리하여 상속 구조로 정의 하는것은 어떨까요 ? 
직접적인 상속 구조로 정의해주신 이유가 있을까요 ?

2024-12-07 12:04 UTC, sah3122 commented on src/main/kotlin/blackjack/machine/BlackJackMachine.kt
> +        if (dealer.isDraw()) {
메서드 네이밍이 적절하지 않은것 같습니다. 
딜러가 카드를 뽑아야한다는 메서드 네이밍을 고민해보세요 😄

2024-12-07 12:04 UTC, sah3122 commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        }
승패를 계산 하는 비즈니스 로직이 외부에 노출되면 어떤 문제점이 있을까요 ?
상태값을 가지는 도메인 객체인 플레이어, 딜러 클래스로 책임을 옮겨 보세요 😄

2024-12-08 07:38 UTC, nooblette commented on src/main/kotlin/blackjack/dealer/Dealer.kt
> +) : Player(name = name, hand = hand) {
블랙잭 게임 상황을 생각해봤을때, _딜러도 플레이어로 볼 수 있지 않을까?_ 란 생각에 상속으로 설계하였습니다.
동철님 리뷰를 보고 고민해보니 두 클래스의 공통 인터페이스를 두어 타입을 정의하고 공통 메서드를 제공하는게 적절할 수 있겠네요 🤔 

더 추상화된 타입인 `Participant` 인터페이스를 두고 각각 `Dealer`와 `Player` 클래스가 이를 구현하도록 수정했습니다.
인터페이스를 통해 default 메서드도 제공하다보니 중복도 제거하면서 코드가 훨씬 명확해진 것 같아요! 

의견 감사합니다 👍

2024-12-08 07:39 UTC, nooblette commented on src/main/kotlin/blackjack/machine/BlackJackMachine.kt
> +        if (dealer.isDraw()) {
메서드 명을 `drawIfAllowed`로 수정하면서 카드를 뽑는 행위도 `Dealer` 클래스로 이동했습니다.
더 자연스럽게 객체가 책임을 갖는 구조가 된 것 같아요! 리뷰 감사합니다

2024-12-08 07:46 UTC, nooblette commented on src/main/kotlin/blackjack/view/ResultView.kt
> +        }
누가 승자인지 판단하는 로직은 `ResultView`에서만 사용하니까, _도메인이 뷰에 의존하지 않으려면 뷰에 구현하는게 적절하지 않을까?_ 라는 생각으로 뷰에 정의했었습니다.

다만 리뷰를 보고 고민해보니, 승자를 판단하는 로직은 단순 출력이 아니라 도메인에 특화된 비즈니스 로직이니 `Dealer`와 `Player`클래스가 그 책임을 갖는게 적절해보이네요.
그리고  다른 개발자가 승자 판단 로직의 구현을 찾는다면 이 두 클래스를 가장 먼저 살펴볼 것 같아요 😅

위에서 주셨던 리뷰에 따라 공통 인터페이스 `Participant`를 정의하면서, 이 부분에 승자 판단 로직도 선언하여 로직을 추상화하였습니다.

```kotlin
interface Participant<out T : Participant<T>> {
    val name: String
    val hand: Hand

    fun isBust(): Boolean = hand.sum() > BlackJackMachine.BLACKJACK

    fun isWin(opponent: Participant<*>): Boolean =
        when {
            isBust() -> false
            opponent.isBust() -> true
            else -> hand.sum() > opponent.hand.sum()
        }

}
```

덕분에 객체지향적인 설계에 대해 많은 고민을 해볼 수 있었어요 리뷰 감사합니다 👍

2024-12-09 09:13 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
사소한 고민거리를 추가로 남겨두었는데 다음 미션을 진행하며 반영 부탁드려요 !

2024-12-09 09:13 UTC, sah3122 commented on src/main/kotlin/blackjack/participant/Participant.kt
> +interface Participant<out T : Participant<T>> {
참가자 인터페이스 정의 👍

2024-12-09 09:13 UTC, sah3122 commented on src/main/kotlin/blackjack/participant/Participant.kt
> +    fun isWin(opponent: Participant<*>): Boolean =
승 / 패의 구현이 참가자 인터페이스에 존재하면 딜러에 특화된 기능이나 플레이어에 특화된 기능을 제공하지 못할수 있습니다. 
`딜러가 21을 초과하면 그 시점까지 남아 있던 플레이어들은 가지고 있는 패에 상관 없이 승리한다.`와 같은 요구사항을 만족하려면 어떤 변화를 주어야 할까요 ?

2024-12-09 09:13 UTC, sah3122 commented on src/main/kotlin/blackjack/dealer/Dealer.kt
> +        if (isDraw()) {
`딜러는 처음에 받은 2장의 합계가 16이하이면 반드시 1장의 카드를 추가로 받아야 하고,` 라는 의미를 코드에 녹여보세요 😄

2024-12-09 09:13 UTC, merged