[Step3] 블랙잭(딜러)
next-step/kotlin-blackjack pull request #789
Opened 2024-12-09 12:24 UTC by kimihiqq

안녕하세요 리뷰어님! 🙂
이번 PR에서는 Step3 블랙잭(딜러) 기능들을 구현해 추가했습니다.
이번 단계도 잘 부탁드립니다. 🙇

2024-12-09 15:48 UTC, Wordbe requested changes
Step3 블랙잭(딜러)를 잘 구현해주셨네요.
실제로 코드 리뷰 하기가 수월했습니다.

댓글 드린내용 한번 확인해보시고, 가능하시면 반영 부탁드립니다 😊

2024-12-09 15:48 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    val results: Map<String, Result>,
<이름, 게임결과> 인 것 같은데 객체로 만들어보면 어떨까요? 
객체는 속성이 있어서 설명이 자체적으로 가능할것같아요 😀

2024-12-09 15:48 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +        val dealerWins = results.values.count { it == Result.LOSE }
results 가 players 를 말하는 거면 변수명이 좀 더 정확하면 이해가 편할것같아요 🙂

2024-12-10 12:40 UTC, kimihiqq commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    val results: Map<String, Result>,
리뷰 감사합니다! 객체를 분리하는 쪽으로 수정했습니다!

2024-12-10 14:36 UTC, Wordbe approved these changes
리뷰를 잘 반영해주셨네요. 감사합니다.
전반적으로 보기 쉬운 코드가 된 것 같습니다.
다음 스텝으로 넘어가 보시죠! 🚀🚀

추가로 드린 코멘트는 옵션입니다. 가능하시면 다음 스텝에서 반영해주세요 :)

2024-12-10 14:36 UTC, Wordbe commented on src/main/kotlin/blackjack/domain/GameResultCalculator.kt
> +                    GameResult.PlayerGameResult(
여긴 인덴트가 좀 과한것같아 조금만 수정해볼 수 있을까요? 😀

2024-12-10 14:36 UTC, merged