[Step3] 3단계 블랙잭(딜러) 미션
next-step/kotlin-blackjack pull request #794
Opened 2024-12-10 14:47 UTC by mdy0501

- 안녕하세요. 3단계 블랙잭 미션 제출합니다.
- Cards 클래스에서 cards의 totalScore()를 구할 수 있도록 작성했는데 이 부분이 지난번에 받았던 피드백과 반대되는 것 같아서 추가로 설명을 적어봅니다.
  - 저는 CardNumber가 어떻게 계산될지를 판단하는 로직은 CardNumber 안에 넣었고, Cards 안에 totalScore()를 넣는 것이 더 응집력이 있다고 생각했습니다. (따로 클래스를 만드는 것보다)
  - Cards 클래스가 카드를 더하는 (add 함수) 역할과 cards 점수를 계산(totalScore())하는 역할이 있어서 2개의 역할을 갖고 있다고 생각하실 수도 있을 것 같지만 둘다 Cards 클래스 안에 있을때 코드를 유지보수 하기 더 좋다고 생각되었습니다.
  -> 이 부분에 대한 리뷰어님의 의견이 궁금합니다.

2024-12-11 13:38 UTC, BeokBeok commented
@mdy0501 
>Cards 클래스에서 cards의 totalScore()를 구할 수 있도록 작성했는데 이 부분이 지난번에 받았던 피드백과 반대되는 것 같아서 추가로 설명을 적어봅니다.

제가 관련 내용을 찾지 못해서 여쭙는데요. 😅 
지난번에 받았던 피드백과 반대되는 것 같다고 말씀을 주셨는데, 혹시 어떤 피드백이 반대되는 피드백이였는지 알려주실 수 있으실까요? 🙏 

> Cards 클래스가 카드를 더하는 (add 함수) 역할과 cards 점수를 계산(totalScore())하는 역할이 있어서 2개의 역할을 갖고 있다고 생각하실 수도 있을 것 같지만 둘다 Cards 클래스 안에 있을때 코드를 유지보수 하기 더 좋다고 생각되었습니다.

동연님이 말씀하시는 Cards 클래스 안에 있을 때 유지보수하기 좋다고 판단하신 근거가 궁금합니다!
다른 개발자가 보았을 때 카드 점수를 계산하는 로직을 수정한다고 가정했을 때, Cards 클래스에 카드 점수를 계산하는 로직이 있다는 것이 쉽게 인지할 수 있을까요? 🤔

2024-12-11 14:13 UTC, BeokBeok requested changes
이전 단계 피드백과 블랙잭(딜러) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/CardNumber.kt
> +            11 // ACE를 11로 사용할 수 있는 경우
숫자 10과 숫자 11은 각각 어떤 것을 의미할까요?
숫자만 보고서 어떤 것을 의미하는지 알 수 있도록 개선해보면 어떨까요?

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/Dealer.kt
> +) : Participant(name, cards) {
상속 활용 👍

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/Dealer.kt
> +        return this.score() < 17 // 딜러는 17 미만일 때만 카드를 받을 수 있음
숫자 17이란 어떤 것을 의미할까요?
숫자만 보고서 어떤 것을 의미하는지 알 수 있도록 개선해보면 어떨까요?

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/GameManager.kt
> +import blackjack.step2.view.InputView
domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현해보면 어떨까요?

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/GameManager.kt
> +    private fun processPlayerTurn(player: Player): Player? {
함수 자체는 "전달받은 데이터를 처리한다" 라는 의미를 내포하고 있습니다.
해서, process 보다 좀 더 의미를 드러낼 수 있도록 네이밍을 하면 좋을 것 같은데 동연님은 어떻게 생각하시나요?

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/Participant.kt
> +sealed class Participant(
sealed class 활용 👍

2024-12-11 14:13 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/GameManager.kt
> +            }
is 연산자를 사용해서 Player일 경우와 Dealer일 경우에 대해 어떻게 동작해야하는지 분기처리를 해주셨네요.
지금도 좋지만, 다형성을 활용하여 개선해보면 어떨까요?

2024-12-12 13:46 UTC, mdy0501 commented
> 제가 관련 내용을 찾지 못해서 여쭙는데요. 😅
지난번에 받았던 피드백과 반대되는 것 같다고 말씀을 주셨는데, 혹시 어떤 피드백이 반대되는 피드백이였는지 알려주실 수 있으실까요? 🙏
- https://github.com/next-step/kotlin-blackjack/pull/756

<img width="626" alt="image" src="https://github.com/user-attachments/assets/02d58c74-72fe-4933-bd5e-7f0def410a52" />

지난번에 주셨던 피드백 중에 Cards 클래스 안에 (1) 카드 뭉치 관리 와 (2) 카드 점수 계산 이 2가지 책임이 있는 것 같다고 피드백을 주셨는데 제가 이번에 Cards 클래스 안에 점수 계산하는 함수를 넣게 되었기 이 부분이 리뷰어 님이 주신 내용과 반대되는 것이라고 생각했었습니다 ㅎㅎ


<br>

> 동연님이 말씀하시는 Cards 클래스 안에 있을 때 유지보수하기 좋다고 판단하신 근거가 궁금합니다!
다른 개발자가 보았을 때 카드 점수를 계산하는 로직을 수정한다고 가정했을 때, Cards 클래스에 카드 점수를 계산하는 로직이 있다는 것이 쉽게 인지할 수 있을까요? 🤔

저는 카드 점수 계산 로직을 넣는 방법이 2가지가 있다고 생각했습니다.
(1) ScoreCalculator 와 같은 object를 만들고, 함수를 만들어서 cards를 매개변수로 넘겨서 계산한다.
(2) Cards 클래스 안에서 Cards가 갖고 있는 cards 들의 점수를 계산한다.

위의 2가지 중에서는 Cards가 이미 cards를 갖고 있기 때문에 별다른 매개변수를 받지 않고 바로 계산할 수 있어서 다른 코드와 의존성이 생기지도 않고 간편히 계산할 수 있다고 생각했습니다!

그렇지만 리뷰어님이 이야기해주신 것처럼 Cards 클래스에 카드 점수를 계산하는 로직이 있다는 것을 다른 사람들이 모를 수도 있겠다는 생각도 듭니다..!

이 부분에 대해 제가 생각하지 못한 또 다른 방법이 있는 것인지? 아니면 리뷰어님이라면 어떤 식으로 접근할지 알려주시면 큰 도움이 될 것 같습니다.


---

@BeokBeok 꼼꼼한 리뷰 감사합니다!
그리고 코멘트 주신 부분들은 다 수정했습니다.

2024-12-12 14:26 UTC, BeokBeok commented
@mdy0501 
> 지난번에 주셨던 피드백 중에 Cards 클래스 안에 (1) 카드 뭉치 관리 와 (2) 카드 점수 계산 이 2가지 책임이 있는 것 같다고 피드백을 주셨는데 제가 이번에 Cards 클래스 안에 점수 계산하는 함수를 넣게 되었기 이 부분이 리뷰어 님이 주신 내용과 반대되는 것이라고 생각했었습니다 ㅎㅎ

와우 알려주셔서 감사합니다. 👍 

> 저는 카드 점수 계산 로직을 넣는 방법이 2가지가 있다고 생각했습니다.
(1) ScoreCalculator 와 같은 object를 만들고, 함수를 만들어서 cards를 매개변수로 넘겨서 계산한다.
(2) Cards 클래스 안에서 Cards가 갖고 있는 cards 들의 점수를 계산한다.
위의 2가지 중에서는 Cards가 이미 cards를 갖고 있기 때문에 별다른 매개변수를 받지 않고 바로 계산할 수 있어서 다른 코드와 의존성이 생기지도 않고 간편히 계산할 수 있다고 생각했습니다!
그렇지만 리뷰어님이 이야기해주신 것처럼 Cards 클래스에 카드 점수를 계산하는 로직이 있다는 것을 다른 사람들이 모를 수도 있겠다는 생각도 듭니다..!
이 부분에 대해 제가 생각하지 못한 또 다른 방법이 있는 것인지? 아니면 리뷰어님이라면 어떤 식으로 접근할지 알려주시면 큰 도움이 될 것 같습니다.

유지보수라는 의미는 어떤 관점으로 바라보느냐에 따라 다른 것 같네요. 😅 
하나의 클래스에서 많은 책임을 갖도록 하면 다른 코드와의 의존성이 생기지도 않고 관리해야하는 클래스의 개수가 줄어들게 되니 유지보수가 더 용이할 것 같은데 이 부분에 대해서 동연님은 어떻게 생각하시나요? 🤔 
동연님이 클래스를 나누는 기준에 대해서 고민을 해보시고 그 기준을 스스로 정해보신다면 큰 도움이 될 것이라 생각합니다! 💪

2024-12-12 14:32 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2024-12-12 14:32 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/CardNumber.kt
> +        private const val ACE_SCORE_DIFFERENCE = 10
ACE의 추가점수만 관리하셔도 좋을 것 같습니다.

2024-12-12 14:32 UTC, BeokBeok commented on src/main/kotlin/blackjack/step2/domain/Participant.kt
> +    ): Participant
다형성 활용 👍

2024-12-12 14:32 UTC, merged