[Step4] 블랙잭(배팅)
next-step/kotlin-blackjack pull request #801
Opened 2024-12-11 12:16 UTC by KimDabomi

지난 리뷰 반영과 배팅 구현했습니다!
지난 리뷰 반영이 꽤나 고난이였어서 그런지 배팅은... 생각보다 간단한 느낌이네요 허허
매 단계마다 허를 찌르는 고등리뷰... 감사합니다..

2024-12-12 07:42 UTC, malibinYun requested changes
4단계 미션 고생 많으셨어요 :)
그렇게 말씀해주시니 더욱 더 열심히 리뷰 해드려야겠다는 생각이 드네요 ㅎ_ㅎ
여러 코멘트 남겨두었으니 확인 후 반영해주세요!

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +    ResultView.printDealerDrawMessage(dealerDrewCard)
게임을 시작했을 때 나타나야 할 콘솔 VIew요소도, interface로 선언 후 구현체를 넘겨주는 형태로 구성해볼 수 있겠어요.
game 객체에서는, notifyPlayerAllReady(), notifyDelaerCard() 등등.. 이런 식으로 호출해주면 콘솔 뷰와 느슨하게 결합할 수 있을 거라 생각해요!

물론 완전히 뷰에 대한 전략을 도메인 자체에서는 절대로 모르게 해야한다는 생각이 더 강하시다면, 이렇게 구성해도 충분하다고 생각해요 :)

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Deck.kt
> +) {
MutableList를 넘겨 해당 가변 객체 내부를 변경시켜볼 수도 있겠지만,
List\<Card> 를 받아 List\<Card>를 반환하도록, 불변객체를 활용해 전략 메서드를 구성해볼 수도 있겠어요!

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Deck.kt
> +        cards.clear()
오 이렇게 기존에 있던 카드를 초기화 해버리면, 1장이 남은 상태에서 초기 카드 2장을 뽑는 등, 여러 게임이 진행되는 떄에는 플레이어가 카드카운팅 전략을 사용하지 못할지도 모르겠어요!

물론 각 게임마다 다른 덱 인스턴스를 만든다면 발생하지 않을 수도 있겠지만, drawCards 메서드가 뽑을 카드의 수를 받는 만큼, 남아있는 카드가 사라지는 상황을 배제해봐도 좋겠어요!

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Deck.kt
> +    fun getCurrentCardCount(): Int = cards.size
테스트만을 위한 메서드는 지양해보는 건 어떨까요?
내부 card 프로퍼티를 get 하는 메서드를 만들어서, 자기 자신을 복사해서 반환하는 방법을 사용해보셔도 좋겠어요!
카운트를 세는 메서드도, cards를 반환 받고 그 개수를 가져와서 비교해보는 것도 좋겠어요 :)

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Game.kt
> +) {
Map을 활용해볼 수도 있겠지만, 이름과 베팅을 묶은 하나의 모델을 만들어 더 의미를 녹여내보는 건 어떨까요?

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Game.kt
> +    fun start(decisionMaker: PlayerDecision): Pair<Map<String, GameResult>, Boolean> {
반환하는 결과 객체도 모델로 묶어 의미를 더 부여해보면 좋겠어요!

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Game.kt
> +        if (dealer.score > 21) {
딜러의 점수를 직접 꺼내 비교하기보다, 메시지를 던져 busted인지 물어보는 형태로 구성해보는 건 어떨까요?

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Hand.kt
> +    }
이름을 plus 로 바꿔보는 건 어떨까요?
코틀린의 MutableList에는 add 하면 내부 값이 바뀌는데,
List 의 확장함수인 plus 를 호출하면 새로운 객체를 반환하도록 구성되어있는 것을 볼 수 있어요.
의도적으로 코틀린 팀이 가변과 불변에 대해 값이 증가하는 것을 단어로써 구분한 게 아닐까 하는 생각이 있어서 제안드려보아요 :)

2024-12-12 07:42 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Player.kt
>          }
부모 클래스가 하위 구현체를 알고 있는 것에서 의존 방향이 적절하지 못하다 생각해요.
점수를 계산하는 것은 딜러의 일은 아니었을지, 혹은 여기에 정말 딜러라는 객체가 필요한지 고민해보시고 선택해보시면 좋겠어요!

또, 카드 점수의 합이 21이기만 하면 블랙잭이 아니에요. 21이면서 2장만을 가지고 있어야 블랙잭인 것이 규칙입니다!

2024-12-13 11:55 UTC, KimDabomi commented on src/main/kotlin/blackjack/BlackjackApplication.kt
> +    ResultView.printDealerDrawMessage(dealerDrewCard)
일부러 뷰와 도메인의 결합을 최소화하려고 한 것이라서 의견 참고만 하겠습니다! ㅎㅎ

2024-12-13 15:57 UTC, malibinYun approved these changes
블랙잭 미션 완주하시느라 고생 많으셨어요!
미션을 진행하시면서 고민했던 점들이 앞으로 큰 도움이 되시면 좋겠어요!
이만 미션은 마무리 하도록 하겠습니다 :)
남은 마지막 미션도 모두 완수하시길 응원할게요! 💪

2024-12-13 15:57 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Deck.kt
> +            throw IllegalStateException(NOT_ENOUGH_CARDS_EXCEPTION_MESSAGE)
덱을 다시 채우는 로직이 빠진 건 다소 아쉬워요.
게임이 한창 진행 중에, 덱이 다 떨어졌을 때 게임이 비정상 종료되면 굉장히 어색할 거라 생각해요!

2024-12-13 15:57 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Game.kt
> +            .map { Player(it.name, it.bet) }
딜러를 문자열로 구분하기 보다, 객체 자체로 다루는 건 어떨까요?
게임에서 딜러라는 문자열을 입력하지 않더라도 게임 전체에는 딜러가 존재해야하고,
플레이어 이름에 딜러라는 이름이 입력 되더라도 그것은 딜러 객체가 아닌, 플레이어 객체로만 취급되게 만들어도 좋겠어요.
혹은 딜러라는 이름을 플레이어 객체가 사용하지 못하도록 막는 로직을 작성하고, 그 예외일 때 입력을 다시 받는 로직을 추가하는 방향도 좋아 보여요!

2024-12-13 15:57 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/GameResult.kt
> +    ;
GameResult가 갖고 있는 값은 Console View에 종속적이라 생각해요.
View에서 GameResult 분기로 원하는 출력 문자열을 반환하도록 구성해보는 건 어떨까요?

2024-12-13 15:57 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/GameRules.kt
> +    }
딜러와 플레이어의 점수를 비교해서 딜러와의 승패가 결정나는 것이니,
딜러 객체가 플레이어를 받아 결과 객체를 반환하는 역할을 부여해봐도 좋겠어요 :)

2024-12-13 15:57 UTC, malibinYun commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        return score == 21 && cards.size == 2
점수 계산을 Hand가 하고 있으니, Blackjack인지도 Hand에게 메시지를 던져 물어볼 수 있겠어요 :)

2024-12-13 15:57 UTC, merged