[Step4] 블랙잭(베팅)
next-step/kotlin-blackjack pull request #810
Opened 2024-12-15 11:15 UTC by chicori3

안녕하세요 현석님
요새 이래저래 신경쓰이는 게 많아 미션을 수행하지 못해 
1주일 만에 리뷰요청 드립니다 🙇‍♂️

잘 부탁드립니다

2024-12-15 12:55 UTC, BeokBeok requested changes
이전 단계 피드백과 블랙잭(베팅) 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2024-12-15 12:55 UTC, BeokBeok commented on src/main/kotlin/blackjack/application/BlackjackGame.kt
> +    private fun setup(): Pair<List<Player>, Dealer> {
Pair는 두 개의 데이터를 간편하게 하나로 묶을 수 있는 장점이 있지만, first가 무엇인지 second가 무엇인지 알기 어렵다는 단점이 있습니다.
좀 더 가독성있도록 개선해보면 어떨까요?

2024-12-15 12:55 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Bet.kt
> +@JvmInline
value class 활용 👍

2024-12-15 12:55 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/GameState.kt
> +        get() = bet.value
프로그래밍 요구사항에는 아래와 같은 항목이 있습니다.
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

이 요구사항을 반영해보면 어떨까요?

2024-12-15 12:55 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = gameState.betValue
프로그래밍 요구사항에는 아래와 같은 항목이 있습니다.
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

이 요구사항을 반영해보면 어떨까요?

2024-12-15 12:55 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Rule.kt
> +object Rule {
클래스명만 봤을 때 "규칙" 을 담당하는 것으로 이해를 했습니다.
다만, 이름이 너무 일반적이다보니, 어디까지를 규칙으로 봐야하는 건지 잘 모르겠는데요. 🤔 
클래스가 하나의 책임만을 가질 수 있도록 이름을 명확하게 작성해보면 어떨까요?

2024-12-15 13:00 UTC, chicori3 commented on src/main/kotlin/blackjack/domain/GameState.kt
> +        get() = bet.value
hands와 bet 을 가지고 있는데 hands 안에 있는 card들도 포함해서 일까요??

2024-12-15 13:00 UTC, chicori3 commented on src/main/kotlin/blackjack/application/BlackjackGame.kt
> +    private fun setup(): Pair<List<Player>, Dealer> {
같은 클래스 내에서 사용하기 때문에 괜찮지 않을까라고 생각했습니다
변경해볼게요

2024-12-15 13:08 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/GameState.kt
> +        get() = bet.value
@chicori3 
https://github.com/next-step/kotlin-blackjack/pull/810/files/044f40275a070ab010fe293f785ab585aeee13c6#r1885694986 에 대한 코맨트가 잘못 들어갔네요!
혼선을 드려 죄송합니다. 😭 🙏

2024-12-15 13:08 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/GameState.kt
> +        get() = bet.value
@chicori3 
이 코맨트는 Resolve 처리하겠습니다!

2024-12-15 13:48 UTC, chicori3 commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = gameState.betValue
Participant에도 name과 gameState 변수 둘이긴 한데 혹시 어디가 문제일까요??

2024-12-15 13:52 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = gameState.betValue
@chicori3 
gameState를 사용하는 부분은 괜찮아 보입니다. 👍 
다만, isBlackjack과 같이 Rule에 직접 접근하는 부분에 대해서는 어떻게 생각하시나요? 🤔

2024-12-15 13:58 UTC, chicori3 commented
Pair 대신에 Participants라는 타입을 정의해서 써봤어요
이 클래스 내에서만 쓰이는 데이터라서 내부 클래스로 정의해서 썼는데
적절하게 사용한 것인지 궁금합니다 🧐

2024-12-15 14:11 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = BlackjackRule.isBlackjack(score, handSize)
BlackjackRule이 object이다보니 아무런 제약없이 클래스 내부에서 직접 접근이 가능합니다.
즉, Participant는 BlackjackRule에 의존하고 있으며, BlackjackRule 변경에 따라 영향을 받게 됩니다.
제가 https://github.com/next-step/kotlin-blackjack/pull/810#discussion_r1885694986 와 같은 코맨트를 작성한 이유는, BlackjackRule를 생성자로 받게 되면 프로그래밍 요구사항에 위반되어 지금과 같이 하신 것으로 이해하고 코맨트를 작성하였습니다. 🙇

2024-12-15 14:11 UTC, BeokBeok commented on src/main/kotlin/blackjack/application/BlackjackGame.kt
> +    data class Participants(
클래스 내부에서만 사용한다면 private 접근자를 붙여보면 어떨까요!?

2024-12-15 15:58 UTC, chicori3 commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = BlackjackRule.isBlackjack(score, handSize)
아하
우선 이전에 Status라는 값으로 버스트인지, 플레이 가능한지 상태를 관리했는데
그런 상태는 점수에 의존하기도 하고, 스코어 계산에서도 버스트 여부를 판단하다 보니
공통으로 사용될 수 있는 Rule 에서 사용하자라고 생각을 했어요

블랙잭 룰은 블랙잭 게임의 핵심이라고 생각해서 룰이 변경된다면 변경이 되는 것도 그럴듯하지 않나라는 생각인데
더 나은 방법이 있을까요?  😓

2024-12-16 13:02 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2024-12-16 13:02 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = BlackjackRule.isBlackjack(score, handSize)
@chicori3 
Participant가 블랙잭인지 버스트인지에 대한 판단을 스스로 해야하는걸까요?
시안님이 말씀하시는 응집도란 무엇을 의미하는지 궁금하네요!
객체들은 협력하는 구조로 개선해보시면 좋을 것 같습니다.
플레이어와 딜러는 본인이 가지고 있는 카드 정보만 알고, 카드 정보를 전달해주면 이 정보를 통해 상태가 무엇인지 판단해주도록 하는 것이 좋을 것 같은데요.
현재 시안님께서 작성하신 구조는, 게임의 규칙이 변경이 된다면 딜러와 BlackjackRule 둘 다 영향을 받게 될 것 같은데 이 부분에 대해서 시안님은 어떻게 생각하시나요?

2024-12-17 15:46 UTC, chicori3 commented on src/main/kotlin/blackjack/domain/Participant.kt
> +        get() = BlackjackRule.isBlackjack(score, handSize)
제가 생각했던 응집도는 Rank에서 점수 계산 시, 딜러와의 결과를 비교할 때 버스트에 대한 판단을 하고 있는데
그럼 버스트에 대한 판단을 한 군데에서 하자 그럼 Rule이라는 개념을 만들고 Rule에 요청하는 것이 응집도가 높겠구나 라고 생각했어요
네이밍 또한 Rule로 지어서 상수를 쓰는데 어색하지 않도록 하려는 목적이었습니다

말씀하신대로 의존 관계에서는 의존하는 대상이 변경되면 영향을 받을 수 밖에 없기 때문에 그 컨텍스트를 최대한 줄여야 하는게 맞는 것 같아요
지금 수정한 코드에서는 Hands에서 버스트와 블랙잭 판단을 위임했고, Rank에서도 점수 계산을 Rule에 의존하지 않도록 변경해봤습니다

할 때는 막막했는데 좀 쉬다가 다시 고민하니까 또 되네요 😂

2024-12-18 12:12 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
시안님과 미션하면서 저 또한 성장하게 된 것 같습니다. 😄 
좋은 개발자가 되기 위한 소중한 경험이 되었길 바랍니다. 💪

2024-12-18 12:12 UTC, BeokBeok commented on src/main/kotlin/blackjack/domain/Hands.kt
> +        get() = Rank.isBlackjack(calculateTotalValue(), size)
Hands로 옮기니 이전보다 훨씬 좋아졌는데요!? 👍

2024-12-18 12:12 UTC, merged