[Step2] 블랙잭
next-step/kotlin-blackjack pull request #82
Opened 2021-03-19 11:19 UTC by bactoria

블랙잭 리뷰 요청드립니다 :)

(참고로, `feat: 블랙잭 게임 추가 (7b8a770)` 이전까지는 페어프로그래밍으로 진행하였어요.)

2021-03-20 07:56 UTC, vsh123 requested changes
준오님 안녕하세요!!
페어프로그래밍이 쉽지 않았을텐데 잘 구현해주셨네요 💯 

몇가지 코멘트를 남겼습니다!
확인 부탁드릴게요~~ :)

2021-03-20 07:56 UTC, vsh123 commented on README.md
> +# 블랙잭 🃏
기능 요구사항 작성 👍

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/userinterface/Console.kt
> +class Console : UserInterface {
Console은 싱글턴일 수 없을까요?

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/userinterface/Console.kt
> +            validateDuplicateName(it)
중복된 이름에 대한 검사가 View의 책임일까요???

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Denomination.kt
> +        val denominations = listOf(this, *otherDenominations.toTypedArray())
저는 아래가 더 깔끔해보이는데, 어떻게 생각하시는가요?
```suggestion
        val denominations = listOf(this) + otherDenominations
```

2021-03-20 07:56 UTC, vsh123 commented on src/test/kotlin/blackjack/domain/DenominationTest.kt
> +    @Test
[ParameterizeTest](https://www.baeldung.com/parameterized-tests-junit-5)를 활용해보는 건 어떨까요?

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Denomination.kt
> +    fun calculateScore(otherDenominations: List<Denomination>): Score {
하나의 Denomination가 다른 Denomination List를 받아 계산을 한다는게 어색한 것 같아요!!
계산에 대한 책임이 Denomination이 맞는지 다시한번 생각해보면 어떨까요?

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +            return firstCard.calculateScore(otherCards)
계산에 대한 책임을 첫번째 카드에게 주는게 맞을까요?

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        get() = _elements.map { it.copy() }
아래와 같이 사용이 가능합니다 :)

```suggestion
        get() = _elements.toList()
```

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        require(this._elements.size == CARDS_MIN_COUNT)
이것과 아래의 validation의 목적이 다른걸까요??

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    fun add(card: Card) {
해당 함수에 대한 단위테스트가 존재하지 않는 것 같아요~!

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        require(elements.size == 52)
매직넘버를 상수화하면 어떨까요?

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        return elements.removeAt(0)
매직넘버를 상수화하면 어떨까요?

2021-03-20 07:56 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +    private val elements = elements.toMutableList()
elements를 구성하기에 List가 최선일까요??

2021-03-20 10:27 UTC, bactoria commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        require(this._elements.size == CARDS_MIN_COUNT)
```kotlin
require(this._elements.size == CARDS_MIN_COUNT) // 초기 사이즈가 2개인지 검증하기 위함
require(this._elements.distinct().count() == CARDS_MIN_COUNT) // 중복인 카드를 검증하기 위함
```

eg.
||위|아래|
|:--:|:--:|:--:|
|[1,1]||예외 발생|
|[1,2,2]|예외 발생||

두 validation은 목적이 다르긴 한데요.
현재 코드는 오해의 소지가 있는 것처럼 보여 의미를 가지도로록 변경해보았어요. 639e0ed

2021-03-20 10:29 UTC, bactoria commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        require(elements.size == 52)
f435e07 반영하였어요. 👍👍

2021-03-20 10:56 UTC, bactoria commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +    private val elements = elements.toMutableList()
코틀린은 Set에서도 `first()`를 사용할 수가 있네요.
Set으로 변경해보았어요 1546210

2021-03-20 11:05 UTC, bactoria commented on src/main/kotlin/blackjack/userinterface/Console.kt
> +class Console : UserInterface {
그동안 `Object` 에 대한 고민은 해보지 않았는데요.
Console의 경우는 싱글톤이 명확하니, Object로 선언하면 좋을 것 같네요👍 a25a0ae

2021-03-20 11:37 UTC, bactoria commented on src/main/kotlin/blackjack/userinterface/Console.kt
> +            validateDuplicateName(it)
만약 `Console`이 다른 `UserInterface 구현체`로 변경되고, 해당 구현체에서 중복된 이름 검증을 빼먹는다면 문제가 되겠네요. 👍

반영하였습니다. b93b127
(`Console`에서 중복된 이름 검증을 제거하지는 않았는데요. View에서도 검증을 하는 건 문제라고 생각되지는 않아서에요 )

2021-03-20 11:56 UTC, bactoria commented on src/test/kotlin/blackjack/domain/DenominationTest.kt
> +    @Test
개인적으로 `ParameterizedTest`를 굉장히 좋아하는데요.
이번 PR에서는 하나도 없었네요 😓
추가해보았어요 1a9e19c

2021-03-20 12:04 UTC, bactoria commented on src/main/kotlin/blackjack/domain/Denomination.kt
> +        val denominations = listOf(this, *otherDenominations.toTypedArray())
`Collection` 확장함수로 `plus` 연산자를 만들어두었군요 🙇‍♂️

2021-03-20 12:11 UTC, bactoria commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    fun add(card: Card) {
감사합니다 👍👍👍 54b0ba4

2021-03-20 12:16 UTC, bactoria commented on src/main/kotlin/blackjack/domain/deck/Deck.kt
> +        return elements.removeAt(0)
https://github.com/next-step/kotlin-blackjack/pull/82#discussion_r598096451 여기서 제거되었군요 🙇‍♂️

2021-03-21 04:58 UTC, bactoria commented on src/main/kotlin/blackjack/domain/Cards.kt
> +        get() = _elements.map { it.copy() }
`toList`가 새로운 리스트 를 생성하는군요 👍👍
5fbf86a

2021-03-21 05:26 UTC, bactoria commented on src/main/kotlin/blackjack/domain/Denomination.kt
> +    fun calculateScore(otherDenominations: List<Denomination>): Score {
페어프로그래밍을 하면서 진도가 안나가고 서로 꽉 막혔었던 부분이네요.

말씀주신 것 처럼 블랙잭 점수에 대한 계산을 `Denomination` 에서 하고 있는데요.
이로 인해 각 `Denomination` 의 점수들이 외부로 노출되지 않는 캡슐화의 장점이 있었던 반면, 
`Denomination`은 블랙잭에 대한 점수(`Score(21)`) 를 알고 있어야 하는 단점이 있었던 것 같네요.

이건 어떠신가요? 458b25f
기존에는 `Denomination` 가 점수를 외부로 공개하지 않았지만, 블랙잭에 대한 점수를 알고 있어야 했다면,
이번에는 `Denomination` 가 점수를 외부로 공개하는 대신, 블랙잭 점수를 모르게 되었어요.



둘 중 하나를 취해야한다면 458b25f 가 좀 더 나을 것 같다고 생각해요.
아래와 같은 요구사항 변경에는 유연할 것 같다고 생각이 들었거든요.
- 추후 Suit 에도 점수가 부여될 가능성이 있다. 
- Card의 개수에 따라 점수 패널티가 있을 가능성이 있다.

하지만 페어프로그래밍을 하면서는 먼 미래에 대해 확장을 열어두는 것은 불필요한 작업일 수 있으니, Denomination에서 계산하자. 
라고 결론이 났었던 것 같네요.

그러다보니 말씀주신 `하나의 Denomination이 다른 Denomination List를 받아 계산한다` 는 코드도 나온 것 같아요.

&nbsp;

추가로 3가지 정도 여쭤보고 싶네요.
- 458b25f 는 개선되었다고 생각하시나요?
- 458b25f 가 기존 코드보다 낫다는 근거에는 확장성일 것 같은데, 또 다른 장점들이 있다면 추가로 말씀주셔도 좋을 것 같아요. (eg. 가독성)
- `Denomination` 에서 점수를 계산할 때 다른 `Denomination List` 를 받지 않고도 구현하는 방법이 있으려나요? 🧐

&nbsp;

혹시 리뷰에 도움이 되실까봐 해서 대충 만들어보았어요.
<img src="https://user-images.githubusercontent.com/25674959/111894705-4388fd00-8a50-11eb-9dfd-3f920691c60b.png" width=230>

2021-03-21 05:27 UTC, bactoria commented on src/main/kotlin/blackjack/domain/Cards.kt
> +            return firstCard.calculateScore(otherCards)
https://github.com/next-step/kotlin-blackjack/pull/82#discussion_r598223775 에서 제거되었습니다

2021-03-21 15:10 UTC, vsh123 approved these changes
준오님 안녕하세요!!
피드백을 반영하시면서 많은 고민이 보였던 것 같습니다 💯 

질문주신 내용에 대해서는 답변을 남겼습니다!
다음 단계에 함께 생각해보면 좋을 것 같아요~~!!!
이번 단계는 머지하도록 하겠습니다!
다음 단계도 화이팅하세요!

2021-03-21 15:10 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +    val score: Score
https://github.com/next-step/kotlin-blackjack/pull/82#discussion_r598223775 에 대한 답변을 여기에다 하도록 할게요!

> 하지만 페어프로그래밍을 하면서는 먼 미래에 대해 확장을 열어두는 것은 불필요한 작업일 수 있으니, Denomination에서 계산하자.
라고 결론이 났었던 것 같네요.

저도 해당 부분에 대해 동의합니다. 확장성을 고려하다가 오버 엔지니어링이되는 경우가 많더라구요 ㅠㅠ

> 458b25f 는 개선되었다고 생각하시나요?

기존에 Card나 Denomination이 가지고 있던 책임보다는 훨씬 개선되었다고 생각합니다 :)

> 458b25f 가 기존 코드보다 낫다는 근거에는 확장성일 것 같은데, 또 다른 장점들이 있다면 추가로 말씀주셔도 좋을 것 같아요. (eg. 가독성)

이 부분은 크게 동의를 하지 못했어요..!! 물론 준오님이 말씀해주신 요구사항 변경들이라면 해당 Cards에 적용하는게 유리할 수 있지만,  그게 Cards에 해당 로직을 위치했다고 해서 확장성이 좋아졌느냐..! 라고 단정짓기는 힘들 것 같아요 ㅠㅠ
또한 개인적으로 계산식이 직관적이지 못한 것 같아요! 확장함수를 통한 계산식은 좋았지만, 처음보는 사람입장에서는 왜 sumDistinct를 해서 계산을 하는지 해석하는데 많은 시간이 걸릴 것 같아요..!

> Denomination 에서 점수를 계산할 때 다른 Denomination List 를 받지 않고도 구현하는 방법이 있으려나요? 🧐

Denomination이 점수를 계산해야하는게 맞을까요?? 저는 Denomination이 계산을 하는게 어색하게 느껴져요!

추가적으로 첨언을 드리자면 아래와 같이 개선해보면 좋을 것 같아요.

* Cards에도 계산 로직이 없을 수 있을까요?
    * 계산을 위한 객체를 새로 만들어 보면 어떨까요?
    * 계산 방법은 다음과 같이 두가지가 있을 것 같아요
        * 에이스가 존재하는 계산 (혹은 primaryScore와 secondaryScore가 서로 다른 카드가 존재하는 계산)
        * 에이스가 존재하지 않는 계산 (혹은 primaryScore와 secondaryScore가 서로 다른 카드가 존재하지 않는 계산)
    * Cards입장에서는 어떤 계산기인지는 모른채 받을 수 있도록 계산기 인터페이스를 구현해보면 어떨까요?

만약 답변이 이해가 안가시거나 추가적으로 궁금한 점이 있으시다면 DM부탁드릴게요!

2021-03-21 15:10 UTC, vsh123 commented on src/main/kotlin/blackjack/domain/Cards.kt
> +                .reduce { acc, card -> acc.sumDistinct(card) }
card가 아니라 scores가 알맞지 않을까요??

2021-03-21 15:11 UTC, merged