Step3 블랙잭(딜러)
next-step/kotlin-blackjack pull request #97
Opened 2021-03-27 05:27 UTC by SeoJinHyuk14

## 요구사항
- 딜러는 처음에 받은 2장의 합계가 16이하이면 반드시 1장의 카드를 추가로 받아야 하고, 17점 이상이면 추가로 받을 수 없다.
- 딜러가 21을 초과하면 그 시점까지 남아 있던 플레이어들은 가지고 있는 패에 상관 없이 승리한다.
- 게임을 완료한 후 각 플레이어별로 승패를 출력한다.

2021-03-28 05:12 UTC, galcyurio requested changes
이번 블랙잭 미션에서 딜러 기능을 추가하는게 가장 어렵지 않을까 생각됩니다.
잘 구현해주셨는데 잘못 구현된 부분과 어울리지 않는 용어들이 몇 가지 보이네요.
다시 한 번 시도해보세요!

2021-03-28 05:12 UTC, galcyurio commented on src/main/kotlin/blackjack/ResultView.kt
> +}
현재 딜러든 플레이어든 상관없이 모든 카드를 공개해서 보여주네요.
딜러는 처음에 나누어준 한 장만 공개합니다.

```
게임에 참여할 사람의 이름을 입력하세요.(쉼표 기준으로 분리)
pobi,jason

딜러와 pobi, jason에게 2장의 나누었습니다.
딜러: 3다이아몬드
pobi카드: 2하트, 8스페이드
jason카드: 7클로버, K스페이드

pobi는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)
y
pobi카드: 2하트, 8스페이드, A클로버
pobi는 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)
n
jason은 한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)
n
jason카드: 7클로버, K스페이드

딜러는 16이하라 한장의 카드를 더 받았습니다.

딜러 카드: 3다이아몬드, 9클로버, 8다이아몬드 - 결과: 20
pobi카드: 2하트, 8스페이드, A클로버 - 결과: 21
jason카드: 7클로버, K스페이드 - 결과: 17

## 최종 승패
딜러: 1승 1패
pobi: 승 
jason: 패
```

2021-03-28 07:48 UTC, SeoJinHyuk14 commented on src/main/kotlin/blackjack/User.kt
> +    }
넵! 이 부분 https://github.com/next-step/kotlin-blackjack/pull/97/commits/11e6a405cf5ac2df0194f185552dbc4927e00f9a 여기서 반영했었습니다!
확인해주셔서 감사합니다 :)

2021-03-28 08:22 UTC, SeoJinHyuk14 commented on src/test/kotlin/blackjack/DealerTest.kt
> +        }
@galcyurio

안녕하세요!
사실 저도 이 부분을 조금 고민을 했는데요.
RandomCardExtractor는 CardExtractor의 is-a 관계이고, 그것에 예외가 있는 케이스가 있을거 같지 않다고 생각이 들었어요.
그래서 abstract를 사용하였는데요.

오히려 interface의 `~을 할 수 있는 (has-a)` 보다는 abstract의 `is-a`를 사용하는게 객체의 관계를 표현하는데 더 명확하다는 느낌을 받았어요! :)

2021-03-28 12:15 UTC, SeoJinHyuk14 commented on src/main/kotlin/blackjack/Player.kt
> +    }
블랙잭을 여러번 해봤음에도 실제로 게임 용어를 잘 알지 못했네요!
`hit`이라는 용어를 쓰기보다 테이블을 두드리는 방식으로 사용해서 용어를 잊고 있었어요! (처음 배울 때 들었던거 같긴하지만..)
리뷰어님이 알려주신 덕에 잘못된 지식을 고칠수 있었네요! 감사합니다 :)

2021-03-28 12:34 UTC, SeoJinHyuk14 commented on src/test/kotlin/blackjack/DealerTest.kt
> +        }
저는 테스트 코드는 가볍게 작성하는 편이고, 날코드도 허용하는 편인데요.
그래서 처음에는 리뷰어님께서 말씀해주신 방법대로 카드를 몇장 정도 수기로 추가하려고 하였습니다.

그런데 카드를 생성할때 카드의 타입과 숫자를 직접 지정하는 코드가 여러번 반복되니, 이쁘지 않다는 느낌을 받았습니다.
또한 현재는 한명의 카드만 뽑고 있지만 여러명의 카드를 뽑았을때의 need가 생기게 되면 더 많은 카드를 추가해야 하는데 이러한 부분을 고려하여 지금과 같은 코드로 변경하였습니다.

ps. 실제 서비스 코드도 랜덤성 코드이다보니, 테스트도 랜덤성으로 작성하는게 통일성이 있지 않을까? 하는 생각도 들었어요.
감사합니다!

2021-03-28 12:43 UTC, SeoJinHyuk14 commented on src/main/kotlin/blackjack/ResultView.kt
> +}
앗! 이 부분은 `기능 요구사항`에 적혀있지 않아서 놓쳤네요!
수정토록 하겠습니다! 감사합니다! 👍

2021-03-28 13:17 UTC, SeoJinHyuk14 commented on src/test/kotlin/blackjack/PlayerTest.kt
> +        players.hit(CardExtractor())
`players.hit`을 검증하는데 있어서 `CardExtractor`라는 서비스 요소를 전달해주는게 가독성을 해친다는 말씀이시군요!
저는 제가 작성한 코드라서 (작성자는 해당 코드의 도메인 지식을 알고 있다는 의미) 해당 코드가 가독성이 좋지 않을수 있다는 생각을 하지 못했네요!
좋은  의견 감사합니다!

해당 테스트는 그저 hit 함수의 결과가 카드를 2장 받는다는 의미를 테스트하는 것이기때문에,
어떠한 종류의 CardExtractor를 전달하던지 간에 큰 의미가 없기 때문에 그대로 서비스 코드의 CardExtractor를 전달하여도 괜찮겠다고 생각을 했어요!

혹시 제가 잘못 이해한것이 있다면 답변 주시면 감사하겠습니다 :)

2021-03-28 13:24 UTC, SeoJinHyuk14 commented on src/main/kotlin/blackjack/ResultView.kt
> +}
수정 내용 : https://github.com/next-step/kotlin-blackjack/pull/97/commits/e8c0a464f5f60350e62b8cd4fe53043b1e15a2be

2021-03-29 08:23 UTC, galcyurio approved these changes
피드백 잘 반영해주셨네요 👍 
코멘트 남겨두었으니 확인부탁드립니다.

2021-03-29 08:23 UTC, merged

2021-03-29 14:40 UTC, SeoJinHyuk14 commented on src/main/kotlin/blackjack/BlackJackGame.kt
> +    fun moreCard(player: Player, randomCardExtractor: RandomCardExtractor) {
아닙니다! 이 부분 수정하도록 하겠습니다! 확인해주셔 감사합니다 :)

2021-03-29 15:26 UTC, SeoJinHyuk14 commented
@galcyurio 안녕하세요!
https://github.com/next-step/kotlin-blackjack/pull/97#discussion_r602984922
답변 주셔서 감사합니다! :)

기능적인 차이를 제외하고 상속이라는 관점에서만 바라본다면 저는 abstract가 완전한 `is-a` 관계라고 생각해요.
리뷰어님 말씀대로 interface가 `is-a` 역할을 할 수 있지만, 제가 느끼기에는 공통적으로 사용되는 특정 기능을 implement 하는 것에 더 집중 되어 있다고 느끼고 있어요.
이 부분에 대해서 리뷰어님의 생각은 어떠한지 궁금하네요 :)

abstract가 interface보다 강한 결합이고 다중 상속이 되지 않기 때문에 가급적 interface를 사용하는게 유리한 케이스가 많다고 알고 있습니다.
하지만 이러한 점을 잘 알고 명확한 관계에서 사용되는 것이라면 오히려 강점도 있다고 생각해요.

예를 들어 제 코드에서는 공통적으로 사용되는 validation을 예로 들수 있을거 같아요.
저는 User가 반드시 이름을 가지고 있어야 한다고 가정을 하였구요.
이를 추상클래스의 초기화에서 validation을 하고 있습니다.
```
init {
        require(name.isNotBlank()) { "이름이 공백이어서는 안됩니다." }
    }
```
interface로 변경한다면 동일한 validation 로직이 Dealer와 Player라는 자식으로 각각 구현이 되어야 할것 같아요.

만약 제가 잘못 인지하고 있는 내용이 있거나, 다른 의견이 있으시다면 추가적으로 말씀 주시면 감사하겠습니다 :)

2021-03-30 02:18 UTC, galcyurio commented
네, 저도 abstract class가 interface보다 `is-a` 관계에 가깝다고 생각합니다.
무조건적인 interface 사용보다 적절하게 abstract class를 사용하면 재사용성 면에서 강점이 있다는 의견에도 동의해요.

그런데 CardExtractor의 경우에는 LowCardExtractor 구현에서 abscract class의 장점이 제대로 발휘되지 않았다는 생각이 들었어요.
`addAll()` 구현과 생성자로 넘겨주는 인자가 똑같고 allCards 생성하는 부분만 filter가 추가된 걸로 보여서 abstract class로 선언해서 얻은 장점이 없어보였거든요.
말씀해주신 방향처럼 별도의 클래스에 따로 구현이 되지 않고 abstract class를 통해 중복 코드를 줄여보면 더 좋을 것 같아요. 😄